Warning: openssl_encrypt(): Unknown cipher algorithm in %s on line %d
bool(false)

Warning: openssl_encrypt() expects parameter 1 to be string, object given in %s on line %d
NULL

Warning: openssl_encrypt() expects parameter 2 to be string, object given in %s on line %d
NULL

Warning: openssl_encrypt() expects parameter 3 to be string, object given in %s on line %d
NULL

Warning: openssl_encrypt() expects parameter 1 to be string, array given in %s on line %d
NULL

Warning: openssl_encrypt() expects parameter 2 to be string, array given in %s on line %d
NULL

Warning: openssl_encrypt() expects parameter 3 to be string, array given in %s on line %d
NULL

Warning: openssl_encrypt(): The authenticated tag cannot be provided for cipher that doesn not support AEAD in %s on line %d
string(44) "iPR4HulskuaP5Z6me5uImk6BqVyJG73+63tkPauVZYk="

Warning: openssl_encrypt(): Key length cannot be set for the cipher method in %s on line %d
bool(false)