bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)

Warning: openssl_pkcs12_export_to_file(): cannot get cert from parameter 1 in %s on line %d
bool(false)

Warning: openssl_pkcs12_export_to_file(): cannot get cert from parameter 1 in %s on line %d
bool(false)

Warning: openssl_pkcs12_export_to_file(): supplied resource is not a valid OpenSSL X.509 resource in %s on line %d

Warning: openssl_pkcs12_export_to_file(): cannot get cert from parameter 1 in %s on line %d
bool(false)