bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
int(3)

Warning: openssl_pkcs12_export(): cannot get cert from parameter 1 in %s on line %d
bool(false)

Warning: openssl_pkcs12_export(): cannot get cert from parameter 1 in %s on line %d
bool(false)

Warning: openssl_pkcs12_export(): supplied resource is not a valid OpenSSL X.509 resource in %s on line %d

Warning: openssl_pkcs12_export(): cannot get cert from parameter 1 in %s on line %d
bool(false)