bool(true)
bool(true)

Warning: openssl_pkcs7_decrypt(): unable to get private key in %s on line %d
bool(false)

Warning: openssl_pkcs7_decrypt(): unable to coerce parameter 3 to x509 cert in %s on line %d
bool(false)

Warning: openssl_pkcs7_decrypt(): unable to coerce parameter 3 to x509 cert in %s on line %d
bool(false)
bool(false)
bool(false)
bool(false)

Warning: openssl_pkcs7_decrypt(): unable to coerce parameter 3 to x509 cert in %s on line %d
bool(false)

Warning: openssl_pkcs7_decrypt(): unable to get private key in %s on line %d
bool(false)
true
true