bool(true)

Warning: openssl_csr_export() expects parameter 1 to be resource, string given in %s on line %d
NULL

Warning: openssl_csr_export(): supplied resource is not a valid OpenSSL X.509 CSR resource in %s on line %d

Warning: openssl_csr_export(): cannot get CSR from parameter 1 in %s on line %d
bool(false)

Warning: openssl_csr_export() expects parameter 1 to be resource, array given in %s on line %d
NULL
bool(true)