*** Testing atan2() : basic functionality ***

-- Iteration 1 --
float(1.570796327)

-- Iteration 2 --
float(1.527345431)

-- Iteration 3 --
float(1.089909047)

-- Iteration 4 --
float(2.051683607)

-- Iteration 5 --
float(1.071020961E-8)

-- Iteration 6 --
float(1.142532174)

-- Iteration 7 --
float(1.99906048)

-- Iteration 8 --
float(0.1841885846)

-- Iteration 9 --
float(1.570259559)

-- Iteration 10 --
float(1.54906062)

-- Iteration 11 --
float(1.570796327)

-- Iteration 12 --
float(1.570796327)

-- Iteration 13 --
float(1.527345431)

-- Iteration 14 --
float(1.570796327)

-- Iteration 15 --
float(1.527345431)

-- Iteration 16 --
float(1.570796327)

-- Iteration 17 --

Warning: atan2() expects parameter 2 to be float, string given in %s on line %d
NULL

-- Iteration 18 --

Warning: atan2() expects parameter 2 to be float, string given in %s on line %d
NULL

-- Iteration 19 --

Warning: atan2() expects parameter 2 to be float, array given in %s on line %d
NULL

-- Iteration 20 --

Warning: atan2() expects parameter 2 to be float, string given in %s on line %d
NULL

-- Iteration 21 --

Warning: atan2() expects parameter 2 to be float, string given in %s on line %d
NULL

-- Iteration 22 --

Warning: atan2() expects parameter 2 to be float, string given in %s on line %d
NULL

-- Iteration 23 --

Warning: atan2() expects parameter 2 to be float, object given in %s on line %d
NULL

-- Iteration 24 --
float(1.570796327)

-- Iteration 25 --
float(1.570796327)

-- Iteration 26 --

Warning: atan2() expects parameter 2 to be float, resource given in %s on line %d
NULL
===Done===