*** Testing base_convert() : usage variations ***

-- Iteration 1 --

Warning: base_convert(): Invalid `from base' (0) in %s on line %d
bool(false)

-- Iteration 2 --

Warning: base_convert(): Invalid `from base' (1) in %s on line %d
bool(false)

-- Iteration 3 --

Warning: base_convert(): Invalid `from base' (-1) in %s on line %d
bool(false)

-- Iteration 4 --

Warning: base_convert(): Invalid `from base' (-12) in %s on line %d
bool(false)

-- Iteration 5 --

Warning: base_convert(): Invalid `from base' (2147483647) in %s on line %d
bool(false)

-- Iteration 6 --
string(2) "31"

-- Iteration 7 --

Warning: base_convert(): Invalid `from base' (-10) in %s on line %d
bool(false)

-- Iteration 8 --

Warning: base_convert(): Invalid `from base' (123) in %s on line %d
bool(false)

-- Iteration 9 --

Warning: base_convert(): Invalid `from base' (0) in %s on line %d
bool(false)

-- Iteration 10 --

Warning: base_convert(): Invalid `from base' (0) in %s on line %d
bool(false)

-- Iteration 11 --

Warning: base_convert(): Invalid `from base' (0) in %s on line %d
bool(false)

-- Iteration 12 --

Warning: base_convert(): Invalid `from base' (0) in %s on line %d
bool(false)

-- Iteration 13 --

Warning: base_convert(): Invalid `from base' (1) in %s on line %d
bool(false)

-- Iteration 14 --

Warning: base_convert(): Invalid `from base' (0) in %s on line %d
bool(false)

-- Iteration 15 --

Warning: base_convert(): Invalid `from base' (1) in %s on line %d
bool(false)

-- Iteration 16 --

Warning: base_convert(): Invalid `from base' (0) in %s on line %d
bool(false)

-- Iteration 17 --

Warning: base_convert() expects parameter 2 to be integer, string given in %s on line %d
NULL

-- Iteration 18 --

Warning: base_convert() expects parameter 2 to be integer, string given in %s on line %d
NULL

-- Iteration 19 --

Warning: base_convert() expects parameter 2 to be integer, array given in %s on line %d
NULL

-- Iteration 20 --

Warning: base_convert() expects parameter 2 to be integer, string given in %s on line %d
NULL

-- Iteration 21 --

Warning: base_convert() expects parameter 2 to be integer, string given in %s on line %d
NULL

-- Iteration 22 --

Warning: base_convert() expects parameter 2 to be integer, string given in %s on line %d
NULL

-- Iteration 23 --

Warning: base_convert(): Invalid `from base' (0) in %s on line %d
bool(false)

-- Iteration 24 --

Warning: base_convert(): Invalid `from base' (0) in %s on line %d
bool(false)
===Done===