*** Testing exp() : usage variations ***

-- Iteration 1 --
float(1)

-- Iteration 2 --
float(2.718281828459)

-- Iteration 3 --
float(INF)

-- Iteration 4 --
float(0)

-- Iteration 5 --
float(INF)

-- Iteration 6 --
float(36315.502674247)

-- Iteration 7 --
float(2.7536449349747E-5)

-- Iteration 8 --
float(INF)

-- Iteration 9 --
float(1.0000000012346)

-- Iteration 10 --
float(1.6487212707001)

-- Iteration 11 --
float(1)

-- Iteration 12 --
float(1)

-- Iteration 13 --
float(2.718281828459)

-- Iteration 14 --
float(1)

-- Iteration 15 --
float(2.718281828459)

-- Iteration 16 --
float(1)

-- Iteration 17 --

Warning: exp() expects parameter 1 to be float, string given in %s on line %d
NULL

-- Iteration 18 --

Warning: exp() expects parameter 1 to be float, string given in %s on line %d
NULL

-- Iteration 19 --

Warning: exp() expects parameter 1 to be float, array given in %s on line %d
NULL

-- Iteration 20 --

Warning: exp() expects parameter 1 to be float, string given in %s on line %d
NULL

-- Iteration 21 --

Warning: exp() expects parameter 1 to be float, string given in %s on line %d
NULL

-- Iteration 22 --

Warning: exp() expects parameter 1 to be float, string given in %s on line %d
NULL

-- Iteration 23 --

Warning: exp() expects parameter 1 to be float, object given in %s on line %d
NULL

-- Iteration 24 --
float(1)

-- Iteration 25 --
float(1)

-- Iteration 26 --

Warning: exp() expects parameter 1 to be float, resource given in %s on line %d
NULL
===Done===