*** Testing expm1() : usage variations ***

-- Iteration 1 --
float(0)

-- Iteration 2 --
float(1.718281828459)

-- Iteration 3 --
float(INF)

-- Iteration 4 --
float(-1)

-- Iteration 5 --
float(36314.502674247)

-- Iteration 6 --
float(-0.99997246355065)

-- Iteration 7 --
float(INF)

-- Iteration 8 --
float(0.0012353302826471)

-- Iteration 9 --
float(0.64872127070013)

-- Iteration 10 --
float(0)

-- Iteration 11 --
float(0)

-- Iteration 12 --
float(1.718281828459)

-- Iteration 13 --
float(0)

-- Iteration 14 --
float(1.718281828459)

-- Iteration 15 --
float(0)

-- Iteration 16 --

Warning: expm1() expects parameter 1 to be float, string given in %s on line %d
NULL

-- Iteration 17 --

Warning: expm1() expects parameter 1 to be float, string given in %s on line %d
NULL

-- Iteration 18 --

Warning: expm1() expects parameter 1 to be float, array given in %s on line %d
NULL

-- Iteration 19 --

Warning: expm1() expects parameter 1 to be float, string given in %s on line %d
NULL

-- Iteration 20 --

Warning: expm1() expects parameter 1 to be float, string given in %s on line %d
NULL

-- Iteration 21 --

Warning: expm1() expects parameter 1 to be float, string given in %s on line %d
NULL

-- Iteration 22 --

Warning: expm1() expects parameter 1 to be float, array given in %s on line %d
NULL

-- Iteration 23 --

Warning: expm1() expects parameter 1 to be float, array given in %s on line %d
NULL

-- Iteration 24 --

Warning: expm1() expects parameter 1 to be float, object given in %s on line %d
NULL

-- Iteration 25 --
float(0)

-- Iteration 26 --
float(0)

-- Iteration 27 --

Warning: expm1() expects parameter 1 to be float, resource given in %s on line %d
NULL
===Done===