*** Testing hypot() : error conditions ***

-- Testing hypot() function with less than expected no. of arguments --

Warning: hypot() expects exactly 2 parameters, 0 given in %s on line %d

Warning: hypot() expects exactly 2 parameters, 1 given in %s on line %d

-- Testing hypot() function with more than expected no. of arguments --

Warning: hypot() expects exactly 2 parameters, 3 given in %s on line %d
===Done===