*** Testing is_nan() : usage variations ***

-- Iteration 1 --
bool(false)

-- Iteration 2 --
bool(false)

-- Iteration 3 --
bool(false)

-- Iteration 4 --
bool(false)

-- Iteration 5 --
bool(false)

-- Iteration 6 --
bool(false)

-- Iteration 7 --
bool(false)

-- Iteration 8 --
bool(false)

-- Iteration 9 --
bool(false)

-- Iteration 10 --
bool(false)

-- Iteration 11 --
bool(false)

-- Iteration 12 --
bool(false)

-- Iteration 13 --
bool(false)

-- Iteration 14 --
bool(false)

-- Iteration 15 --
bool(false)

-- Iteration 16 --
bool(false)

-- Iteration 17 --

Warning: is_nan() expects parameter 1 to be float, string given in %s on line %d
NULL

-- Iteration 18 --

Warning: is_nan() expects parameter 1 to be float, string given in %s on line %d
NULL

-- Iteration 19 --

Warning: is_nan() expects parameter 1 to be float, array given in %s on line %d
NULL

-- Iteration 20 --

Warning: is_nan() expects parameter 1 to be float, string given in %s on line %d
NULL

-- Iteration 21 --

Warning: is_nan() expects parameter 1 to be float, string given in %s on line %d
NULL

-- Iteration 22 --

Warning: is_nan() expects parameter 1 to be float, string given in %s on line %d
NULL

-- Iteration 23 --

Warning: is_nan() expects parameter 1 to be float, object given in %s on line %d
NULL

-- Iteration 24 --
bool(false)

-- Iteration 25 --
bool(false)

-- Iteration 26 --

Warning: is_nan() expects parameter 1 to be float, resource given in %s on line %d
NULL
===Done===