*** Testing mt_rand() : usage variations ***

-- Iteration 1 --
int(%i)

-- Iteration 2 --
int(%i)

-- Iteration 3 --
int(%i)

-- Iteration 4 --
int(%i)

-- Iteration 5 --
int(%i)

-- Iteration 6 --
int(%i)

-- Iteration 7 --
int(%i)

-- Iteration 8 --
int(%i)

-- Iteration 9 --
int(%i)

-- Iteration 10 --
int(%i)

-- Iteration 11 --
int(%i)

-- Iteration 12 --
int(%i)

-- Iteration 13 --
int(%i)

-- Iteration 14 --
int(%i)

-- Iteration 15 --
int(%i)

-- Iteration 16 --
int(%i)

-- Iteration 17 --

Warning: mt_rand() expects parameter 1 to be integer, string given in %s on line %d
NULL

-- Iteration 18 --

Warning: mt_rand() expects parameter 1 to be integer, string given in %s on line %d
NULL

-- Iteration 19 --

Warning: mt_rand() expects parameter 1 to be integer, array given in %s on line %d
NULL

-- Iteration 20 --

Warning: mt_rand() expects parameter 1 to be integer, string given in %s on line %d
NULL

-- Iteration 21 --

Warning: mt_rand() expects parameter 1 to be integer, string given in %s on line %d
NULL

-- Iteration 22 --

Warning: mt_rand() expects parameter 1 to be integer, string given in %s on line %d
NULL

-- Iteration 23 --

Warning: mt_rand() expects parameter 1 to be integer, object given in %s on line %d
NULL

-- Iteration 24 --
int(%i)

-- Iteration 25 --
int(%i)

-- Iteration 26 --

Warning: mt_rand() expects parameter 1 to be integer, resource given in %s on line %d
NULL
===Done===