Warning: preg_match(): Empty regular expression in %sdelimiters.php on line 3
bool(false)

Warning: preg_match(): Empty regular expression in %sdelimiters.php on line 4
bool(false)
int(1)

Warning: preg_match(): Delimiter must not be alphanumeric or backslash in %sdelimiters.php on line 6
bool(false)
int(1)

Warning: preg_match(): No ending delimiter '~' found in %sdelimiters.php on line 8
bool(false)
int(1)

Warning: preg_match(): Unknown modifier 'z' in %sdelimiters.php on line 10
bool(false)

Warning: preg_match(): No ending matching delimiter '}' found in %sdelimiters.php on line 11
bool(false)