*** Testing preg_grep() : error conditions ***

Arg value is abcdef

Warning: preg_grep(): Delimiter must not be alphanumeric or backslash in %spreg_grep_error1.php on line %d
bool(false)

Arg value is /[a-zA-Z]

Warning: preg_grep(): No ending delimiter '/' found in %spreg_grep_error1.php on line %d
bool(false)

Arg value is [a-zA-Z]/

Warning: preg_grep(): Unknown modifier '/' in %spreg_grep_error1.php on line %d
bool(false)

Arg value is /[a-zA-Z]/F

Warning: preg_grep(): Unknown modifier 'F' in %spreg_grep_error1.php on line %d
bool(false)

Arg value is Array

Warning: preg_grep() expects parameter 1 to be string, array given in %spreg_grep_error1.php on line %d
NULL

Arg value is /[a-zA-Z]/
array(2) {
  [1]=>
  string(3) "abc"
  [2]=>
  string(4) "test"
}

Warning: preg_grep() expects parameter 1 to be string, object given in %spreg_grep_error1.php on line %d
NULL
Done