Warning: preg_replace_callback_array() expects at least 2 parameters, 0 given in %s on line %d
NULL

Warning: preg_replace_callback_array() expects at least 2 parameters, 1 given in %s on line %d
NULL

Warning: preg_replace_callback_array() expects parameter 1 to be array, integer given in %s on line %d
NULL

Warning: preg_replace_callback_array() expects parameter 1 to be array, integer given in %s on line %d
NULL

Warning: preg_replace_callback_array() expects parameter 1 to be array, integer given in %s on line %d
NULL

Warning: preg_replace_callback_array() expects parameter 3 to be integer, string given in %s on line %d
NULL

Warning: preg_replace_callback() expects parameter 4 to be integer, array given in %s on line %d
NULL
string(0) ""

Warning: preg_replace_callback_array(): 's' is not a valid callback in %spreg_replace_callback_array2.php on line %d
array(0) {
}
string(0) ""

Warning: preg_replace_callback_array(): No ending delimiter '/' found in %spreg_replace_callback_array2.php on line %d
NULL
string(1) "1"
Done