***Testing preg_replace_callback() : error conditions***

-- Testing preg_replace_callback() function with Zero arguments --

Warning: preg_replace_callback() expects at least 3 parameters, 0 given in %s on line %d
NULL

-- Testing preg_replace_callback() function with more than expected no. of arguments --

Warning: preg_replace_callback() expects at most 5 parameters, 6 given in %s on line %d
NULL

-- Testing preg_replace_callback() function with less than expected no. of arguments --

Warning: preg_replace_callback() expects at least 3 parameters, 2 given in %s on line %d
NULL
Done