*** Testing preg_match() : error conditions ***

Arg value is abcdef

Warning: preg_match(): Delimiter must not be alphanumeric or backslash in %spreg_match_error1.php on line %d
bool(false)

Arg value is /[a-zA-Z]

Warning: preg_match(): No ending delimiter '/' found in %spreg_match_error1.php on line %d
bool(false)

Arg value is [a-zA-Z]/

Warning: preg_match(): Unknown modifier '/' in %spreg_match_error1.php on line %d
bool(false)

Arg value is /[a-zA-Z]/F

Warning: preg_match(): Unknown modifier 'F' in %spreg_match_error1.php on line %d
bool(false)

Arg value is Array

Warning: preg_match() expects parameter 1 to be string, array given in %spreg_match_error1.php on line %d
bool(false)

Arg value is /[a-zA-Z]/
int(1)

Warning: preg_match() expects parameter 1 to be string, object given in %spreg_match_error1.php on line %d
bool(false)