*** Testing preg_replace() : error conditions ***

Arg value is: this is a string
string(64) "this is a stringthis is a stringthis is a stringthis is a string"

Arg value is: Array

Warning: preg_replace(): Parameter mismatch, pattern is a string while replacement is an array in %spreg_replace_error2.php on line %d
bool(false)

Recoverable fatal error: Object of class stdClass could not be converted to string in %spreg_replace_error2.php on line %d