*** Testing getimagesize() : variation ***

-- File with text data (test.txt) --
bool(false)
bool(false)
array(0) {
}

-- File with corrupted BMP data (200x100_unknown.unknown) --
bool(false)
bool(false)
array(0) {
}

-- Non-existent file (nofile.ext) --

Warning: getimagesize(%snofile.ext): failed to open stream: No such file or directory in %s on line %d
bool(false)

Warning: getimagesize(%snofile.ext): failed to open stream: No such file or directory in %s on line %d
bool(false)
array(0) {
}

-- Empty File (blank_file.bmp) --

Notice: getimagesize(): Read error! in %s on line %d
bool(false)

Notice: getimagesize(): Read error! in %s on line %d
bool(false)
array(0) {
}
===DONE===