Warning: bzread() expects at least 1 parameter, 0 given in %s on line %d
bool(false)

Warning: bzread() expects at most 2 parameters, 3 given in %s on line %d
bool(false)
string(0) ""

Warning: bzread(): length may not be negative in %s on line %d
bool(false)
string(1) "R"
string(2) "is"
string(251) "ing up from the heart of the desert
Rising up for Jerusalem
Rising up from the heat of the desert
Building up Old Jerusalem
Rising up from the heart of the desert
Rising up for Jerusalem
Rising up from the heat of the desert
Heading out for Jerusalem
"
Done