Warning: Only arrays and Traversables can be unpacked in %s on line %d
array(0) {
}

Warning: Only arrays and Traversables can be unpacked in %s on line %d
array(0) {
}

Warning: Only arrays and Traversables can be unpacked in %s on line %d
array(0) {
}

Warning: Only arrays and Traversables can be unpacked in %s on line %d
array(5) {
  [0]=>
  int(1)
  [1]=>
  int(2)
  [2]=>
  int(3)
  [3]=>
  int(4)
  [4]=>
  int(5)
}

Warning: Only arrays and Traversables can be unpacked in %s on line %d

Warning: Only arrays and Traversables can be unpacked in %s on line %d
array(5) {
  [0]=>
  int(1)
  [1]=>
  int(2)
  [2]=>
  int(3)
  [3]=>
  int(4)
  [4]=>
  int(5)
}