Warning: bindtextdomain(): domain passed too long in %s on line %d
bool(false)

Warning: dngettext(): domain passed too long in %s on line %d
bool(false)

Warning: dngettext(): msgid1 passed too long in %s on line %d
bool(false)

Warning: dngettext(): msgid2 passed too long in %s on line %d
bool(false)

Warning: gettext(): msgid passed too long in %s on line %d
bool(false)

Warning: ngettext(): msgid1 passed too long in %s on line %d
bool(false)

Warning: ngettext(): msgid2 passed too long in %s on line %d
bool(false)

Warning: dcgettext(): domain passed too long in %s on line %d
bool(false)

Warning: dcgettext(): msgid passed too long in %s on line %d
bool(false)

Warning: dcngettext(): domain passed too long in %s on line %d
bool(false)

Warning: dcngettext(): msgid1 passed too long in %s on line %d
bool(false)

Warning: dcngettext(): msgid2 passed too long in %s on line %d
bool(false)

Warning: dgettext(): domain passed too long in %s on line %d
bool(false)

Warning: dgettext(): msgid passed too long in %s on line %d
bool(false)

Warning: textdomain(): domain passed too long in %s on line %d
bool(false)
==DONE==