object(DateTime)#1 (3) {
  ["date"]=>
  string(26) "2006-01-23 00:00:00.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(3) "UTC"
}
string(19) "2006/01/23 00:00:00"

Warning: date_isodate_set() expects at least 3 parameters, 2 given in %s on line %d
bool(false)
string(19) "2006/01/23 00:00:00"
object(DateTime)#1 (3) {
  ["date"]=>
  string(26) "2006-01-30 00:00:00.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(3) "UTC"
}
string(19) "2006/01/30 00:00:00"
object(DateTime)#1 (3) {
  ["date"]=>
  string(26) "2007-12-10 00:00:00.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(3) "UTC"
}
string(19) "2007/12/10 00:00:00"

Warning: date_isodate_set() expects at most 4 parameters, 5 given in %s on line %d
bool(false)
string(19) "2007/12/10 00:00:00"
Done