*** Testing date_offset_get() : error conditions ***

-- Testing date_offset_get() function with zero arguments --

Warning: date_offset_get() expects exactly 1 parameter, 0 given in %s on line %d
bool(false)

-- Testing date_offset_get() function with more than expected no. of arguments --

Warning: date_offset_get() expects exactly 1 parameter, 2 given in %s on line %d
bool(false)

-- Testing date_offset_get() function with an invalid values for $object argument --

Warning: date_offset_get() expects parameter 1 to be DateTimeInterface, object given in %s on line %d
bool(false)

Warning: date_offset_get() expects parameter 1 to be DateTimeInterface, integer given in %s on line %d
bool(false)

Warning: date_offset_get() expects parameter 1 to be DateTimeInterface, null given in %s on line %d
bool(false)
===DONE===