*** Testing date_time_set() : error conditions ***

-- Testing date_time_set() function with zero arguments --

Warning: date_time_set() expects at least 3 parameters, 0 given in %s on line %d
bool(false)

-- Testing date_time_set() function with less than expected no. of arguments --

Warning: date_time_set() expects at least 3 parameters, 1 given in %s on line %d
bool(false)

Warning: date_time_set() expects at least 3 parameters, 2 given in %s on line %d
bool(false)

-- Testing date_time_set() function with more than expected no. of arguments --

Warning: date_time_set() expects at most 5 parameters, 6 given in %s on line %d
bool(false)

-- Testing date_time_set() function with an invalid values for $object argument --

Warning: date_time_set() expects parameter 1 to be DateTime, object given in %s on line %d
bool(false)

Warning: date_time_set() expects parameter 1 to be DateTime, integer given in %s on line %d
bool(false)

Warning: date_time_set() expects parameter 1 to be DateTime, null given in %s on line %d
bool(false)
===DONE===