*** Testing date_timezone_set() : usage variation -  unexpected values to second argument $timezone***

-- int 0 --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, integer given in %s on line %d
bool(false)

-- int 1 --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, integer given in %s on line %d
bool(false)

-- int 12345 --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, integer given in %s on line %d
bool(false)

-- int -12345 --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, integer given in %s on line %d
bool(false)

-- float 10.5 --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, float given in %s on line %d
bool(false)

-- float -10.5 --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, float given in %s on line %d
bool(false)

-- float .5 --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, float given in %s on line %d
bool(false)

-- empty array --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, array given in %s on line %d
bool(false)

-- int indexed array --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, array given in %s on line %d
bool(false)

-- associative array --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, array given in %s on line %d
bool(false)

-- nested arrays --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, array given in %s on line %d
bool(false)

-- uppercase NULL --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, null given in %s on line %d
bool(false)

-- lowercase null --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, null given in %s on line %d
bool(false)

-- lowercase true --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, boolean given in %s on line %d
bool(false)

-- lowercase false --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, boolean given in %s on line %d
bool(false)

-- uppercase TRUE --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, boolean given in %s on line %d
bool(false)

-- uppercase FALSE --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, boolean given in %s on line %d
bool(false)

-- empty string DQ --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, string given in %s on line %d
bool(false)

-- empty string SQ --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, string given in %s on line %d
bool(false)

-- string DQ --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, string given in %s on line %d
bool(false)

-- string SQ --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, string given in %s on line %d
bool(false)

-- mixed case string --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, string given in %s on line %d
bool(false)

-- heredoc --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, string given in %s on line %d
bool(false)

-- instance of classWithToString --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, object given in %s on line %d
bool(false)

-- instance of classWithoutToString --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, object given in %s on line %d
bool(false)

-- undefined var --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, null given in %s on line %d
bool(false)

-- unset var --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, null given in %s on line %d
bool(false)

-- resource --

Warning: date_timezone_set() expects parameter 2 to be DateTimeZone, resource given in %s on line %d
bool(false)
===DONE===