*** Testing date_sunset() : usage variation ***

--int 0--
string(5) "17:43"
float(17.730%d)
int(1218197630)

--int 1--
string(5) "17:44"
float(17.749%d)
int(1218197698)

--int 12345--
bool(false)
bool(false)
bool(false)

--int -12345--
string(5) "17:35"
float(17.598%d)
int(1218197155)

--empty array--

Warning: date_sunset() expects parameter 3 to be float, array given in %s on line %d
bool(false)

Warning: date_sunset() expects parameter 3 to be float, array given in %s on line %d
bool(false)

Warning: date_sunset() expects parameter 3 to be float, array given in %s on line %d
bool(false)

--int indexed array--

Warning: date_sunset() expects parameter 3 to be float, array given in %s on line %d
bool(false)

Warning: date_sunset() expects parameter 3 to be float, array given in %s on line %d
bool(false)

Warning: date_sunset() expects parameter 3 to be float, array given in %s on line %d
bool(false)

--associative array--

Warning: date_sunset() expects parameter 3 to be float, array given in %s on line %d
bool(false)

Warning: date_sunset() expects parameter 3 to be float, array given in %s on line %d
bool(false)

Warning: date_sunset() expects parameter 3 to be float, array given in %s on line %d
bool(false)

--nested arrays--

Warning: date_sunset() expects parameter 3 to be float, array given in %s on line %d
bool(false)

Warning: date_sunset() expects parameter 3 to be float, array given in %s on line %d
bool(false)

Warning: date_sunset() expects parameter 3 to be float, array given in %s on line %d
bool(false)

--uppercase NULL--
string(5) "17:43"
float(17.730%d)
int(1218197630)

--lowercase null--
string(5) "17:43"
float(17.730%d)
int(1218197630)

--lowercase true--
string(5) "17:44"
float(17.749%d)
int(1218197698)

--lowercase false--
string(5) "17:43"
float(17.730%d)
int(1218197630)

--uppercase TRUE--
string(5) "17:44"
float(17.749%d)
int(1218197698)

--uppercase FALSE--
string(5) "17:43"
float(17.730%d)
int(1218197630)

--empty string DQ--

Warning: date_sunset() expects parameter 3 to be float, string given in %s on line %d
bool(false)

Warning: date_sunset() expects parameter 3 to be float, string given in %s on line %d
bool(false)

Warning: date_sunset() expects parameter 3 to be float, string given in %s on line %d
bool(false)

--empty string SQ--

Warning: date_sunset() expects parameter 3 to be float, string given in %s on line %d
bool(false)

Warning: date_sunset() expects parameter 3 to be float, string given in %s on line %d
bool(false)

Warning: date_sunset() expects parameter 3 to be float, string given in %s on line %d
bool(false)

--string DQ--

Warning: date_sunset() expects parameter 3 to be float, string given in %s on line %d
bool(false)

Warning: date_sunset() expects parameter 3 to be float, string given in %s on line %d
bool(false)

Warning: date_sunset() expects parameter 3 to be float, string given in %s on line %d
bool(false)

--string SQ--

Warning: date_sunset() expects parameter 3 to be float, string given in %s on line %d
bool(false)

Warning: date_sunset() expects parameter 3 to be float, string given in %s on line %d
bool(false)

Warning: date_sunset() expects parameter 3 to be float, string given in %s on line %d
bool(false)

--mixed case string--

Warning: date_sunset() expects parameter 3 to be float, string given in %s on line %d
bool(false)

Warning: date_sunset() expects parameter 3 to be float, string given in %s on line %d
bool(false)

Warning: date_sunset() expects parameter 3 to be float, string given in %s on line %d
bool(false)

--heredoc--

Warning: date_sunset() expects parameter 3 to be float, string given in %s on line %d
bool(false)

Warning: date_sunset() expects parameter 3 to be float, string given in %s on line %d
bool(false)

Warning: date_sunset() expects parameter 3 to be float, string given in %s on line %d
bool(false)

--instance of classWithToString--

Warning: date_sunset() expects parameter 3 to be float, object given in %s on line %d
bool(false)

Warning: date_sunset() expects parameter 3 to be float, object given in %s on line %d
bool(false)

Warning: date_sunset() expects parameter 3 to be float, object given in %s on line %d
bool(false)

--instance of classWithoutToString--

Warning: date_sunset() expects parameter 3 to be float, object given in %s on line %d
bool(false)

Warning: date_sunset() expects parameter 3 to be float, object given in %s on line %d
bool(false)

Warning: date_sunset() expects parameter 3 to be float, object given in %s on line %d
bool(false)

--undefined var--
string(5) "17:43"
float(17.730%d)
int(1218197630)

--unset var--
string(5) "17:43"
float(17.730%d)
int(1218197630)
===DONE===