*** Testing date_date_set() : usage variation -  unexpected values to second argument $year***

-- int 0 --
object(DateTime)#%d (3) {
  ["date"]=>
  string(%d) "%s"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- int 1 --
object(DateTime)#%d (3) {
  ["date"]=>
  string(26) "0001-07-02 08:34:10.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- int 12345 --
object(DateTime)#%d (3) {
  ["date"]=>
  string(27) "12345-07-02 08:34:10.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- int -12345 --
object(DateTime)#%d (3) {
  ["date"]=>
  string(28) "-12345-07-02 08:34:10.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- float 10.5 --
object(DateTime)#%d (3) {
  ["date"]=>
  string(26) "0010-07-02 08:34:10.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- float -10.5 --
object(DateTime)#%d (3) {
  ["date"]=>
  string(27) "-0010-07-02 08:34:10.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- float .5 --
object(DateTime)#%d (3) {
  ["date"]=>
  string(%d) "%s"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- empty array --

Warning: date_date_set() expects parameter 2 to be integer, array given in %s on line %d
bool(false)

-- int indexed array --

Warning: date_date_set() expects parameter 2 to be integer, array given in %s on line %d
bool(false)

-- associative array --

Warning: date_date_set() expects parameter 2 to be integer, array given in %s on line %d
bool(false)

-- nested arrays --

Warning: date_date_set() expects parameter 2 to be integer, array given in %s on line %d
bool(false)

-- uppercase NULL --
object(DateTime)#%d (3) {
  ["date"]=>
  string(%d) "%s"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- lowercase null --
object(DateTime)#%d (3) {
  ["date"]=>
  string(%d) "%s"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- lowercase true --
object(DateTime)#%d (3) {
  ["date"]=>
  string(26) "0001-07-02 08:34:10.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- lowercase false --
object(DateTime)#%d (3) {
  ["date"]=>
  string(%d) "%s"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- uppercase TRUE --
object(DateTime)#%d (3) {
  ["date"]=>
  string(26) "0001-07-02 08:34:10.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- uppercase FALSE --
object(DateTime)#%d (3) {
  ["date"]=>
  string(%d) "%s"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- empty string DQ --

Warning: date_date_set() expects parameter 2 to be integer, string given in %s on line %d
bool(false)

-- empty string SQ --

Warning: date_date_set() expects parameter 2 to be integer, string given in %s on line %d
bool(false)

-- string DQ --

Warning: date_date_set() expects parameter 2 to be integer, string given in %s on line %d
bool(false)

-- string SQ --

Warning: date_date_set() expects parameter 2 to be integer, string given in %s on line %d
bool(false)

-- mixed case string --

Warning: date_date_set() expects parameter 2 to be integer, string given in %s on line %d
bool(false)

-- heredoc --

Warning: date_date_set() expects parameter 2 to be integer, string given in %s on line %d
bool(false)

-- instance of classWithToString --

Warning: date_date_set() expects parameter 2 to be integer, object given in %s on line %d
bool(false)

-- instance of classWithoutToString --

Warning: date_date_set() expects parameter 2 to be integer, object given in %s on line %d
bool(false)

-- undefined var --
object(DateTime)#%d (3) {
  ["date"]=>
  string(%d) "%s"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- unset var --
object(DateTime)#%d (3) {
  ["date"]=>
  string(%d) "%s"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- resource --

Warning: date_date_set() expects parameter 2 to be integer, resource given in %s on line %d
bool(false)
===DONE===