*** Testing DateTime::format() : error conditions ***

-- Testing date_date_formatcreate() function with zero arguments --

Warning: DateTime::format() expects exactly 1 parameter, 0 given in %s on line %d
bool(false)

-- Testing date_date_formatcreate() function with more than expected no. of arguments --

Warning: DateTime::format() expects exactly 1 parameter, 2 given in %s on line %d
bool(false)
===DONE===