sunrise: 21:00:00
sunset: 21:00:00
transit: 10:04:02
civil_twilight_begin: 21:00:00
civil_twilight_end: 21:00:00
nautical_twilight_begin: 21:00:00
nautical_twilight_end: 21:00:00
astronomical_twilight_begin: 21:00:00
astronomical_twilight_end: 21:00:00

sunrise: 21:00:01
sunset: 21:00:01
transit: 08:52:30
civil_twilight_begin: 21:00:01
civil_twilight_end: 21:00:01
nautical_twilight_begin: 21:00:01
nautical_twilight_end: 21:00:01
astronomical_twilight_begin: 21:00:01
astronomical_twilight_end: 21:00:01
Done