*** Testing date_sunrise() : usage variation ***

--int 0--
string(5) "05:12"
float(5.200%d)
int(1218172321)

--int 1--
string(5) "05:08"
float(5.133%d)
int(1218172081)

--int 12345--
string(5) "21:45"
float(21.759%d)
int(1218145534)

--int -12345--
string(5) "12:41"
float(12.698%d)
int(1218199315)

--empty array--

Warning: date_sunrise() expects parameter 4 to be float, array given in %s on line %d
bool(false)

Warning: date_sunrise() expects parameter 4 to be float, array given in %s on line %d
bool(false)

Warning: date_sunrise() expects parameter 4 to be float, array given in %s on line %d
bool(false)

--int indexed array--

Warning: date_sunrise() expects parameter 4 to be float, array given in %s on line %d
bool(false)

Warning: date_sunrise() expects parameter 4 to be float, array given in %s on line %d
bool(false)

Warning: date_sunrise() expects parameter 4 to be float, array given in %s on line %d
bool(false)

--associative array--

Warning: date_sunrise() expects parameter 4 to be float, array given in %s on line %d
bool(false)

Warning: date_sunrise() expects parameter 4 to be float, array given in %s on line %d
bool(false)

Warning: date_sunrise() expects parameter 4 to be float, array given in %s on line %d
bool(false)

--nested arrays--

Warning: date_sunrise() expects parameter 4 to be float, array given in %s on line %d
bool(false)

Warning: date_sunrise() expects parameter 4 to be float, array given in %s on line %d
bool(false)

Warning: date_sunrise() expects parameter 4 to be float, array given in %s on line %d
bool(false)

--uppercase NULL--
string(5) "05:12"
float(5.200%d)
int(1218172321)

--lowercase null--
string(5) "05:12"
float(5.200%d)
int(1218172321)

--lowercase true--
string(5) "05:08"
float(5.133%d)
int(1218172081)

--lowercase false--
string(5) "05:12"
float(5.200%d)
int(1218172321)

--uppercase TRUE--
string(5) "05:08"
float(5.133%d)
int(1218172081)

--uppercase FALSE--
string(5) "05:12"
float(5.200%d)
int(1218172321)

--empty string DQ--

Warning: date_sunrise() expects parameter 4 to be float, string given in %s on line %d
bool(false)

Warning: date_sunrise() expects parameter 4 to be float, string given in %s on line %d
bool(false)

Warning: date_sunrise() expects parameter 4 to be float, string given in %s on line %d
bool(false)

--empty string SQ--

Warning: date_sunrise() expects parameter 4 to be float, string given in %s on line %d
bool(false)

Warning: date_sunrise() expects parameter 4 to be float, string given in %s on line %d
bool(false)

Warning: date_sunrise() expects parameter 4 to be float, string given in %s on line %d
bool(false)

--string DQ--

Warning: date_sunrise() expects parameter 4 to be float, string given in %s on line %d
bool(false)

Warning: date_sunrise() expects parameter 4 to be float, string given in %s on line %d
bool(false)

Warning: date_sunrise() expects parameter 4 to be float, string given in %s on line %d
bool(false)

--string SQ--

Warning: date_sunrise() expects parameter 4 to be float, string given in %s on line %d
bool(false)

Warning: date_sunrise() expects parameter 4 to be float, string given in %s on line %d
bool(false)

Warning: date_sunrise() expects parameter 4 to be float, string given in %s on line %d
bool(false)

--mixed case string--

Warning: date_sunrise() expects parameter 4 to be float, string given in %s on line %d
bool(false)

Warning: date_sunrise() expects parameter 4 to be float, string given in %s on line %d
bool(false)

Warning: date_sunrise() expects parameter 4 to be float, string given in %s on line %d
bool(false)

--heredoc--

Warning: date_sunrise() expects parameter 4 to be float, string given in %s on line %d
bool(false)

Warning: date_sunrise() expects parameter 4 to be float, string given in %s on line %d
bool(false)

Warning: date_sunrise() expects parameter 4 to be float, string given in %s on line %d
bool(false)

--instance of classWithToString--

Warning: date_sunrise() expects parameter 4 to be float, object given in %s on line %d
bool(false)

Warning: date_sunrise() expects parameter 4 to be float, object given in %s on line %d
bool(false)

Warning: date_sunrise() expects parameter 4 to be float, object given in %s on line %d
bool(false)

--instance of classWithoutToString--

Warning: date_sunrise() expects parameter 4 to be float, object given in %s on line %d
bool(false)

Warning: date_sunrise() expects parameter 4 to be float, object given in %s on line %d
bool(false)

Warning: date_sunrise() expects parameter 4 to be float, object given in %s on line %d
bool(false)

--undefined var--
string(5) "05:12"
float(5.200%d)
int(1218172321)

--unset var--
string(5) "05:12"
float(5.200%d)
int(1218172321)
===DONE===