*** Testing DateTime::setTimezone () : error conditions ***

-- Testing DateTime::setTimezone () function with zero arguments --

Warning: DateTime::setTimezone() expects exactly 1 parameter, 0 given in %s on line %d
bool(false)

-- Testing DateTime::setTimezone () function with more than expected no. of arguments --

Warning: DateTime::setTimezone() expects exactly 1 parameter, 2 given in %s on line %d
bool(false)
===DONE===