*** Testing date_isodate_set() : usage variation -  unexpected values to third argument $week***

-- int 0 --
object(DateTime)#%d (3) {
  ["date"]=>
  string(26) "1962-12-25 08:34:10.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- int 1 --
object(DateTime)#%d (3) {
  ["date"]=>
  string(26) "1963-01-01 08:34:10.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- int 12345 --
object(DateTime)#%d (3) {
  ["date"]=>
  string(26) "2199-07-30 08:34:10.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- int -12345 --
object(DateTime)#%d (3) {
  ["date"]=>
  string(26) "1726-05-21 08:34:10.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- float 10.5 --
object(DateTime)#%d (3) {
  ["date"]=>
  string(26) "1963-03-05 08:34:10.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- float -10.5 --
object(DateTime)#%d (3) {
  ["date"]=>
  string(26) "1962-10-16 08:34:10.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- float .5 --
object(DateTime)#%d (3) {
  ["date"]=>
  string(26) "1962-12-25 08:34:10.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- empty array --

Warning: date_isodate_set() expects parameter 3 to be integer, array given in %s on line %d
bool(false)

-- int indexed array --

Warning: date_isodate_set() expects parameter 3 to be integer, array given in %s on line %d
bool(false)

-- associative array --

Warning: date_isodate_set() expects parameter 3 to be integer, array given in %s on line %d
bool(false)

-- nested arrays --

Warning: date_isodate_set() expects parameter 3 to be integer, array given in %s on line %d
bool(false)

-- uppercase NULL --
object(DateTime)#%d (3) {
  ["date"]=>
  string(26) "1962-12-25 08:34:10.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- lowercase null --
object(DateTime)#%d (3) {
  ["date"]=>
  string(26) "1962-12-25 08:34:10.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- lowercase true --
object(DateTime)#%d (3) {
  ["date"]=>
  string(26) "1963-01-01 08:34:10.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- lowercase false --
object(DateTime)#%d (3) {
  ["date"]=>
  string(26) "1962-12-25 08:34:10.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- uppercase TRUE --
object(DateTime)#%d (3) {
  ["date"]=>
  string(26) "1963-01-01 08:34:10.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- uppercase FALSE --
object(DateTime)#%d (3) {
  ["date"]=>
  string(26) "1962-12-25 08:34:10.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- empty string DQ --

Warning: date_isodate_set() expects parameter 3 to be integer, string given in %s on line %d
bool(false)

-- empty string SQ --

Warning: date_isodate_set() expects parameter 3 to be integer, string given in %s on line %d
bool(false)

-- string DQ --

Warning: date_isodate_set() expects parameter 3 to be integer, string given in %s on line %d
bool(false)

-- string SQ --

Warning: date_isodate_set() expects parameter 3 to be integer, string given in %s on line %d
bool(false)

-- mixed case string --

Warning: date_isodate_set() expects parameter 3 to be integer, string given in %s on line %d
bool(false)

-- heredoc --

Warning: date_isodate_set() expects parameter 3 to be integer, string given in %s on line %d
bool(false)

-- instance of classWithToString --

Warning: date_isodate_set() expects parameter 3 to be integer, object given in %s on line %d
bool(false)

-- instance of classWithoutToString --

Warning: date_isodate_set() expects parameter 3 to be integer, object given in %s on line %d
bool(false)

-- undefined var --
object(DateTime)#%d (3) {
  ["date"]=>
  string(26) "1962-12-25 08:34:10.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- unset var --
object(DateTime)#%d (3) {
  ["date"]=>
  string(26) "1962-12-25 08:34:10.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(13) "Europe/London"
}

-- resource --

Warning: date_isodate_set() expects parameter 3 to be integer, resource given in %s on line %d
bool(false)
===DONE===