*** Testing date_default_timezone_set() : error variations ***

-- Testing date_default_timezone_set() function with less than expected no. of arguments --

Warning: date_default_timezone_set() expects exactly 1 parameter, 0 given in %s on line %d
bool(false)

-- Testing date_default_timezone_set() function with more than expected no. of arguments --

Warning: date_default_timezone_set() expects exactly 1 parameter, 2 given in %s on line %d
bool(false)

-- Testing date_default_timezone_set() function with invalid timezone identifier  --

Notice: date_default_timezone_set(): Timezone ID 'foo' is invalid in %s on line %d
bool(false)
===Done===