*** Testing gmmktime() : usage variation ***

--float 10.5--
int(1223453288)

--float -10.5--
int(1170922088)

--float .5--
int(1197101288)

--empty array--

Warning: gmmktime() expects parameter 4 to be integer, array given in %s on line %d
bool(false)

--int indexed array--

Warning: gmmktime() expects parameter 4 to be integer, array given in %s on line %d
bool(false)

--associative array--

Warning: gmmktime() expects parameter 4 to be integer, array given in %s on line %d
bool(false)

--nested arrays--

Warning: gmmktime() expects parameter 4 to be integer, array given in %s on line %d
bool(false)

--uppercase NULL--
int(1197101288)

--lowercase null--
int(1197101288)

--lowercase true--
int(1199779688)

--lowercase false--
int(1197101288)

--uppercase TRUE--
int(1199779688)

--uppercase FALSE--
int(1197101288)

--empty string DQ--

Warning: gmmktime() expects parameter 4 to be integer, string given in %s on line %d
bool(false)

--empty string SQ--

Warning: gmmktime() expects parameter 4 to be integer, string given in %s on line %d
bool(false)

--string DQ--

Warning: gmmktime() expects parameter 4 to be integer, string given in %s on line %d
bool(false)

--string SQ--

Warning: gmmktime() expects parameter 4 to be integer, string given in %s on line %d
bool(false)

--mixed case string--

Warning: gmmktime() expects parameter 4 to be integer, string given in %s on line %d
bool(false)

--heredoc--

Warning: gmmktime() expects parameter 4 to be integer, string given in %s on line %d
bool(false)

--instance of classWithToString--

Warning: gmmktime() expects parameter 4 to be integer, object given in %s on line %d
bool(false)

--instance of classWithoutToString--

Warning: gmmktime() expects parameter 4 to be integer, object given in %s on line %d
bool(false)

--undefined var--
int(1197101288)

--unset var--
int(1197101288)
===DONE===