*** Testing gmmktime() : usage variation ***

--float 10.5--
int(1218182890)

--float -10.5--
int(1218182870)

--float .5--
int(1218182880)

--empty array--

Warning: gmmktime() expects parameter 3 to be integer, array given in %s on line %d
bool(false)

--int indexed array--

Warning: gmmktime() expects parameter 3 to be integer, array given in %s on line %d
bool(false)

--associative array--

Warning: gmmktime() expects parameter 3 to be integer, array given in %s on line %d
bool(false)

--nested arrays--

Warning: gmmktime() expects parameter 3 to be integer, array given in %s on line %d
bool(false)

--uppercase NULL--
int(1218182880)

--lowercase null--
int(1218182880)

--lowercase true--
int(1218182881)

--lowercase false--
int(1218182880)

--uppercase TRUE--
int(1218182881)

--uppercase FALSE--
int(1218182880)

--empty string DQ--

Warning: gmmktime() expects parameter 3 to be integer, string given in %s on line %d
bool(false)

--empty string SQ--

Warning: gmmktime() expects parameter 3 to be integer, string given in %s on line %d
bool(false)

--string DQ--

Warning: gmmktime() expects parameter 3 to be integer, string given in %s on line %d
bool(false)

--string SQ--

Warning: gmmktime() expects parameter 3 to be integer, string given in %s on line %d
bool(false)

--mixed case string--

Warning: gmmktime() expects parameter 3 to be integer, string given in %s on line %d
bool(false)

--heredoc--

Warning: gmmktime() expects parameter 3 to be integer, string given in %s on line %d
bool(false)

--instance of classWithToString--

Warning: gmmktime() expects parameter 3 to be integer, object given in %s on line %d
bool(false)

--instance of classWithoutToString--

Warning: gmmktime() expects parameter 3 to be integer, object given in %s on line %d
bool(false)

--undefined var--
int(1218182880)

--unset var--
int(1218182880)
===DONE===