*** Testing idate() : usage variation ***

--int 0--

Warning: idate(): Unrecognized date format token. in %s on line %d
bool(false)

Warning: idate(): Unrecognized date format token. in %s on line %d
bool(false)

--int 1--

Warning: idate(): Unrecognized date format token. in %s on line %d
bool(false)

Warning: idate(): Unrecognized date format token. in %s on line %d
bool(false)

--int 12345--

Warning: idate(): idate format is one char in %s on line %d
bool(false)

Warning: idate(): idate format is one char in %s on line %d
bool(false)

--int -12345--

Warning: idate(): idate format is one char in %s on line %d
bool(false)

Warning: idate(): idate format is one char in %s on line %d
bool(false)

--float 10.5--

Warning: idate(): idate format is one char in %s on line %d
bool(false)

Warning: idate(): idate format is one char in %s on line %d
bool(false)

--float -10.5--

Warning: idate(): idate format is one char in %s on line %d
bool(false)

Warning: idate(): idate format is one char in %s on line %d
bool(false)

--float 12.3456789000e10--

Warning: idate(): idate format is one char in %s on line %d
bool(false)

Warning: idate(): idate format is one char in %s on line %d
bool(false)

--float -12.3456789000e10--

Warning: idate(): idate format is one char in %s on line %d
bool(false)

Warning: idate(): idate format is one char in %s on line %d
bool(false)

--float .5--

Warning: idate(): idate format is one char in %s on line %d
bool(false)

Warning: idate(): idate format is one char in %s on line %d
bool(false)

--empty array--

Warning: idate() expects parameter 1 to be string, array given in %s on line %d
bool(false)

Warning: idate() expects parameter 1 to be string, array given in %s on line %d
bool(false)

--int indexed array--

Warning: idate() expects parameter 1 to be string, array given in %s on line %d
bool(false)

Warning: idate() expects parameter 1 to be string, array given in %s on line %d
bool(false)

--associative array--

Warning: idate() expects parameter 1 to be string, array given in %s on line %d
bool(false)

Warning: idate() expects parameter 1 to be string, array given in %s on line %d
bool(false)

--nested arrays--

Warning: idate() expects parameter 1 to be string, array given in %s on line %d
bool(false)

Warning: idate() expects parameter 1 to be string, array given in %s on line %d
bool(false)

--uppercase NULL--

Warning: idate(): idate format is one char in %s on line %d
bool(false)

Warning: idate(): idate format is one char in %s on line %d
bool(false)

--lowercase null--

Warning: idate(): idate format is one char in %s on line %d
bool(false)

Warning: idate(): idate format is one char in %s on line %d
bool(false)

--lowercase true--

Warning: idate(): Unrecognized date format token. in %s on line %d
bool(false)

Warning: idate(): Unrecognized date format token. in %s on line %d
bool(false)

--lowercase false--

Warning: idate(): idate format is one char in %s on line %d
bool(false)

Warning: idate(): idate format is one char in %s on line %d
bool(false)

--uppercase TRUE--

Warning: idate(): Unrecognized date format token. in %s on line %d
bool(false)

Warning: idate(): Unrecognized date format token. in %s on line %d
bool(false)

--uppercase FALSE--

Warning: idate(): idate format is one char in %s on line %d
bool(false)

Warning: idate(): idate format is one char in %s on line %d
bool(false)

--empty string DQ--

Warning: idate(): idate format is one char in %s on line %d
bool(false)

Warning: idate(): idate format is one char in %s on line %d
bool(false)

--empty string SQ--

Warning: idate(): idate format is one char in %s on line %d
bool(false)

Warning: idate(): idate format is one char in %s on line %d
bool(false)

--instance of classWithToString--

Warning: idate(): idate format is one char in %s on line %d
bool(false)

Warning: idate(): idate format is one char in %s on line %d
bool(false)

--instance of classWithoutToString--

Warning: idate() expects parameter 1 to be string, object given in %s on line %d
bool(false)

Warning: idate() expects parameter 1 to be string, object given in %s on line %d
bool(false)

--undefined var--

Warning: idate(): idate format is one char in %s on line %d
bool(false)

Warning: idate(): idate format is one char in %s on line %d
bool(false)

--unset var--

Warning: idate(): idate format is one char in %s on line %d
bool(false)

Warning: idate(): idate format is one char in %s on line %d
bool(false)
===DONE===