*** Testing timezone_name_from_abbr() : usage variation -  unexpected values to second argument $gmtOffset***

-- int 0 --
string(3) "UTC"

-- int 12345 --
string(3) "UTC"

-- int -12345 --
string(3) "UTC"

-- float 10.5 --
string(3) "UTC"

-- float -10.5 --
string(3) "UTC"

-- float .5 --
string(3) "UTC"

-- empty array --

Warning: timezone_name_from_abbr() expects parameter 2 to be integer, array given in %s on line %d
bool(false)

-- int indexed array --

Warning: timezone_name_from_abbr() expects parameter 2 to be integer, array given in %s on line %d
bool(false)

-- associative array --

Warning: timezone_name_from_abbr() expects parameter 2 to be integer, array given in %s on line %d
bool(false)

-- nested arrays --

Warning: timezone_name_from_abbr() expects parameter 2 to be integer, array given in %s on line %d
bool(false)

-- uppercase NULL --
string(3) "UTC"

-- lowercase null --
string(3) "UTC"

-- lowercase true --
string(3) "UTC"

-- lowercase false --
string(3) "UTC"

-- uppercase TRUE --
string(3) "UTC"

-- uppercase FALSE --
string(3) "UTC"

-- empty string DQ --

Warning: timezone_name_from_abbr() expects parameter 2 to be integer, string given in %s on line %d
bool(false)

-- empty string SQ --

Warning: timezone_name_from_abbr() expects parameter 2 to be integer, string given in %s on line %d
bool(false)

-- string DQ --

Warning: timezone_name_from_abbr() expects parameter 2 to be integer, string given in %s on line %d
bool(false)

-- string SQ --

Warning: timezone_name_from_abbr() expects parameter 2 to be integer, string given in %s on line %d
bool(false)

-- mixed case string --

Warning: timezone_name_from_abbr() expects parameter 2 to be integer, string given in %s on line %d
bool(false)

-- heredoc --

Warning: timezone_name_from_abbr() expects parameter 2 to be integer, string given in %s on line %d
bool(false)

-- instance of classWithToString --

Warning: timezone_name_from_abbr() expects parameter 2 to be integer, object given in %s on line %d
bool(false)

-- instance of classWithoutToString --

Warning: timezone_name_from_abbr() expects parameter 2 to be integer, object given in %s on line %d
bool(false)

-- undefined var --
string(3) "UTC"

-- unset var --
string(3) "UTC"

-- resource --

Warning: timezone_name_from_abbr() expects parameter 2 to be integer, resource given in %s on line %d
bool(false)
===DONE===