*** Testing timezone_offset_get() : error conditions ***

-- Testing timezone_offset_get() function with zero arguments --
bool(false)

-- Testing timezone_offset_get() function with less than expected no. of arguments --
bool(false)

-- Testing timezone_offset_get() function with more than expected no. of arguments --
bool(false)

-- Testing timezone_offset_get() function with an invalid values for $object argument --
string(%d) "Argument 1 passed to timezone_offset_get() must be an instance of DateTimeZone, instance of stdClass given"

string(%d) "Argument 1 passed to timezone_offset_get() must be an instance of DateTimeZone, integer given"

string(%d) "Argument 1 passed to timezone_offset_get() must be an instance of DateTimeZone, null given"


-- Testing timezone_offset_get() function with an invalid values for $datetime argument --
string(%d) "Argument 2 passed to timezone_offset_get() must implement interface DateTimeInterface, instance of stdClass given"

string(%d) "Argument 2 passed to timezone_offset_get() must implement interface DateTimeInterface, integer given"

string(%d) "Argument 2 passed to timezone_offset_get() must implement interface DateTimeInterface, null given"

===DONE===