*** Testing timezone_open() : usage variation -  unexpected values to first argument $timezone***

-- int 0 --

Warning: timezone_open(): Unknown or bad timezone (0) in %s on line %d
bool(false)

-- int 1 --

Warning: timezone_open(): Unknown or bad timezone (1) in %s on line %d
bool(false)

-- int 12345 --

Warning: timezone_open(): Unknown or bad timezone (12345) in %s on line %d
bool(false)

-- float 10.5 --

Warning: timezone_open(): Unknown or bad timezone (10.5) in %s on line %d
bool(false)

-- float .5 --

Warning: timezone_open(): Unknown or bad timezone (0.5) in %s on line %d
bool(false)

-- empty array --

Warning: timezone_open() expects parameter 1 to be string, array given in %s on line %d
bool(false)

-- int indexed array --

Warning: timezone_open() expects parameter 1 to be string, array given in %s on line %d
bool(false)

-- associative array --

Warning: timezone_open() expects parameter 1 to be string, array given in %s on line %d
bool(false)

-- nested arrays --

Warning: timezone_open() expects parameter 1 to be string, array given in %s on line %d
bool(false)

-- uppercase NULL --

Warning: timezone_open(): Unknown or bad timezone () in %s on line %d
bool(false)

-- lowercase null --

Warning: timezone_open(): Unknown or bad timezone () in %s on line %d
bool(false)

-- lowercase true --

Warning: timezone_open(): Unknown or bad timezone (1) in %s on line %d
bool(false)

-- lowercase false --

Warning: timezone_open(): Unknown or bad timezone () in %s on line %d
bool(false)

-- uppercase TRUE --

Warning: timezone_open(): Unknown or bad timezone (1) in %s on line %d
bool(false)

-- uppercase FALSE --

Warning: timezone_open(): Unknown or bad timezone () in %s on line %d
bool(false)

-- empty string DQ --

Warning: timezone_open(): Unknown or bad timezone () in %s on line %d
bool(false)

-- empty string SQ --

Warning: timezone_open(): Unknown or bad timezone () in %s on line %d
bool(false)

-- string DQ --

Warning: timezone_open(): Unknown or bad timezone (string) in %s on line %d
bool(false)

-- string SQ --

Warning: timezone_open(): Unknown or bad timezone (string) in %s on line %d
bool(false)

-- mixed case string --

Warning: timezone_open(): Unknown or bad timezone (sTrInG) in %s on line %d
bool(false)

-- heredoc --

Warning: timezone_open(): Unknown or bad timezone (hello world) in %s on line %d
bool(false)

-- instance of classWithToString --

Warning: timezone_open(): Unknown or bad timezone (Class A object) in %s on line %d
bool(false)

-- instance of classWithoutToString --

Warning: timezone_open() expects parameter 1 to be string, object given in %s on line %d
bool(false)

-- undefined var --

Warning: timezone_open(): Unknown or bad timezone () in %s on line %d
bool(false)

-- unset var --

Warning: timezone_open(): Unknown or bad timezone () in %s on line %d
bool(false)

-- resource --

Warning: timezone_open() expects parameter 1 to be string, resource given in %s on line %d
bool(false)
===DONE===