*** Testing timezone_transitions_get() : error conditions ***

-- Testing timezone_transitions_get() function with zero arguments --

Warning: timezone_transitions_get() expects at least 1 parameter, 0 given in %s on line %d
bool(false)

-- Testing timezone_transitions_get() function with more than expected no. of arguments --

Warning: timezone_transitions_get() expects at most 3 parameters, 4 given in %s on line %d
bool(false)

-- Testing timezone_transitions_get() function with an invalid values for $object argument --

Warning: timezone_transitions_get() expects parameter 1 to be DateTimeZone, object given in %s on line %d
bool(false)

Warning: timezone_transitions_get() expects parameter 1 to be DateTimeZone, integer given in %s on line %d
bool(false)

Warning: timezone_transitions_get() expects parameter 1 to be DateTimeZone, null given in %s on line %d
bool(false)
===DONE===