*** Testing timezone_name_from_abbr() : error conditions ***

-- Testing timezone_name_from_abbr() function with Zero arguments --

Warning: timezone_name_from_abbr() expects at least 1 parameter, 0 given in %s on line %d
bool(false)

-- Testing timezone_name_from_abbr() function with more than expected no. of arguments --

Warning: timezone_name_from_abbr() expects at most 3 parameters, 4 given in %s on line %d
bool(false)
===DONE===