*** Testing chdir() : usage variations ***

-- Iteration 1 --

Warning: chdir(): %s (errno %d) in %s on line %d
bool(false)

-- Iteration 2 --

Warning: chdir(): %s (errno %d) in %s on line %d
bool(false)

-- Iteration 3 --

Warning: chdir(): %s (errno %d) in %s on line %d
bool(false)

-- Iteration 4 --

Warning: chdir(): %s (errno %d) in %s on line %d
bool(false)

-- Iteration 5 --

Warning: chdir(): %s (errno %d) in %s on line %d
bool(false)

-- Iteration 6 --

Warning: chdir(): %s (errno %d) in %s on line %d
bool(false)

-- Iteration 7 --

Warning: chdir(): %s (errno %d) in %s on line %d
bool(false)

-- Iteration 8 --

Warning: chdir(): %s (errno %d) in %s on line %d
bool(false)

-- Iteration 9 --

Warning: chdir(): %s (errno %d) in %s on line %d
bool(false)

-- Iteration 10 --

Warning: chdir(): %s (errno %d) in %s on line %d
bool(false)

-- Iteration 11 --

Warning: chdir(): %s (errno %d) in %s on line %d
bool(false)

-- Iteration 12 --

Warning: chdir(): %s (errno %d) in %s on line %d
bool(false)

-- Iteration 13 --

Warning: chdir(): %s (errno %d) in %s on line %d
bool(false)

-- Iteration 14 --

Warning: chdir(): %s (errno %d) in %s on line %d
bool(false)

-- Iteration 15 --

Warning: chdir(): %s (errno %d) in %s on line %d
bool(false)

-- Iteration 16 --

Warning: chdir(): %s (errno %d) in %s on line %d
bool(false)

-- Iteration 17 --

Warning: chdir(): %s (errno %d) in %s on line %d
bool(false)

-- Iteration 18 --

Warning: chdir() expects parameter 1 to be a valid path, array given in %s on line %d
bool(false)

-- Iteration 19 --
bool(true)

-- Iteration 20 --

Warning: chdir(): %s (errno %d) in %s on line %d
bool(false)

-- Iteration 21 --
bool(true)

-- Iteration 22 --
bool(true)

-- Iteration 23 --

Warning: chdir(): %s (errno %d) in %s on line %d
bool(false)

-- Iteration 24 --

Warning: chdir(): %s (errno %d) in %s on line %d
bool(false)

-- Iteration 25 --

Warning: chdir() expects parameter 1 to be a valid path, resource given in %s on line %d
bool(false)
===DONE===