*** Testing dir() : unexpected values for $directory argument ***

-- Iteration 1 --

Warning: dir() expects parameter 1 to be a valid path, array given in %s on line %d
NULL

-- Iteration 2 --

Warning: dir() expects parameter 1 to be a valid path, array given in %s on line %d
NULL

-- Iteration 3 --

Warning: dir() expects parameter 1 to be a valid path, array given in %s on line %d
NULL

-- Iteration 4 --

Warning: dir() expects parameter 1 to be a valid path, array given in %s on line %d
NULL

-- Iteration 5 --

Warning: dir() expects parameter 1 to be a valid path, array given in %s on line %d
NULL

-- Iteration 6 --
bool(false)

-- Iteration 7 --
bool(false)

-- Iteration 8 --

Warning: dir(1): failed to open dir: %s in %s on line %d
bool(false)

-- Iteration 9 --
bool(false)

-- Iteration 10 --

Warning: dir(1): failed to open dir: %s in %s on line %d
bool(false)

-- Iteration 11 --
bool(false)

-- Iteration 12 --
bool(false)

-- Iteration 13 --
bool(false)

-- Iteration 14 --
bool(false)

-- Iteration 15 --
bool(false)

-- Iteration 16 --

Warning: dir() expects parameter 1 to be a valid path, resource given in %s on line %d
NULL

-- Iteration 17 --

Warning: dir() expects parameter 1 to be a valid path, resource given in %s on line %d
NULL

-- Iteration 18 --

Warning: dir() expects parameter 1 to be a valid path, object given in %s on line %d
NULL
Done