*** Testing dir() : unexpected values for $context argument ***

-- Iteration 1 --
Warning: dir() expects parameter 2 to be resource, integer given in %s on line %d
NULL

-- Iteration 2 --
Warning: dir() expects parameter 2 to be resource, integer given in %s on line %d
NULL

-- Iteration 3 --
Warning: dir() expects parameter 2 to be resource, integer given in %s on line %d
NULL

-- Iteration 4 --
Warning: dir() expects parameter 2 to be resource, integer given in %s on line %d
NULL

-- Iteration 5 --
Warning: dir() expects parameter 2 to be resource, float given in %s on line %d
NULL

-- Iteration 6 --
Warning: dir() expects parameter 2 to be resource, float given in %s on line %d
NULL

-- Iteration 7 --
Warning: dir() expects parameter 2 to be resource, float given in %s on line %d
NULL

-- Iteration 8 --
Warning: dir() expects parameter 2 to be resource, float given in %s on line %d
NULL

-- Iteration 9 --
Warning: dir() expects parameter 2 to be resource, float given in %s on line %d
NULL

-- Iteration 10 --
Warning: dir() expects parameter 2 to be resource, array given in %s on line %d
NULL

-- Iteration 11 --
Warning: dir() expects parameter 2 to be resource, array given in %s on line %d
NULL

-- Iteration 12 --
Warning: dir() expects parameter 2 to be resource, array given in %s on line %d
NULL

-- Iteration 13 --
Warning: dir() expects parameter 2 to be resource, array given in %s on line %d
NULL

-- Iteration 14 --
Warning: dir() expects parameter 2 to be resource, array given in %s on line %d
NULL

-- Iteration 15 --
Warning: dir() expects parameter 2 to be resource, null given in %s on line %d
NULL

-- Iteration 16 --
Warning: dir() expects parameter 2 to be resource, null given in %s on line %d
NULL

-- Iteration 17 --
Warning: dir() expects parameter 2 to be resource, boolean given in %s on line %d
NULL

-- Iteration 18 --
Warning: dir() expects parameter 2 to be resource, boolean given in %s on line %d
NULL

-- Iteration 19 --
Warning: dir() expects parameter 2 to be resource, boolean given in %s on line %d
NULL

-- Iteration 20 --
Warning: dir() expects parameter 2 to be resource, boolean given in %s on line %d
NULL

-- Iteration 21 --
Warning: dir() expects parameter 2 to be resource, string given in %s on line %d
NULL

-- Iteration 22 --
Warning: dir() expects parameter 2 to be resource, string given in %s on line %d
NULL

-- Iteration 23 --
Warning: dir() expects parameter 2 to be resource, string given in %s on line %d
NULL

-- Iteration 24 --
Warning: dir() expects parameter 2 to be resource, string given in %s on line %d
NULL

-- Iteration 25 --
Warning: dir() expects parameter 2 to be resource, string given in %s on line %d
NULL

-- Iteration 26 --
Warning: dir() expects parameter 2 to be resource, object given in %s on line %d
NULL

-- Iteration 27 --
Warning: dir() expects parameter 2 to be resource, null given in %s on line %d
NULL

-- Iteration 28 --
Warning: dir() expects parameter 2 to be resource, null given in %s on line %d
NULL
Done