*** Testing opendir() : usage variations ***

-- Wildcard = '*' --

Warning: opendir(%s/opendir_var*): failed to open dir: %s in %s on line %d
bool(false)

Warning: opendir(%s/*): failed to open dir: %s in %s on line %d
bool(false)

-- Wildcard = '?' --

Warning: opendir(%s/opendir_variation6/sub_dir?): failed to open dir: %s in %s on line %d
bool(false)

Warning: opendir(%s/opendir_variation6/sub?dir1): failed to open dir: %s in %s on line %d
bool(false)
===DONE===