*** Testing opendir() : usage variation ***

-- Iteration 1 --

Warning: opendir() expects parameter 2 to be resource, integer given in %s on line %d
NULL

-- Iteration 2 --

Warning: opendir() expects parameter 2 to be resource, integer given in %s on line %d
NULL

-- Iteration 3 --

Warning: opendir() expects parameter 2 to be resource, integer given in %s on line %d
NULL

-- Iteration 4 --

Warning: opendir() expects parameter 2 to be resource, integer given in %s on line %d
NULL

-- Iteration 5 --

Warning: opendir() expects parameter 2 to be resource, float given in %s on line %d
NULL

-- Iteration 6 --

Warning: opendir() expects parameter 2 to be resource, float given in %s on line %d
NULL

-- Iteration 7 --

Warning: opendir() expects parameter 2 to be resource, float given in %s on line %d
NULL

-- Iteration 8 --

Warning: opendir() expects parameter 2 to be resource, float given in %s on line %d
NULL

-- Iteration 9 --

Warning: opendir() expects parameter 2 to be resource, float given in %s on line %d
NULL

-- Iteration 10 --

Warning: opendir() expects parameter 2 to be resource, null given in %s on line %d
NULL

-- Iteration 11 --

Warning: opendir() expects parameter 2 to be resource, null given in %s on line %d
NULL

-- Iteration 12 --

Warning: opendir() expects parameter 2 to be resource, boolean given in %s on line %d
NULL

-- Iteration 13 --

Warning: opendir() expects parameter 2 to be resource, boolean given in %s on line %d
NULL

-- Iteration 14 --

Warning: opendir() expects parameter 2 to be resource, boolean given in %s on line %d
NULL

-- Iteration 15 --

Warning: opendir() expects parameter 2 to be resource, boolean given in %s on line %d
NULL

-- Iteration 16 --

Warning: opendir() expects parameter 2 to be resource, string given in %s on line %d
NULL

-- Iteration 17 --

Warning: opendir() expects parameter 2 to be resource, string given in %s on line %d
NULL

-- Iteration 18 --

Warning: opendir() expects parameter 2 to be resource, array given in %s on line %d
NULL

-- Iteration 19 --

Warning: opendir() expects parameter 2 to be resource, string given in %s on line %d
NULL

-- Iteration 20 --

Warning: opendir() expects parameter 2 to be resource, string given in %s on line %d
NULL

-- Iteration 21 --

Warning: opendir() expects parameter 2 to be resource, string given in %s on line %d
NULL

-- Iteration 22 --

Warning: opendir() expects parameter 2 to be resource, object given in %s on line %d
NULL

-- Iteration 23 --

Warning: opendir() expects parameter 2 to be resource, null given in %s on line %d
NULL

-- Iteration 24 --

Warning: opendir() expects parameter 2 to be resource, null given in %s on line %d
NULL

-- Iteration 25 --

Warning: opendir(): supplied resource is not a valid Stream-Context resource in %s on line %d
resource(%d) of type (stream)
===DONE===