*** Testing scandir() : error conditions ***

-- Pass scandir() an absolute path that does not exist --

Warning: scandir(%s/idonotexist): failed to open dir: %s in %s on line %d

Warning: scandir(): (errno %d): %s in %s on line %d
bool(false)

-- Pass scandir() a relative path that does not exist --

Warning: scandir(/idonotexist): failed to open dir: %s in %s on line %d

Warning: scandir(): (errno %d): %s in %s on line %d
bool(false)
===DONE===