*** Testing scandir() : usage variations ***

-- Iteration 1 --

Warning: scandir() expects parameter 3 to be resource, integer given in %s on line %d
NULL

-- Iteration 2 --

Warning: scandir() expects parameter 3 to be resource, integer given in %s on line %d
NULL

-- Iteration 3 --

Warning: scandir() expects parameter 3 to be resource, integer given in %s on line %d
NULL

-- Iteration 4 --

Warning: scandir() expects parameter 3 to be resource, integer given in %s on line %d
NULL

-- Iteration 5 --

Warning: scandir() expects parameter 3 to be resource, float given in %s on line %d
NULL

-- Iteration 6 --

Warning: scandir() expects parameter 3 to be resource, float given in %s on line %d
NULL

-- Iteration 7 --

Warning: scandir() expects parameter 3 to be resource, float given in %s on line %d
NULL

-- Iteration 8 --

Warning: scandir() expects parameter 3 to be resource, float given in %s on line %d
NULL

-- Iteration 9 --

Warning: scandir() expects parameter 3 to be resource, float given in %s on line %d
NULL

-- Iteration 10 --

Warning: scandir() expects parameter 3 to be resource, null given in %s on line %d
NULL

-- Iteration 11 --

Warning: scandir() expects parameter 3 to be resource, null given in %s on line %d
NULL

-- Iteration 12 --

Warning: scandir() expects parameter 3 to be resource, boolean given in %s on line %d
NULL

-- Iteration 13 --

Warning: scandir() expects parameter 3 to be resource, boolean given in %s on line %d
NULL

-- Iteration 14 --

Warning: scandir() expects parameter 3 to be resource, boolean given in %s on line %d
NULL

-- Iteration 15 --

Warning: scandir() expects parameter 3 to be resource, boolean given in %s on line %d
NULL

-- Iteration 16 --

Warning: scandir() expects parameter 3 to be resource, string given in %s on line %d
NULL

-- Iteration 17 --

Warning: scandir() expects parameter 3 to be resource, string given in %s on line %d
NULL

-- Iteration 18 --

Warning: scandir() expects parameter 3 to be resource, array given in %s on line %d
NULL

-- Iteration 19 --

Warning: scandir() expects parameter 3 to be resource, string given in %s on line %d
NULL

-- Iteration 20 --

Warning: scandir() expects parameter 3 to be resource, string given in %s on line %d
NULL

-- Iteration 21 --

Warning: scandir() expects parameter 3 to be resource, string given in %s on line %d
NULL

-- Iteration 22 --

Warning: scandir() expects parameter 3 to be resource, object given in %s on line %d
NULL

-- Iteration 23 --

Warning: scandir() expects parameter 3 to be resource, null given in %s on line %d
NULL

-- Iteration 24 --

Warning: scandir() expects parameter 3 to be resource, null given in %s on line %d
NULL

-- Iteration 25 --

Warning: scandir(): supplied resource is not a valid Stream-Context resource in %s on line %d
array(2) {
  [0]=>
  string(1) "."
  [1]=>
  string(2) ".."
}
===DONE===