string(10) "‚ ‚¢‚¤‚¦‚¨" refcount(%d)
string(10) "¤¢¤¤¤¦¤¨¤ª" refcount(%d)
string(10) "¤¢¤¤¤¦¤¨¤ª" refcount(%d)
string(10) "¤¢¤¤¤¦¤¨¤ª" refcount(%d)
array(1) refcount(%d){
  [0]=>
  string(10) "‚ ‚¢‚¤‚¦‚¨" refcount(%d)
}
array(1) refcount(%d){
  [0]=>
  string(10) "¤¢¤¤¤¦¤¨¤ª" refcount(%d)
}
array(1) refcount(%d){
  [0]=>
  &string(10) "‚ ‚¢‚¤‚¦‚¨" refcount(%d)
}
array(1) refcount(%d){
  [0]=>
  string(10) "¤¢¤¤¤¦¤¨¤ª" refcount(%d)
}
array(1) refcount(%d){
  [0]=>
  string(10) "¤¢¤¤¤¦¤¨¤ª" refcount(%d)
}
array(1) refcount(%d){
  [0]=>
  string(10) "¤¢¤¤¤¦¤¨¤ª" refcount(%d)
}
array(1) refcount(%d){
  [0]=>
  string(10) "¤¢¤¤¤¦¤¨¤ª" refcount(%d)
}
array(1) refcount(%d){
  [0]=>
  string(10) "¤¢¤¤¤¦¤¨¤ª" refcount(%d)
}
array(1) refcount(%d){
  [0]=>
  array(1) refcount(%d){
    [0]=>
    string(10) "‚ ‚¢‚¤‚¦‚¨" refcount(%d)
  }
}
array(1) refcount(%d){
  [0]=>
  array(1) refcount(%d){
    [0]=>
    string(10) "¤¢¤¤¤¦¤¨¤ª" refcount(%d)
  }
}