-- Iteration 1 --

Warning: mb_strtolower(): Unknown encoding "12345" in %s on line %d
bool(false)

Warning: mb_strtoupper(): Unknown encoding "12345" in %s on line %d
bool(false)

-- Iteration 2 --

Warning: mb_strtolower(): Unknown encoding "1.23456789E-9" in %s on line %d
bool(false)

Warning: mb_strtoupper(): Unknown encoding "1.23456789E-9" in %s on line %d
bool(false)

-- Iteration 3 --

Warning: mb_strtolower(): Unknown encoding "1" in %s on line %d
bool(false)

Warning: mb_strtoupper(): Unknown encoding "1" in %s on line %d
bool(false)

-- Iteration 4 --

Warning: mb_strtolower(): Unknown encoding "" in %s on line %d
bool(false)

Warning: mb_strtoupper(): Unknown encoding "" in %s on line %d
bool(false)

-- Iteration 5 --

Warning: mb_strtolower(): Unknown encoding "" in %s on line %d
bool(false)

Warning: mb_strtoupper(): Unknown encoding "" in %s on line %d
bool(false)