-- Offset is 20 --
--Multibyte String:--
int(20)
--ASCII String:--
int(20)

-- Offset is 21 --
--Multibyte String:--
bool(false)
--ASCII String:--
bool(false)

-- Offset is 22 --
--Multibyte String:--

Warning: mb_strpos(): Offset not contained in string in %s on line %d
bool(false)
--ASCII String:--

Warning: mb_strpos(): Offset not contained in string in %s on line %d
bool(false)

-- Offset is 53 --
--Multibyte String:--

Warning: mb_strpos(): Offset not contained in string in %s on line %d
bool(false)
--ASCII String:--

Warning: mb_strpos(): Offset not contained in string in %s on line %d
bool(false)

-- Offset is 54 --
--Multibyte String:--

Warning: mb_strpos(): Offset not contained in string in %s on line %d
bool(false)
--ASCII String:--

Warning: mb_strpos(): Offset not contained in string in %s on line %d
bool(false)