-- Iteration 1 --
Without $regs arg:

Warning: mb_ereg(): empty pattern in %s on line %d
bool(false)
With $regs arg:

Warning: mb_ereg(): empty pattern in %s on line %d
bool(false)
array(0) {
}

-- Iteration 2 --
Without $regs arg:

Warning: mb_ereg(): empty pattern in %s on line %d
bool(false)
With $regs arg:

Warning: mb_ereg(): empty pattern in %s on line %d
bool(false)
array(0) {
}

-- Iteration 3 --
Without $regs arg:

Warning: mb_ereg(): empty pattern in %s on line %d
bool(false)
With $regs arg:

Warning: mb_ereg(): empty pattern in %s on line %d
bool(false)
array(0) {
}

-- Iteration 4 --
Without $regs arg:

Warning: mb_ereg(): empty pattern in %s on line %d
bool(false)
With $regs arg:

Warning: mb_ereg(): empty pattern in %s on line %d
bool(false)
array(0) {
}

-- Iteration 5 --
Without $regs arg:

Warning: mb_ereg(): empty pattern in %s on line %d
bool(false)
With $regs arg:

Warning: mb_ereg(): empty pattern in %s on line %d
bool(false)
array(0) {
}

-- Iteration 6 --
Without $regs arg:

Warning: mb_ereg(): empty pattern in %s on line %d
bool(false)
With $regs arg:

Warning: mb_ereg(): empty pattern in %s on line %d
bool(false)
array(0) {
}

-- Iteration 7 --
Without $regs arg:

Warning: mb_ereg(): empty pattern in %s on line %d
bool(false)
With $regs arg:

Warning: mb_ereg(): empty pattern in %s on line %d
bool(false)
array(0) {
}

-- Iteration 8 --
Without $regs arg:

Warning: mb_ereg(): empty pattern in %s on line %d
bool(false)
With $regs arg:

Warning: mb_ereg(): empty pattern in %s on line %d
bool(false)
array(0) {
}