Warning: mb_convert_variables(): %s on line %d
bool(false)

Warning: mb_convert_variables(): %s on line %d
bool(false)
string(5) "UTF-8"
array(4) {
  [0]=>
  string(21) "日本語テキスト"
  [1]=>
  string(21) "日本語テキスト"
  [2]=>
  string(21) "日本語テキスト"
  [3]=>
  string(21) "日本語テキスト"
}

Warning: mb_convert_variables(): %s on line %d
bool(false)
array(5) {
  [0]=>
  string(21) "日本語テキスト"
  [1]=>
  string(21) "日本語テキスト"
  [2]=>
  string(21) "日本語テキスト"
  [3]=>
  string(21) "日本語テキスト"
  [4]=>
  *RECURSION*
}