*** Testing mb_ereg_replace() : error conditions ***

-- Testing mb_ereg_replace() function with more than expected no. of arguments --

Warning: mb_ereg_replace() expects at most 4 parameters, 5 given in %s on line %d
bool(false)

-- Testing mb_ereg_replace() function with less than expected no. of arguments --

Warning: mb_ereg_replace() expects at least 3 parameters, 2 given in %s on line %d
bool(false)
Done