bool(true)

Warning: mb_ereg_search_setpos(): Position is out of range in %s on line %d
bool(false)

* Position: 5 :
bool(true)
int(5)

* Position: 20 :
bool(true)
int(20)

* Position: 21 :

Warning: mb_ereg_search_setpos(): Position is out of range in %s on line %d
bool(false)
int(0)

* Position: 25 :

Warning: mb_ereg_search_setpos(): Position is out of range in %s on line %d
bool(false)
int(0)

* Position: 0 :
bool(true)
int(0)

* Position: -5 :
bool(true)
int(15)

* Position: -20 :
bool(true)
int(0)

* Position: -30 :

Warning: mb_ereg_search_setpos(): Position is out of range in %s on line %d
bool(false)
int(0)
==DONE==