*** Testing mb_ereg_match() : error conditions ***

-- Testing mb_ereg_match() function with more than expected no. of arguments --

Warning: mb_ereg_match() expects at most 3 parameters, 4 given in %s on line %d
bool(false)

-- Testing mb_ereg_match() function with less than expected no. of arguments --

Warning: mb_ereg_match() expects at least 2 parameters, 1 given in %s on line %d
bool(false)

-- Testing mb_ereg_match() function with zero arguments --

Warning: mb_ereg_match() expects at least 2 parameters, 0 given in %s on line %d
bool(false)
Done