*** Testing mb_ereg() : usage variations ***

-- Iteration 1 --
bool(false)
array(0) {
}

-- Iteration 2 --
bool(false)
array(0) {
}

-- Iteration 3 --
bool(false)
array(0) {
}

-- Iteration 4 --
bool(false)
array(0) {
}

-- Iteration 5 --
bool(false)
array(0) {
}

-- Iteration 6 --
bool(false)
array(0) {
}

-- Iteration 7 --
bool(false)
array(0) {
}

-- Iteration 8 --
bool(false)
array(0) {
}

-- Iteration 9 --
bool(false)
array(0) {
}

-- Iteration 10 --
bool(false)
array(0) {
}

-- Iteration 11 --
bool(false)
array(0) {
}

-- Iteration 12 --
int(6)
array(1) {
  [0]=>
  string(6) "string"
}

-- Iteration 13 --
int(6)
array(1) {
  [0]=>
  string(6) "string"
}

-- Iteration 14 --
bool(false)
array(0) {
}

-- Iteration 15 --
bool(false)
array(0) {
}

-- Iteration 16 --
bool(false)
array(0) {
}
Done