*** Testing mb_ereg() : usage variations ***

-- Iteration 1 --
bool(false)
array(0) {
}

-- Iteration 2 --
bool(false)
array(0) {
}

-- Iteration 3 --
bool(false)
array(0) {
}

-- Iteration 4 --
bool(false)
array(0) {
}

-- Iteration 5 --
bool(false)
array(0) {
}

-- Iteration 6 --
bool(false)
array(0) {
}

-- Iteration 7 --
bool(false)
array(0) {
}

-- Iteration 8 --
bool(false)
array(0) {
}

-- Iteration 9 --
bool(false)
array(0) {
}

-- Iteration 10 --
bool(false)
array(0) {
}

-- Iteration 11 --
bool(false)
array(0) {
}

-- Iteration 12 --
bool(false)
array(0) {
}

-- Iteration 13 --
bool(false)
array(0) {
}

-- Iteration 14 --
bool(false)
array(0) {
}

-- Iteration 15 --
bool(false)
array(0) {
}

-- Iteration 16 --
bool(false)
array(0) {
}

-- Iteration 17 --
bool(false)
array(0) {
}

-- Iteration 18 --
int(3)
array(1) {
  [0]=>
  string(3) "str"
}

-- Iteration 19 --
int(3)
array(1) {
  [0]=>
  string(3) "str"
}

-- Iteration 20 --
bool(false)
array(0) {
}

-- Iteration 21 --
bool(false)
array(0) {
}

-- Iteration 22 --
bool(false)
array(0) {
}

-- Iteration 23 --
bool(false)
array(0) {
}

-- Iteration 24 --

Warning: mb_ereg() expects parameter 2 to be string, resource given in %s on line %d
bool(false)
NULL
Done