*** Testing mb_stripos() : usage variations ***

-- Iteration 1 --
int(8)

-- Iteration 2 --
int(8)

-- Iteration 3 --

Warning: mb_stripos(): Offset not contained in string in %s on line %d
bool(false)

-- Iteration 4 --
int(8)

-- Iteration 5 --

Warning: mb_stripos(): Offset not contained in string in %s on line %d
bool(false)

-- Iteration 6 --
bool(false)

-- Iteration 7 --
int(8)

-- Iteration 8 --

Warning: mb_stripos(): Offset not contained in string in %s on line %d
bool(false)

-- Iteration 9 --

Warning: mb_stripos(): Offset not contained in string in %s on line %d
bool(false)

-- Iteration 10 --
int(8)

-- Iteration 11 --
int(8)

-- Iteration 12 --
int(8)

-- Iteration 13 --
int(8)

-- Iteration 14 --
int(8)

-- Iteration 15 --
int(8)

-- Iteration 16 --
int(8)

-- Iteration 17 --
int(8)

-- Iteration 18 --

Warning: mb_stripos() expects parameter 3 to be integer, string given in %s on line %d
NULL

-- Iteration 19 --

Warning: mb_stripos() expects parameter 3 to be integer, string given in %s on line %d
NULL

-- Iteration 20 --

Warning: mb_stripos() expects parameter 3 to be integer, string given in %s on line %d
NULL

-- Iteration 21 --

Warning: mb_stripos() expects parameter 3 to be integer, string given in %s on line %d
NULL

-- Iteration 22 --

Warning: mb_stripos() expects parameter 3 to be integer, string given in %s on line %d
NULL

-- Iteration 23 --

Warning: mb_stripos() expects parameter 3 to be integer, object given in %s on line %d
NULL

-- Iteration 24 --
int(8)

-- Iteration 25 --
int(8)

-- Iteration 26 --

Warning: mb_stripos() expects parameter 3 to be integer, resource given in %s on line %d
NULL
Done