*** Testing mb_strpos() : usage variations ***

**-- Offset is: -30 --**
-- ASCII String --

Warning: mb_strpos(): Offset not contained in string in %s on line %d
bool(false)
--Multibyte String --

Warning: mb_strpos(): Offset not contained in string in %s on line %d
bool(false)

**-- Offset is: -20 --**
-- ASCII String --
int(9)
--Multibyte String --
int(9)

**-- Offset is: -10 --**
-- ASCII String --
int(20)
--Multibyte String --
int(20)

**-- Offset is: 0 --**
-- ASCII String --
int(9)
--Multibyte String --
int(9)

**-- Offset is: 10 --**
-- ASCII String --
int(20)
--Multibyte String --
int(20)

**-- Offset is: 20 --**
-- ASCII String --
int(20)
--Multibyte String --
int(20)

**-- Offset is: 30 --**
-- ASCII String --

Warning: mb_strpos(): Offset not contained in string in %s on line %d
bool(false)
--Multibyte String --

Warning: mb_strpos(): Offset not contained in string in %s on line %d
bool(false)

**-- Offset is: 40 --**
-- ASCII String --

Warning: mb_strpos(): Offset not contained in string in %s on line %d
bool(false)
--Multibyte String --

Warning: mb_strpos(): Offset not contained in string in %s on line %d
bool(false)

**-- Offset is: 50 --**
-- ASCII String --

Warning: mb_strpos(): Offset not contained in string in %s on line %d
bool(false)
--Multibyte String --

Warning: mb_strpos(): Offset not contained in string in %s on line %d
bool(false)

**-- Offset is: 60 --**
-- ASCII String --

Warning: mb_strpos(): Offset not contained in string in %s on line %d
bool(false)
--Multibyte String --

Warning: mb_strpos(): Offset not contained in string in %s on line %d
bool(false)
Done