*** Testing mb_strstr() : usage variation ***

--int 0--
bool(false)

--int 1--
bool(false)

--int 12345--
bool(false)

--int -12345--
bool(false)

--float 10.5--
bool(false)

--float -10.5--
bool(false)

--float 12.3456789000e10--
bool(false)

--float -12.3456789000e10--
bool(false)

--float .5--
bool(false)

--empty array--
Error: 2 - mb_strstr() expects parameter 2 to be string, array given, %s(%d)
NULL

--int indexed array--
Error: 2 - mb_strstr() expects parameter 2 to be string, array given, %s(%d)
NULL

--associative array--
Error: 2 - mb_strstr() expects parameter 2 to be string, array given, %s(%d)
NULL

--nested arrays--
Error: 2 - mb_strstr() expects parameter 2 to be string, array given, %s(%d)
NULL

--uppercase NULL--
Error: 2 - mb_strstr(): Empty delimiter, %s(%d)
bool(false)

--lowercase null--
Error: 2 - mb_strstr(): Empty delimiter, %s(%d)
bool(false)

--lowercase true--
bool(false)

--lowercase false--
Error: 2 - mb_strstr(): Empty delimiter, %s(%d)
bool(false)

--uppercase TRUE--
bool(false)

--uppercase FALSE--
Error: 2 - mb_strstr(): Empty delimiter, %s(%d)
bool(false)

--empty string DQ--
Error: 2 - mb_strstr(): Empty delimiter, %s(%d)
bool(false)

--empty string SQ--
Error: 2 - mb_strstr(): Empty delimiter, %s(%d)
bool(false)

--instance of classWithToString--
bool(false)

--instance of classWithoutToString--
Error: 2 - mb_strstr() expects parameter 2 to be string, object given, %s(%d)
NULL

--undefined var--
Error: 2 - mb_strstr(): Empty delimiter, %s(%d)
bool(false)

--unset var--
Error: 2 - mb_strstr(): Empty delimiter, %s(%d)
bool(false)

--resource--
Error: 2 - mb_strstr() expects parameter 2 to be string, resource given, %s(%d)
NULL
===DONE===