*** Testing mb_strpos() : usage variations ***

-- Iteration 1 --

Warning: mb_strpos(): Unknown encoding "0" in %s on line %d
bool(false)

-- Iteration 2 --

Warning: mb_strpos(): Unknown encoding "1" in %s on line %d
bool(false)

-- Iteration 3 --

Warning: mb_strpos(): Unknown encoding "12345" in %s on line %d
bool(false)

-- Iteration 4 --

Warning: mb_strpos(): Unknown encoding "-2345" in %s on line %d
bool(false)

-- Iteration 5 --

Warning: mb_strpos(): Unknown encoding "10.5" in %s on line %d
bool(false)

-- Iteration 6 --

Warning: mb_strpos(): Unknown encoding "-10.5" in %s on line %d
bool(false)

-- Iteration 7 --

Warning: mb_strpos(): Unknown encoding "123456789000" in %s on line %d
bool(false)

-- Iteration 8 --

Warning: mb_strpos(): Unknown encoding "1.23456789E-9" in %s on line %d
bool(false)

-- Iteration 9 --

Warning: mb_strpos(): Unknown encoding "0.5" in %s on line %d
bool(false)

-- Iteration 10 --

Warning: mb_strpos(): Unknown encoding "" in %s on line %d
bool(false)

-- Iteration 11 --

Warning: mb_strpos(): Unknown encoding "" in %s on line %d
bool(false)

-- Iteration 12 --

Warning: mb_strpos(): Unknown encoding "1" in %s on line %d
bool(false)

-- Iteration 13 --

Warning: mb_strpos(): Unknown encoding "" in %s on line %d
bool(false)

-- Iteration 14 --

Warning: mb_strpos(): Unknown encoding "1" in %s on line %d
bool(false)

-- Iteration 15 --

Warning: mb_strpos(): Unknown encoding "" in %s on line %d
bool(false)

-- Iteration 16 --

Warning: mb_strpos(): Unknown encoding "" in %s on line %d
bool(false)

-- Iteration 17 --

Warning: mb_strpos(): Unknown encoding "" in %s on line %d
bool(false)

-- Iteration 18 --
int(7)

-- Iteration 19 --
int(7)

-- Iteration 20 --
int(7)

-- Iteration 21 --
int(7)

-- Iteration 22 --

Warning: mb_strpos(): Unknown encoding "" in %s on line %d
bool(false)

-- Iteration 23 --

Warning: mb_strpos(): Unknown encoding "" in %s on line %d
bool(false)

-- Iteration 24 --

Warning: mb_strpos() expects parameter 4 to be string, resource given in %s on line %d
NULL
Done