*** Testing mb_strripos() : usage variations ***

-- Iteration 1 --
int(8)

-- Iteration 2 --
int(8)

-- Iteration 3 --

Warning: mb_strripos(): Offset is greater than the length of haystack string in %s on line %d
bool(false)

-- Iteration 4 --

Warning: mb_strripos(): Offset is greater than the length of haystack string in %s on line %d
bool(false)

-- Iteration 5 --

Warning: mb_strripos(): Offset is greater than the length of haystack string in %s on line %d
bool(false)

-- Iteration 6 --

Warning: mb_strripos(): Offset is greater than the length of haystack string in %s on line %d
bool(false)

-- Iteration 7 --

Warning: mb_strripos(): Offset is greater than the length of haystack string in %s on line %d
bool(false)

-- Iteration 8 --
int(8)

-- Iteration 9 --
int(8)

-- Iteration 10 --
int(8)

-- Iteration 11 --
int(8)

-- Iteration 12 --
int(8)

-- Iteration 13 --
int(8)

-- Iteration 14 --
int(8)

-- Iteration 15 --
int(8)

-- Iteration 16 --

Warning: mb_strripos() expects parameter 3 to be integer, string given in %s on line %d
NULL

-- Iteration 17 --

Warning: mb_strripos() expects parameter 3 to be integer, string given in %s on line %d
NULL

-- Iteration 18 --

Warning: mb_strripos() expects parameter 3 to be integer, string given in %s on line %d
NULL

-- Iteration 19 --

Warning: mb_strripos() expects parameter 3 to be integer, string given in %s on line %d
NULL

-- Iteration 20 --

Warning: mb_strripos() expects parameter 3 to be integer, string given in %s on line %d
NULL

-- Iteration 21 --

Warning: mb_strripos() expects parameter 3 to be integer, object given in %s on line %d
NULL

-- Iteration 22 --
int(8)

-- Iteration 23 --
int(8)

-- Iteration 24 --

Warning: mb_strripos() expects parameter 3 to be integer, resource given in %s on line %d
NULL
Done