Removing the current element from an iterated object.
string(10) "Original a"
string(10) "Original b"

Notice: Undefined property: C::$b in %s on line %d
string(10) "Original c"

Notice: Undefined property: C::$b in %s on line %d
string(10) "Original d"

Notice: Undefined property: C::$b in %s on line %d
string(10) "Original e"
object(C)#%d (4) {
  ["a"]=>
  string(10) "Original a"
  ["c"]=>
  string(10) "Original c"
  ["d"]=>
  string(10) "Original d"
  ["e"]=>
  string(10) "Original e"
}
===DONE===