$a
array(1) {
  [0]=>
  string(8) "original"
}

${'a'}
array(1) {
  [0]=>
  string(8) "original"
}

$$a
array(1) {
  [0]=>
  string(8) "original"
}

$a[0]
array(1) {
  [0]=>
  string(8) "original"
}

$a[0][0]
array(1) {
  [0]=>
  string(8) "original"
}

$a->b

Warning: Creating default object from empty value in %s on line %d
array(1) {
  [0]=>
  string(8) "original"
}

$a->b->c

Warning: Creating default object from empty value in %s on line %d
array(1) {
  [0]=>
  string(8) "original"
}

$a->b[0]
array(1) {
  [0]=>
  string(8) "original"
}

$a->b[0][0]
array(1) {
  [0]=>
  string(8) "original"
}

$a->b[0]->c

Warning: Creating default object from empty value in %s on line %d
array(1) {
  [0]=>
  string(8) "original"
}

C::$a
array(1) {
  [0]=>
  string(8) "original"
}

C::$a[0]
array(1) {
  [0]=>
  string(8) "original"
}

C::$a[0]->b

Warning: Creating default object from empty value in %s on line %d
array(1) {
  [0]=>
  string(8) "original"
}