Warning: filter_has_var() expects exactly 2 parameters, 0 given in %s on line %d
bool(false)
bool(false)

Warning: filter_has_var() expects parameter 2 to be string, array given in %s on line %d
bool(false)
bool(true)
bool(true)
bool(true)
bool(true)
bool(false)
bool(false)
bool(false)
bool(false)

Warning: filter_has_var() expects parameter 1 to be integer, string given in %s on line %d
bool(false)
Done