string(17) "01-23-45-67-89-ab"
string(17) "01-23-45-67-89-ab"
bool(false)
bool(false)
string(17) "01-23-45-67-89-AB"
string(17) "01-23-45-67-89-aB"
string(17) "01:23:45:67:89:ab"
string(17) "01:23:45:67:89:AB"
string(17) "01:23:45:67:89:aB"
bool(false)
bool(false)
string(14) "0123.4567.89ab"

Warning: filter_var(): Separator must be exactly one character long in %s055.php on line %d
bool(false)

Warning: filter_var(): Separator must be exactly one character long in %s055.php on line %d
bool(false)
Done