---11---
person: Joe
  child: Ann
  child: Marray
person: Boe
  child: Joe
  child: Ann
---12---
person: Joe
  child: Ann
---21---
person: Joe
  child: Ann
  child: Marray
person: Boe
  child: Joe
  child: Ann
---22---
person: Joe
  child: Ann
  child: 
person: 

Notice: Trying to get property of non-object in %s017.php on line %d
  child: 

Notice: Trying to get property of non-object in %s017.php on line %d
  child: 
===DONE===