<people>
</people>
<people>
  <person gender="male">Joe
  </person>
</people>
<people>
  <person gender="male">Jane
  </person>
</people>
<people>
  <person gender="female">Jane
  </person>
  <person gender="male">Joe
  </person>
</people>

Warning: main(): Cannot add element person number 3 when only 2 such elements exist in %s027.php on line %d
<people>
  <person gender="female">Jane
  </person>
  <person gender="male">Joe
  </person>
  <person gender="male">Minni-me
  </person>
</people>
<people>
  <person gender="female">Jane
  </person>
  <person gender="male">Joe
  </person>
  <person gender="male">Minni-me
  </person>
  <person gender="error">
  </person>
</people>
===DONE===