Warning: DOMDocument::loadHTML(): error parsing attribute name in Entity, line: 1 in %s on line %d

Warning: DOMDocument::loadHTML(): error parsing attribute name in Entity, line: 1 in %s on line %d
object(SimpleXMLElement)#%d (3) {
  ["@attributes"]=>
  array(2) {
    ["title"]=>
    string(0) ""
    ["y"]=>
    string(0) ""
  }
  [0]=>
  string(1) "x"
  [1]=>
  string(1) "x"
}
string(0) ""
string(0) ""