object(SimpleXMLElement)#1 (2) {
  ["b"]=>
  object(SimpleXMLElement)#2 (0) {
  }
  ["c"]=>
  object(SimpleXMLElement)#3 (1) {
    ["x"]=>
    object(SimpleXMLElement)#4 (0) {
    }
  }
}

object(SimpleXMLElement)#1 (3) {
  ["b"]=>
  object(SimpleXMLElement)#3 (0) {
  }
  ["d"]=>
  object(SimpleXMLElement)#2 (0) {
  }
  ["c"]=>
  object(SimpleXMLElement)#4 (1) {
    ["x"]=>
    object(SimpleXMLElement)#5 (0) {
    }
  }
}

object(SimpleXMLElement)#1 (2) {
  ["b"]=>
  object(SimpleXMLElement)#4 (0) {
  }
  ["c"]=>
  object(SimpleXMLElement)#2 (2) {
    ["d"]=>
    object(SimpleXMLElement)#3 (0) {
    }
    ["x"]=>
    object(SimpleXMLElement)#5 (0) {
    }
  }
}

object(SimpleXMLElement)#1 (2) {
  ["b"]=>
  object(SimpleXMLElement)#2 (0) {
  }
  ["c"]=>
  object(SimpleXMLElement)#4 (1) {
    ["d"]=>
    object(SimpleXMLElement)#5 (1) {
      ["x"]=>
      object(SimpleXMLElement)#3 (0) {
      }
    }
  }
}