Input: 1

Deprecated: Function mcrypt_create_iv() is deprecated in %s%ebug55169.php on line 4
 Length: 1
 Hex: %x

Input: 2

Deprecated: Function mcrypt_create_iv() is deprecated in %s%ebug55169.php on line 4
 Length: 2
 Hex: %x

Input: 4

Deprecated: Function mcrypt_create_iv() is deprecated in %s%ebug55169.php on line 4
 Length: 4
 Hex: %x

Input: 8

Deprecated: Function mcrypt_create_iv() is deprecated in %s%ebug55169.php on line 4
 Length: 8
 Hex: %x

Input: 16

Deprecated: Function mcrypt_create_iv() is deprecated in %s%ebug55169.php on line 4
 Length: 16
 Hex: %x

Input: 32

Deprecated: Function mcrypt_create_iv() is deprecated in %s%ebug55169.php on line 4
 Length: 32
 Hex: %x

Input: 64

Deprecated: Function mcrypt_create_iv() is deprecated in %s%ebug55169.php on line 4
 Length: 64
 Hex: %x