Deprecated: Function mcrypt_get_iv_size() is deprecated in %s%emcrypt_create_iv.php on line 2

Deprecated: Function mcrypt_create_iv() is deprecated in %s%emcrypt_create_iv.php on line 2

Deprecated: Function mcrypt_get_iv_size() is deprecated in %s%emcrypt_create_iv.php on line 3

Deprecated: Function mcrypt_create_iv() is deprecated in %s%emcrypt_create_iv.php on line 3

Deprecated: Function mcrypt_get_iv_size() is deprecated in %s%emcrypt_create_iv.php on line 4

Deprecated: Function mcrypt_create_iv() is deprecated in %s%emcrypt_create_iv.php on line 4
16
16
16