Deprecated: Function mcrypt_module_open() is deprecated in %s%emcrypt_enc_get_iv_size.php on line 2

Deprecated: Function mcrypt_enc_get_iv_size() is deprecated in %s%emcrypt_enc_get_iv_size.php on line 3
int(32)

Deprecated: Function mcrypt_module_open() is deprecated in %s%emcrypt_enc_get_iv_size.php on line 4

Deprecated: Function mcrypt_enc_get_iv_size() is deprecated in %s%emcrypt_enc_get_iv_size.php on line 5
int(8)

Deprecated: Function mcrypt_module_open() is deprecated in %s%emcrypt_enc_get_iv_size.php on line 6

Deprecated: Function mcrypt_enc_get_iv_size() is deprecated in %s%emcrypt_enc_get_iv_size.php on line 7
int(0)