Deprecated: Function mcrypt_get_iv_size() is deprecated in %s%emcrypt_decrypt.php on line 7

Deprecated: Function mcrypt_create_iv() is deprecated in %s%emcrypt_decrypt.php on line 7

Deprecated: Function mcrypt_encrypt() is deprecated in %s%emcrypt_decrypt.php on line 8

Deprecated: Function mcrypt_decrypt() is deprecated in %s%emcrypt_decrypt.php on line 11
PHP Testfest 2008

Deprecated: Function mcrypt_decrypt() is deprecated in %s%emcrypt_decrypt.php on line 14

Warning: mcrypt_decrypt(): Encryption mode requires an initialization vector of size 16 in %s on line %d
bool(false)

Deprecated: Function mcrypt_decrypt() is deprecated in %s%emcrypt_decrypt.php on line 16

Warning: mcrypt_decrypt(): Received initialization vector of size 16, but size 8 is required for this encryption mode in %s on line %d
bool(false)