=== 2453396
string(3) "Jan"
string(7) "January"
string(3) "Jan"
string(7) "January"
string(6) "Shevat"
string(0) ""

=== 2440588
string(3) "Jan"
string(7) "January"
string(3) "Dec"
string(8) "December"
string(5) "Tevet"
string(0) ""

=== -1
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""
string(0) ""

=== 
Notice: Array to string conversion in %sjdtomonthname.php on line %d
Array

Warning: jdmonthname() expects parameter 1 to be integer, array given in %s on line %d
bool(false)

Warning: jdmonthname() expects parameter 1 to be integer, array given in %s on line %d
bool(false)

Warning: jdmonthname() expects parameter 1 to be integer, array given in %s on line %d
bool(false)

Warning: jdmonthname() expects parameter 1 to be integer, array given in %s on line %d
bool(false)

Warning: jdmonthname() expects parameter 1 to be integer, array given in %s on line %d
bool(false)

Warning: jdmonthname() expects parameter 1 to be integer, array given in %s on line %d
bool(false)

=== 10000000
string(3) "Dec"
string(8) "December"
string(3) "Jul"
string(4) "July"
string(6) "Tishri"
string(0) ""

Done