Setting IP_MULTICAST_LOOP with 256
bool(true)
int(1)

Setting IP_MULTICAST_LOOP with false
bool(true)
int(0)

Setting IP_MULTICAST_TTL with 256

Warning: socket_set_option(): Expected a value between 0 and 255 in %s on line %d
bool(false)
int(1)

Setting IP_MULTICAST_TTL with "254"
bool(true)
int(254)

Setting IP_MULTICAST_TTL with -1

Warning: socket_set_option(): Expected a value between 0 and 255 in %s on line %d
bool(false)
int(254)