Warning: socket_import_stream() expects exactly 1 parameter, 0 given in %s on line %d
NULL

Warning: socket_import_stream() expects exactly 1 parameter, 2 given in %s on line %d
NULL

Warning: socket_import_stream() expects parameter 1 to be resource, integer given in %s on line %d
NULL

Warning: socket_import_stream() expects parameter 1 to be resource, object given in %s on line %d
NULL

Warning: socket_import_stream(): cannot represent a stream of type STDIO as a Socket Descriptor in %s on line %d
bool(false)

Warning: socket_import_stream(): supplied resource is not a valid stream resource in %s on line %d
bool(false)
resource(%d) of type (stream)
bool(true)

Warning: socket_import_stream(): supplied resource is not a valid stream resource in %s on line %d
bool(false)
Done.