Warning: socket_create_pair() expects exactly 4 parameters, 3 given in %s on line %d
NULL

Warning: socket_create_pair() expects parameter 1 to be integer, %unicode_string_optional% given in %s on line %d
NULL

Warning: socket_create_pair(): unable to create socket pair [%d]: %s not supported in %s on line %d
bool(false)

Warning: socket_create_pair(): invalid socket domain [31337] specified for argument 1, assuming AF_INET in %s on line %d

Warning: socket_create_pair(): unable to create socket pair [%d]: %s not supported in %s on line %d
bool(false)

Warning: socket_create_pair(): invalid socket type [31337] specified for argument 2, assuming SOCK_STREAM in %s on line %d

Warning: socket_create_pair(): unable to create socket pair [%d]: %s not supported %s on line %d
bool(false)