normal
stream_set_blocking 1
socket_set_block 1
socket_get_option 2


unset stream
socket_set_block 1
socket_get_option 2


unset socket
stream_set_blocking 1


close stream
stream_set_blocking 
Warning: stream_set_blocking(): supplied resource is not a valid stream resource in %s on line %d

socket_set_block 
Warning: socket_set_block(): unable to set blocking mode [%d]: %s in %s on line %d

socket_get_option 
Warning: socket_get_option(): unable to retrieve socket option [%d]: %s in %s on line %d



close socket
stream_set_blocking 
Warning: stream_set_blocking(): supplied resource is not a valid stream resource in %s on line %d

socket_set_block 
Warning: socket_set_block(): supplied resource is not a valid Socket resource in %s on line %d

socket_get_option 
Warning: socket_get_option(): supplied resource is not a valid Socket resource in %s on line %d


Done.