Warning: socket_export_stream() expects exactly 1 parameter, 0 given in %s on line %d
NULL

Warning: socket_export_stream() expects exactly 1 parameter, 2 given in %s on line %d
NULL

Warning: socket_export_stream() expects parameter 1 to be resource, integer given in %s on line %d
NULL

Warning: socket_export_stream() expects parameter 1 to be resource, object given in %s on line %d
NULL

Warning: socket_export_stream(): supplied resource is not a valid Socket resource in %s on line %d
bool(false)

Warning: socket_export_stream(): supplied resource is not a valid Socket resource in %s on line %d
bool(false)
resource(%d) of type (Socket)

Warning: socket_export_stream(): supplied resource is not a valid Socket resource in %s on line %d
bool(false)
Done.