*** Testing finfo_buffer() : error conditions ***

-- Testing finfo_buffer() function with more than expected no. of arguments --

Warning: finfo_buffer() expects at most 4 parameters, 5 given in %s on line %d
bool(false)

-- Testing finfo_buffer() function with less than expected no. of arguments --

Warning: finfo_buffer() expects at least 2 parameters, 1 given in %s on line %d
bool(false)
===DONE===