Testing gethostbyaddr : error conditions

-- Testing gethostbyaddr function with Zero arguments --

Warning: gethostbyaddr\(\) expects exactly 1 parameter, 0 given in .* on line \d+
NULL

-- Testing gethostbyaddr function with more than expected no. of arguments --

Warning: gethostbyaddr\(\) expects exactly 1 parameter, 2 given in .* on line \d+
NULL

-- Testing gethostbyaddr function with invalid addresses --

Warning: gethostbyaddr\(\): Address is not (in a.b.c.d form|a valid IPv4 or IPv6 address) in .* on line \d+
bool\(false\)

Warning: gethostbyaddr\(\): Address is not (in a.b.c.d form|a valid IPv4 or IPv6 address) in .* on line \d+
bool\(false\)

Warning: gethostbyaddr\(\): Address is not (in a.b.c.d form|a valid IPv4 or IPv6 address) in .* on line \d+
bool\(false\)
Done