%unicode|string%(9) "127.0.0.1"
%unicode|string%(13) "255.255.255.0"

Warning: inet_ntop() expects exactly 1 parameter, 0 given in %s on line %d
bool(false)

Warning: inet_ntop(): Invalid in_addr value in %s on line %d
bool(false)

Warning: inet_ntop(): Invalid in_addr value in %s on line %d
bool(false)

Warning: inet_ntop(): Invalid in_addr value in %s on line %d
bool(false)

Warning: inet_pton() expects exactly 1 parameter, 0 given in %s on line %d
bool(false)

Warning: inet_pton(): Unrecognized address  in %s on line %d
bool(false)

Warning: inet_pton(): Unrecognized address -1 in %s on line %d
bool(false)

Warning: inet_pton(): Unrecognized address abra in %s on line %d
bool(false)
%unicode|string%(%d) "7f000001"
%unicode|string%(9) "127.0.0.1"
%unicode|string%(%d) "42a3a174"
%unicode|string%(14) "66.163.161.116"
%unicode|string%(%d) "ffffffff"
%unicode|string%(15) "255.255.255.255"
%unicode|string%(%d) "00000000"
%unicode|string%(7) "0.0.0.0"
Done