*** Testing iconv_strpos() : usage variations ***
--
int(0)
int(8)
--
int(1)
int(8)
--
int(12345)
bool(false)
--
int(-5)
int(8)
--
int(-2345)

Warning: iconv_strpos(): Offset not contained in string. in %s on line %d
bool(false)
--
float(10.5)
bool(false)
--
float(-9.5)
int(8)
--
float(-100.3)

Warning: iconv_strpos(): Offset not contained in string. in %s on line %d
bool(false)
--
float(123456789000)
bool(false)
--
float(1.23456789E-9)
int(8)
--
float(0.5)
int(8)
--
NULL
int(8)
--
NULL
int(8)
--
bool(true)
int(8)
--
bool(false)
int(8)
--
bool(true)
int(8)
--
bool(false)
int(8)
--
string(0) ""

Warning: iconv_strpos() expects parameter 3 to be integer, string given in %s on line %d
bool(false)
--
string(0) ""

Warning: iconv_strpos() expects parameter 3 to be integer, string given in %s on line %d
bool(false)
--
string(6) "string"

Warning: iconv_strpos() expects parameter 3 to be integer, string given in %s on line %d
bool(false)
--
string(6) "string"

Warning: iconv_strpos() expects parameter 3 to be integer, string given in %s on line %d
bool(false)
--
string(11) "hello world"

Warning: iconv_strpos() expects parameter 3 to be integer, string given in %s on line %d
bool(false)
--
object(classA)#%d (%d) {
}

Warning: iconv_strpos() expects parameter 3 to be integer, object given in %s on line %d
bool(false)
--
NULL
int(8)
--
NULL
int(8)
--
resource(%d) of type (stream)

Warning: iconv_strpos() expects parameter 3 to be integer, resource given in %s on line %d
bool(false)
Done