object(PDOStatement)#%d (1) {
  [%u|b%"queryString"]=>
  %string|unicode%(21) "SELECT * FROM testing"
}
data: 1, php
object(PDOStatement)#%d (1) {
  [%u|b%"queryString"]=>
  %string|unicode%(21) "SELECT * FROM testing"
}
data: 2, 
array(2) {
  [0]=>
  %string|unicode%(3) "PHP"
  [1]=>
  %string|unicode%(0) ""
}

Warning: PDOStatement::fetchAll(): SQLSTATE[HY000]: General error: function 'nothing' not found or invalid function name in %s on line %d
bool(false)

Warning: PDOStatement::fetchAll(): SQLSTATE[HY000]: General error: function '' not found or invalid function name in %s on line %d
bool(false)

Warning: PDOStatement::fetchAll(): SQLSTATE[HY000]: General error: no array or string given in %s on line %d
bool(false)

Warning: PDOStatement::fetchAll(): SQLSTATE[HY000]: General error: no array or string given in %s on line %d
bool(false)

Warning: PDOStatement::fetchAll(): SQLSTATE[HY000]: General error: class 'PDOStatement' does not have a method 'foo' in %s on line %d
bool(false)
array(2) {
  [0]=>
  %string|unicode%(9) "--- 1 ---"
  [1]=>
  %string|unicode%(9) "--- 2 ---"
}
array(2) {
  [0]=>
  %string|unicode%(7) "1---php"
  [1]=>
  %string|unicode%(4) "2---"
}

Warning: PDOStatement::fetchAll(): SQLSTATE[HY000]: General error: cannot access private method bar::test2() in %s on line %d
bool(false)
array(2) {
  [0]=>
  %string|unicode%(7) "1===php"
  [1]=>
  %string|unicode%(4) "2==="
}

Warning: PDOStatement::fetchAll(): SQLSTATE[HY000]: General error: class 'bar' does not have a method 'inexistent' in %s on line %d
bool(false)