=> array_multisort:

Name: arr1
Is passed by reference: yes
Can be passed by value: yes

Name: sort_order
Is passed by reference: yes
Can be passed by value: yes

Name: sort_flags
Is passed by reference: yes
Can be passed by value: yes

Name: arr2
Is passed by reference: yes
Can be passed by value: yes

=> sort:

Name: arg
Is passed by reference: yes
Can be passed by value: no

Name: sort_flags
Is passed by reference: no
Can be passed by value: yes

=> user function:

Name: arg1
Is passed by reference: yes
Can be passed by value: no

Name: arg2
Is passed by reference: no
Can be passed by value: yes

Done.