Check invalid params:

Warning: ReflectionClass::getMethod() expects exactly 1 parameter, 0 given in %s on line 9
NULL

Warning: ReflectionClass::getMethod() expects exactly 1 parameter, 2 given in %s on line 14
NULL
Method  does not exist
Method 1 does not exist
Method 1.5 does not exist
Method 1 does not exist

Warning: ReflectionClass::getMethod() expects parameter 1 to be string, array given in %s on line 39
NULL

Warning: ReflectionClass::getMethod() expects parameter 1 to be string, object given in %s on line 44
NULL