Check invalid params:

Warning: ReflectionClass::getProperty() expects exactly 1 parameter, 0 given in %s on line 9
NULL

Warning: ReflectionClass::getProperty() expects exactly 1 parameter, 2 given in %s on line 14
NULL
Property  does not exist
Property 1 does not exist
Property 1.5 does not exist
Property 1 does not exist

Warning: ReflectionClass::getProperty() expects parameter 1 to be string, array given in %s on line 39
NULL

Warning: ReflectionClass::getProperty() expects parameter 1 to be string, object given in %s on line 44
NULL