string(%d) "%s"

Warning: ReflectionClass::getFileName() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: ReflectionClass::getFileName() expects exactly 0 parameters, 2 given in %s on line %d
NULL
int(2)

Warning: ReflectionClass::getStartLine() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: ReflectionClass::getStartLine() expects exactly 0 parameters, 2 given in %s on line %d
NULL
int(2)

Warning: ReflectionClass::getEndLine() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: ReflectionClass::getEndLine() expects exactly 0 parameters, 2 given in %s on line %d
NULL