Warning: ReflectionClass::getDefaultProperties() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: ReflectionClass::getDefaultProperties() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: ReflectionClass::getDefaultProperties() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: ReflectionClass::getDefaultProperties() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: ReflectionClass::getStaticProperties() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: ReflectionClass::getStaticProperties() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: ReflectionClass::getStaticProperties() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: ReflectionClass::getStaticProperties() expects exactly 0 parameters, 1 given in %s on line %d
NULL