Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; OldCtor has a deprecated constructor in %s on line %d
New-style constructor:
bool(true)

Inherited new-style constructor
bool(true)

Old-style constructor:
bool(true)

Inherited old-style constructor:
bool(true)

Not a constructor:
bool(false)

Inherited method of the same name as the class:
bool(false)

Old-style constructor:
bool(false)

Redefined constructor:
bool(true)

New-style constructor:
bool(true)

Redefined old-style constructor:
bool(false)