Non-existent class:
Class NonExistentClass does not exist

Wrong property parameter type:
The parameter class is expected to be either a string or an object

Non-existent property:
Property TestClass::$nonExistentProperty does not exist

Incorrect number of args:

Warning: ReflectionProperty::export() expects at least 2 parameters, 0 given in %s on line %d

Warning: ReflectionProperty::export() expects at most 3 parameters, 4 given in %s on line %d