Ok - ReflectionProperty::__construct() expects exactly 2 parameters, 0 given
Ok - ReflectionProperty::__construct() expects exactly 2 parameters, 1 given
Ok - ReflectionProperty::__construct() expects exactly 2 parameters, 3 given

Warning: ReflectionProperty::getName() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: ReflectionProperty::isPrivate() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: ReflectionProperty::isProtected() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: ReflectionProperty::isPublic() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: ReflectionProperty::isStatic() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: ReflectionProperty::getModifiers() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: ReflectionProperty::isDefault() expects exactly 0 parameters, 1 given in %s on line %d
NULL