Warning: ReflectionClass::getConstant() expects exactly 1 parameter, 0 given in %s on line 7
NULL

Warning: ReflectionClass::getConstant() expects exactly 1 parameter, 2 given in %s on line 8
NULL
bool(false)
bool(false)
bool(false)
bool(false)

Warning: ReflectionClass::getConstant() expects parameter 1 to be string, array given in %s on line 13
NULL

Warning: ReflectionClass::getConstant() expects parameter 1 to be string, object given in %s on line 14
NULL