Check invalid params:

Warning: ReflectionClass::hasProperty() expects exactly 1 parameter, 0 given in %s on line 8
NULL

Warning: ReflectionClass::hasProperty() expects exactly 1 parameter, 2 given in %s on line 9
NULL
bool(false)
bool(false)
bool(false)
bool(false)

Warning: ReflectionClass::hasProperty() expects parameter 1 to be string, array given in %s on line 14
NULL

Warning: ReflectionClass::hasProperty() expects parameter 1 to be string, object given in %s on line 15
NULL