object(ReflectionClass)#%d (1) {
  ["name"]=>
  string(1) "A"
}
bool(false)

Test bad params:

Warning: ReflectionClass::getParentClass() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: ReflectionClass::getParentClass() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: ReflectionClass::getParentClass() expects exactly 0 parameters, 2 given in %s on line %d
NULL