bool(false)
bool(false)
bool(false)
int(42)
int(-1)

Warning: pcntl_wait() expects at least 1 parameter, 0 given in %s
NULL

Warning: pcntl_waitpid() expects at least 2 parameters, 0 given in %s
NULL

Warning: pcntl_wifexited() expects exactly 1 parameter, 0 given in %s
NULL

Warning: pcntl_wifstopped() expects exactly 1 parameter, 0 given in %s
NULL

Warning: pcntl_wifsignaled() expects exactly 1 parameter, 0 given in %s
NULL

Warning: pcntl_wexitstatus() expects exactly 1 parameter, 0 given in %s
NULL

Warning: pcntl_wtermsig() expects exactly 1 parameter, 0 given in %s
NULL

Warning: pcntl_wstopsig() expects exactly 1 parameter, 0 given in %s
NULL