--> Access the real property:
bool(true)
string(15) "object property"
string(23) "object property.changed"

--> Remove the real property and access the array element:
bool(true)
string(13) "array element"
string(21) "array element.changed"

--> Remove the array element and try access again:
bool(false)

Notice: Undefined index: p in %s on line 10
NULL

Notice: Undefined index: p in %s on line 12
string(8) ".changed"