object(ArrayObject)#2 (1) {
  ["storage":"ArrayObject":private]=>
  object(stdClass)#1 (2) {
    ["b"]=>
    int(1)
    ["a"]=>
    int(2)
  }
}
object(ArrayObject)#3 (1) {
  ["storage":"ArrayObject":private]=>
  object(ArrayObject)#2 (1) {
    ["storage":"ArrayObject":private]=>
    object(stdClass)#1 (2) {
      ["a"]=>
      int(2)
      ["b"]=>
      int(1)
    }
  }
}
object(ArrayObject)#4 (2) {
  ["b"]=>
  int(1)
  ["a"]=>
  int(2)
}
object(ArrayObject)#5 (1) {
  ["storage":"ArrayObject":private]=>
  array(0) {
  }
}
object(ArrayObject)#6 (1) {
  ["storage":"ArrayObject":private]=>
  array(2) {
    ["b"]=>
    int(1)
    ["a"]=>
    int(2)
  }
}