FilterIterator::__construct() expects exactly 1 parameter, 0 given
CachingIterator::__construct() expects at least 1 parameter, 0 given
RecursiveCachingIterator::__construct() expects at least 1 parameter, 0 given
ParentIterator::__construct() expects exactly 1 parameter, 0 given
LimitIterator::__construct() expects at least 1 parameter, 0 given
NoRewindIterator::__construct() expects exactly 1 parameter, 0 given