Warning: SplHeap::extract() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: SplHeap::extract() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: SplHeap::extract() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: SplHeap::extract() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: SplHeap::extract() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: SplHeap::extract() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: SplHeap::extract() expects exactly 0 parameters, 1 given in %s on line %d
NULL