Warning: SplHeap::isEmpty() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: SplHeap::isEmpty() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: SplHeap::isEmpty() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: SplHeap::isEmpty() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: SplHeap::isEmpty() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: SplHeap::isEmpty() expects exactly 0 parameters, 1 given in %s on line %d
NULL

Warning: SplHeap::isEmpty() expects exactly 0 parameters, 1 given in %s on line %d
NULL