*** Testing hash() : error conditions ***

-- Testing hash() function with less than expected no. of arguments --

Warning: hash() expects at least 2 parameters, 0 given in %s on line %d
NULL

Warning: hash() expects at least 2 parameters, 1 given in %s on line %d
NULL

-- Testing hash() function with more than expected no. of arguments --

Warning: hash() expects at most 3 parameters, 4 given in %s on line %d
NULL

-- Testing hash() function with invalid hash algorithm --

Warning: hash(): Unknown hashing algorithm: foo in %s on line %d
bool(false)
===Done===