*** Testing hash_file() : error conditions ***

-- Testing hash_file() function with an unknown algorithm --

Warning: hash_file(): Unknown hashing algorithm: %s in %s on line %d
bool(false)

-- Testing hash_file() function with a non-existent file --

Warning: hash_file(%s): failed to open stream: No such file or directory in %s on line %d
bool(false)

-- Testing hash_file() function with less than expected no. of arguments --

Warning: hash_file() expects at least 2 parameters, 1 given in %s on line %d
NULL

-- Testing hash_file() function with more than expected no. of arguments --

Warning: hash_file() expects at most 3 parameters, 4 given in %s on line %d
NULL
===DONE===