*** Testing hash() : error conditions ***

-- Testing hash_hmac_file() function with less than expected no. of arguments --

Warning: hash_hmac_file() expects at least 3 parameters, 0 given in %s on line %d
NULL

Warning: hash_hmac_file() expects at least 3 parameters, 1 given in %s on line %d
NULL

Warning: hash_hmac_file() expects at least 3 parameters, 2 given in %s on line %d
NULL

-- Testing hash_hmac_file() function with more than expected no. of arguments --

Warning: hash_hmac_file() expects at most 4 parameters, 5 given in %s on line %d

-- Testing hash_hmac_file() function with invalid hash algorithm --

Warning: hash_hmac_file(): Unknown hashing algorithm: foo in %s on line %d

-- Testing hash_hmac_file() function with bad path --

Warning: hash_hmac_file(): Invalid path in %s on line %d
===Done===