string(3) "Foo"
string(6) "FooBar"
string(9) "FooBarBaz"
===ArrayOverloading===
string(3) "Foo"

Notice: Indirect modification of overloaded element of Peoples has no effect in %sarray_access_008.php on line 40
string(3) "Foo"

Notice: Indirect modification of overloaded element of Peoples has no effect in %sarray_access_008.php on line 42
string(3) "Foo"

Notice: Indirect modification of overloaded element of Peoples has no effect in %sarray_access_008.php on line 44
string(3) "Foo"
===DONE===