--> Access visible static prop like instance prop:
bool(false)

Notice: Accessing static property C::$x as non static in %s on line 11

Notice: Accessing static property C::$x as non static in %s on line 12

Notice: Undefined property: C::$x in %s on line 12

Notice: Accessing static property C::$x as non static in %s on line 13

Notice: Accessing static property C::$x as non static in %s on line 15

Notice: Accessing static property C::$x as non static in %s on line 16
%unicode|string%(3) "ref"
%unicode|string%(5) "C::$x"

--> Access non-visible static prop like instance prop:
bool(false)
==Done==