---> Type hints with callback function:
0: Argument 1 passed to f1() must be an instance of A, integer given%s(%d)

in f1;
0: Argument 1 passed to f2() must be an instance of A or null, integer given%s(%d)

in f2;
in f2;
in f2;


---> Type hints with callback static method:
0: Argument 1 passed to C::f1() must be an instance of A, integer given%s(%d)

in C::f1 (static);
0: Argument 1 passed to C::f2() must be an instance of A or null, integer given%s(%d)

in C::f2 (static);
in C::f2 (static);
in C::f2 (static);


---> Type hints with callback instance method:
0: Argument 1 passed to D::f1() must be an instance of A, integer given%s(%d)

in C::f1 (instance);
0: Argument 1 passed to D::f2() must be an instance of A or null, integer given%s(%d)

in C::f2 (instance);
in C::f2 (instance);
in C::f2 (instance);