Within test directory
object(SQLite3)#%d (0) {
}
bool(true)
Above test directory

Warning: SQLite3::__construct(): open_basedir restriction in effect. File(%s) is not within the allowed path(s): (.) in %ssqlite3_21_security.php on line %d
Exception: open_basedir prohibits opening %s in %ssqlite3_21_security.php:%d
Stack trace:
#0 %ssqlite3_21_security.php(%d): SQLite3->__construct('%s')
#1 {main}
Done