------ Calling by_val() with unreferenced argument ------
array(1) {
  [0]=>
  string(8) "original"
}
------ Calling by_ref() with unreferenced argument ------

Warning: Parameter 1 to by_ref() expected to be a reference, value given in %s on line %d
array(1) {
  [0]=>
  string(8) "original"
}
------ Calling by_val() with referenced argument ------
array(1) {
  [0]=>
  &string(8) "original"
}
------ Calling by_ref() with referenced argument ------
array(1) {
  [0]=>
  &string(7) "changed"
}