*** Testing debug_zval_dump() on objects ***
-- Iteration 1 --
object(object_class)#%d (6) refcount(%d){
  ["value1"]=>
  int(5)
  ["value2":"object_class":private]=>
  int(10)
  ["value3":protected]=>
  int(20)
  ["value4"]=>
  int(30)
  ["array_var"]=>
  array(2) refcount(%d){
    ["key1"]=>
    int(1)
    ["key2 "]=>
    int(3)
  }
  ["object_class1"]=>
  object(object_class)#%d (6) refcount(%d){
    ["value1"]=>
    int(5)
    ["value2":"object_class":private]=>
    int(10)
    ["value3":protected]=>
    int(20)
    ["value4"]=>
    int(30)
    ["array_var"]=>
    array(2) refcount(%d){
      ["key1"]=>
      int(1)
      ["key2 "]=>
      int(3)
    }
    ["object_class1"]=>
    *RECURSION*
  }
}
-- Iteration 2 --
object(no_member_class)#%d (0) refcount(%d){
}
-- Iteration 3 --
object(contains_object_class)#%d (9) refcount(%d){
  ["p"]=>
  int(30)
  ["p1":protected]=>
  int(40)
  ["p2":"contains_object_class":private]=>
  int(50)
  ["class_object1"]=>
  object(object_class)#%d (6) refcount(%d){
    ["value1"]=>
    int(5)
    ["value2":"object_class":private]=>
    int(10)
    ["value3":protected]=>
    int(20)
    ["value4"]=>
    int(30)
    ["array_var"]=>
    array(2) refcount(%d){
      ["key1"]=>
      int(1)
      ["key2 "]=>
      int(3)
    }
    ["object_class1"]=>
    object(object_class)#%d (6) refcount(%d){
      ["value1"]=>
      int(5)
      ["value2":"object_class":private]=>
      int(10)
      ["value3":protected]=>
      int(20)
      ["value4"]=>
      int(30)
      ["array_var"]=>
      array(2) refcount(%d){
        ["key1"]=>
        int(1)
        ["key2 "]=>
        int(3)
      }
      ["object_class1"]=>
      *RECURSION*
    }
  }
  ["class_object2"]=>
  object(object_class)#%d (6) refcount(%d){
    ["value1"]=>
    int(5)
    ["value2":"object_class":private]=>
    int(10)
    ["value3":protected]=>
    int(20)
    ["value4"]=>
    int(30)
    ["array_var"]=>
    array(2) refcount(%d){
      ["key1"]=>
      int(1)
      ["key2 "]=>
      int(3)
    }
    ["object_class1"]=>
    object(object_class)#%d (6) refcount(%d){
      ["value1"]=>
      int(5)
      ["value2":"object_class":private]=>
      int(10)
      ["value3":protected]=>
      int(20)
      ["value4"]=>
      int(30)
      ["array_var"]=>
      array(2) refcount(%d){
        ["key1"]=>
        int(1)
        ["key2 "]=>
        int(3)
      }
      ["object_class1"]=>
      *RECURSION*
    }
  }
  ["class_object3":"contains_object_class":private]=>
  object(object_class)#%d (6) refcount(%d){
    ["value1"]=>
    int(5)
    ["value2":"object_class":private]=>
    int(10)
    ["value3":protected]=>
    int(20)
    ["value4"]=>
    int(30)
    ["array_var"]=>
    array(2) refcount(%d){
      ["key1"]=>
      int(1)
      ["key2 "]=>
      int(3)
    }
    ["object_class1"]=>
    object(object_class)#%d (6) refcount(%d){
      ["value1"]=>
      int(5)
      ["value2":"object_class":private]=>
      int(10)
      ["value3":protected]=>
      int(20)
      ["value4"]=>
      int(30)
      ["array_var"]=>
      array(2) refcount(%d){
        ["key1"]=>
        int(1)
        ["key2 "]=>
        int(3)
      }
      ["object_class1"]=>
      *RECURSION*
    }
  }
  ["class_object4":protected]=>
  object(object_class)#%d (6) refcount(%d){
    ["value1"]=>
    int(5)
    ["value2":"object_class":private]=>
    int(10)
    ["value3":protected]=>
    int(20)
    ["value4"]=>
    int(30)
    ["array_var"]=>
    array(2) refcount(%d){
      ["key1"]=>
      int(1)
      ["key2 "]=>
      int(3)
    }
    ["object_class1"]=>
    object(object_class)#%d (6) refcount(%d){
      ["value1"]=>
      int(5)
      ["value2":"object_class":private]=>
      int(10)
      ["value3":protected]=>
      int(20)
      ["value4"]=>
      int(30)
      ["array_var"]=>
      array(2) refcount(%d){
        ["key1"]=>
        int(1)
        ["key2 "]=>
        int(3)
      }
      ["object_class1"]=>
      *RECURSION*
    }
  }
  ["no_member_class_object"]=>
  object(no_member_class)#%d (0) refcount(%d){
  }
  ["class_object5"]=>
  object(contains_object_class)#%d (9) refcount(%d){
    ["p"]=>
    int(30)
    ["p1":protected]=>
    int(40)
    ["p2":"contains_object_class":private]=>
    int(50)
    ["class_object1"]=>
    object(object_class)#%d (6) refcount(%d){
      ["value1"]=>
      int(5)
      ["value2":"object_class":private]=>
      int(10)
      ["value3":protected]=>
      int(20)
      ["value4"]=>
      int(30)
      ["array_var"]=>
      array(2) refcount(%d){
        ["key1"]=>
        int(1)
        ["key2 "]=>
        int(3)
      }
      ["object_class1"]=>
      object(object_class)#%d (6) refcount(%d){
        ["value1"]=>
        int(5)
        ["value2":"object_class":private]=>
        int(10)
        ["value3":protected]=>
        int(20)
        ["value4"]=>
        int(30)
        ["array_var"]=>
        array(2) refcount(%d){
          ["key1"]=>
          int(1)
          ["key2 "]=>
          int(3)
        }
        ["object_class1"]=>
        *RECURSION*
      }
    }
    ["class_object2"]=>
    object(object_class)#%d (6) refcount(%d){
      ["value1"]=>
      int(5)
      ["value2":"object_class":private]=>
      int(10)
      ["value3":protected]=>
      int(20)
      ["value4"]=>
      int(30)
      ["array_var"]=>
      array(2) refcount(%d){
        ["key1"]=>
        int(1)
        ["key2 "]=>
        int(3)
      }
      ["object_class1"]=>
      object(object_class)#%d (6) refcount(%d){
        ["value1"]=>
        int(5)
        ["value2":"object_class":private]=>
        int(10)
        ["value3":protected]=>
        int(20)
        ["value4"]=>
        int(30)
        ["array_var"]=>
        array(2) refcount(%d){
          ["key1"]=>
          int(1)
          ["key2 "]=>
          int(3)
        }
        ["object_class1"]=>
        *RECURSION*
      }
    }
    ["class_object3":"contains_object_class":private]=>
    object(object_class)#%d (6) refcount(%d){
      ["value1"]=>
      int(5)
      ["value2":"object_class":private]=>
      int(10)
      ["value3":protected]=>
      int(20)
      ["value4"]=>
      int(30)
      ["array_var"]=>
      array(2) refcount(%d){
        ["key1"]=>
        int(1)
        ["key2 "]=>
        int(3)
      }
      ["object_class1"]=>
      object(object_class)#%d (6) refcount(%d){
        ["value1"]=>
        int(5)
        ["value2":"object_class":private]=>
        int(10)
        ["value3":protected]=>
        int(20)
        ["value4"]=>
        int(30)
        ["array_var"]=>
        array(2) refcount(%d){
          ["key1"]=>
          int(1)
          ["key2 "]=>
          int(3)
        }
        ["object_class1"]=>
        *RECURSION*
      }
    }
    ["class_object4":protected]=>
    object(object_class)#%d (6) refcount(%d){
      ["value1"]=>
      int(5)
      ["value2":"object_class":private]=>
      int(10)
      ["value3":protected]=>
      int(20)
      ["value4"]=>
      int(30)
      ["array_var"]=>
      array(2) refcount(%d){
        ["key1"]=>
        int(1)
        ["key2 "]=>
        int(3)
      }
      ["object_class1"]=>
      object(object_class)#%d (6) refcount(%d){
        ["value1"]=>
        int(5)
        ["value2":"object_class":private]=>
        int(10)
        ["value3":protected]=>
        int(20)
        ["value4"]=>
        int(30)
        ["array_var"]=>
        array(2) refcount(%d){
          ["key1"]=>
          int(1)
          ["key2 "]=>
          int(3)
        }
        ["object_class1"]=>
        *RECURSION*
      }
    }
    ["no_member_class_object"]=>
    object(no_member_class)#%d (0) refcount(%d){
    }
    ["class_object5"]=>
    *RECURSION*
  }
}
-- Iteration 4 --
object(object_class)#%d (6) refcount(%d){
  ["value1"]=>
  int(5)
  ["value2":"object_class":private]=>
  int(10)
  ["value3":protected]=>
  int(20)
  ["value4"]=>
  int(30)
  ["array_var"]=>
  array(2) refcount(%d){
    ["key1"]=>
    int(1)
    ["key2 "]=>
    int(3)
  }
  ["object_class1"]=>
  object(object_class)#%d (6) refcount(%d){
    ["value1"]=>
    int(5)
    ["value2":"object_class":private]=>
    int(10)
    ["value3":protected]=>
    int(20)
    ["value4"]=>
    int(30)
    ["array_var"]=>
    array(2) refcount(%d){
      ["key1"]=>
      int(1)
      ["key2 "]=>
      int(3)
    }
    ["object_class1"]=>
    *RECURSION*
  }
}
-- Iteration 5 --
object(object_class)#%d (6) refcount(%d){
  ["value1"]=>
  int(5)
  ["value2":"object_class":private]=>
  int(10)
  ["value3":protected]=>
  int(20)
  ["value4"]=>
  int(30)
  ["array_var"]=>
  array(2) refcount(%d){
    ["key1"]=>
    int(1)
    ["key2 "]=>
    int(3)
  }
  ["object_class1"]=>
  object(object_class)#%d (6) refcount(%d){
    ["value1"]=>
    int(5)
    ["value2":"object_class":private]=>
    int(10)
    ["value3":protected]=>
    int(20)
    ["value4"]=>
    int(30)
    ["array_var"]=>
    array(2) refcount(%d){
      ["key1"]=>
      int(1)
      ["key2 "]=>
      int(3)
    }
    ["object_class1"]=>
    *RECURSION*
  }
}
-- Iteration 6 --
object(no_member_class)#%d (0) refcount(%d){
}
-- Iteration 7 --
NULL
-- Iteration 8 --
object(object_class)#%d (6) refcount(%d){
  ["value1"]=>
  int(5)
  ["value2":"object_class":private]=>
  int(10)
  ["value3":protected]=>
  int(20)
  ["value4"]=>
  int(30)
  ["array_var"]=>
  array(2) refcount(%d){
    ["key1"]=>
    int(1)
    ["key2 "]=>
    int(3)
  }
  ["object_class1"]=>
  object(object_class)#%d (6) refcount(%d){
    ["value1"]=>
    int(5)
    ["value2":"object_class":private]=>
    int(10)
    ["value3":protected]=>
    int(20)
    ["value4"]=>
    int(30)
    ["array_var"]=>
    array(2) refcount(%d){
      ["key1"]=>
      int(1)
      ["key2 "]=>
      int(3)
    }
    ["object_class1"]=>
    *RECURSION*
  }
}
-- Iteration 9 --
object(object_class)#%d (6) refcount(%d){
  ["value1"]=>
  int(5)
  ["value2":"object_class":private]=>
  int(10)
  ["value3":protected]=>
  int(20)
  ["value4"]=>
  int(30)
  ["array_var"]=>
  array(2) refcount(%d){
    ["key1"]=>
    int(1)
    ["key2 "]=>
    int(3)
  }
  ["object_class1"]=>
  object(object_class)#%d (6) refcount(%d){
    ["value1"]=>
    int(5)
    ["value2":"object_class":private]=>
    int(10)
    ["value3":protected]=>
    int(20)
    ["value4"]=>
    int(30)
    ["array_var"]=>
    array(2) refcount(%d){
      ["key1"]=>
      int(1)
      ["key2 "]=>
      int(3)
    }
    ["object_class1"]=>
    *RECURSION*
  }
}
-- Iteration 10 --
int(30)
-- Iteration 11 --
NULL

-- Testing debug_zval_dump() on overwritten object variables --
int(500)
int(500)
int(500)
int(500)

-- Testing debug_zval_dump() on objects having circular reference --
object(object_class)#%d (7) refcount(%d){
  ["value1"]=>
  int(5)
  ["value2":"object_class":private]=>
  int(10)
  ["value3":protected]=>
  int(20)
  ["value4"]=>
  int(30)
  ["array_var"]=>
  array(2) refcount(%d){
    ["key1"]=>
    int(1)
    ["key2 "]=>
    int(3)
  }
  ["object_class1"]=>
  object(object_class)#%d (7) refcount(%d){
    ["value1"]=>
    int(5)
    ["value2":"object_class":private]=>
    int(10)
    ["value3":protected]=>
    int(20)
    ["value4"]=>
    int(30)
    ["array_var"]=>
    array(2) refcount(%d){
      ["key1"]=>
      int(1)
      ["key2 "]=>
      int(3)
    }
    ["object_class1"]=>
    *RECURSION*
    ["obj"]=>
    &object(object_class)#%d (7) refcount(%d){
      ["value1"]=>
      int(5)
      ["value2":"object_class":private]=>
      int(10)
      ["value3":protected]=>
      int(20)
      ["value4"]=>
      int(30)
      ["array_var"]=>
      array(2) refcount(%d){
        ["key1"]=>
        int(1)
        ["key2 "]=>
        int(3)
      }
      ["object_class1"]=>
      object(object_class)#%d (7) refcount(%d){
        ["value1"]=>
        int(5)
        ["value2":"object_class":private]=>
        int(10)
        ["value3":protected]=>
        int(20)
        ["value4"]=>
        int(30)
        ["array_var"]=>
        array(2) refcount(%d){
          ["key1"]=>
          int(1)
          ["key2 "]=>
          int(3)
        }
        ["object_class1"]=>
        *RECURSION*
        ["obj"]=>
        *RECURSION*
      }
      ["obj"]=>
      *RECURSION*
    }
  }
  ["obj"]=>
  &object(object_class)#%d (7) refcount(%d){
    ["value1"]=>
    int(5)
    ["value2":"object_class":private]=>
    int(10)
    ["value3":protected]=>
    int(20)
    ["value4"]=>
    int(30)
    ["array_var"]=>
    array(2) refcount(%d){
      ["key1"]=>
      int(1)
      ["key2 "]=>
      int(3)
    }
    ["object_class1"]=>
    object(object_class)#%d (7) refcount(%d){
      ["value1"]=>
      int(5)
      ["value2":"object_class":private]=>
      int(10)
      ["value3":protected]=>
      int(20)
      ["value4"]=>
      int(30)
      ["array_var"]=>
      array(2) refcount(%d){
        ["key1"]=>
        int(1)
        ["key2 "]=>
        int(3)
      }
      ["object_class1"]=>
      *RECURSION*
      ["obj"]=>
      &object(object_class)#%d (7) refcount(%d){
        ["value1"]=>
        int(5)
        ["value2":"object_class":private]=>
        int(10)
        ["value3":protected]=>
        int(20)
        ["value4"]=>
        int(30)
        ["array_var"]=>
        array(2) refcount(%d){
          ["key1"]=>
          int(1)
          ["key2 "]=>
          int(3)
        }
        ["object_class1"]=>
        *RECURSION*
        ["obj"]=>
        *RECURSION*
      }
    }
    ["obj"]=>
    &object(object_class)#%d (7) refcount(%d){
      ["value1"]=>
      int(5)
      ["value2":"object_class":private]=>
      int(10)
      ["value3":protected]=>
      int(20)
      ["value4"]=>
      int(30)
      ["array_var"]=>
      array(2) refcount(%d){
        ["key1"]=>
        int(1)
        ["key2 "]=>
        int(3)
      }
      ["object_class1"]=>
      *RECURSION*
      ["obj"]=>
      &object(object_class)#%d (7) refcount(%d){
        ["value1"]=>
        int(5)
        ["value2":"object_class":private]=>
        int(10)
        ["value3":protected]=>
        int(20)
        ["value4"]=>
        int(30)
        ["array_var"]=>
        array(2) refcount(%d){
          ["key1"]=>
          int(1)
          ["key2 "]=>
          int(3)
        }
        ["object_class1"]=>
        *RECURSION*
        ["obj"]=>
        *RECURSION*
      }
    }
  }
}
Done