*** Testing escapeshellarg() : error conditions ***

-- Testing escapeshellarg() function with no arguments --

Warning: escapeshellarg() expects exactly 1 parameter, 0 given in %s on line %d
NULL

-- Testing escapeshellarg() function with more than expected no. of arguments --

Warning: escapeshellarg() expects exactly 1 parameter, 2 given in %s on line %d
NULL

-- Testing escapeshellarg() function with a object supplied for argument --

Warning: escapeshellarg() expects parameter 1 to be string, object given in %s on line %d
NULL

-- Testing escapeshellarg() function with a resource supplied for argument --

Warning: escapeshellarg() expects parameter 1 to be string, resource given in %s on line %d
NULL

-- Testing escapeshellarg() function with a array supplied for argument --

Warning: escapeshellarg() expects parameter 1 to be string, array given in %s on line %d
NULL
===Done===