*** Testing floatval() and doubleval() : error conditions ***

-- Testing floatval() and doubleval() function with no arguments --

Warning: floatval() expects exactly 1 parameter, 0 given in %s on line %d
NULL

Warning: doubleval() expects exactly 1 parameter, 0 given in %s on line %d
NULL

-- Testing floatval() and doubleval() function with more than expected no. of arguments --

Warning: floatval() expects exactly 1 parameter, 2 given in %s on line %d
NULL

Warning: doubleval() expects exactly 1 parameter, 2 given in %s on line %d
NULL
===DONE===