*** Test substituting argument 1 with array values ***

Warning: getservbyname() expects parameter 1 to be string, array given in %s on line %d
NULL

Warning: getservbyname() expects parameter 1 to be string, array given in %s on line %d
NULL

Warning: getservbyname() expects parameter 1 to be string, array given in %s on line %d
NULL

Warning: getservbyname() expects parameter 1 to be string, array given in %s on line %d
NULL