*** Test substituting argument 2 with array values ***

Warning: getservbyname() expects parameter 2 to be string, array given in %s on line %d
NULL

Warning: getservbyname() expects parameter 2 to be string, array given in %s on line %d
NULL

Warning: getservbyname() expects parameter 2 to be string, array given in %s on line %d
NULL

Warning: getservbyname() expects parameter 2 to be string, array given in %s on line %d
NULL