**** Testing gettype() and settype() functions ****

*** Testing gettype(): error conditions ***

Warning: gettype() expects exactly 1 parameter, 0 given in %s on line %d
NULL

Warning: gettype() expects exactly 1 parameter, 2 given in %s on line %d
NULL

*** Testing settype(): error conditions ***

Warning: settype() expects exactly 2 parameters, 0 given in %s on line %d
NULL

Warning: settype() expects exactly 2 parameters, 3 given in %s on line %d
NULL

Warning: settype(): Invalid type in %s on line %d
bool(false)
Done