string(5) "array"

Warning: ini_get_all(): Unable to find extension '' in %s on line %d
bool(false)

Warning: ini_get_all(): Unable to find extension 'nosuchextension' in %s on line %d
bool(false)
array(0) {
}
array(3) {
  ["pcre.backtrack_limit"]=>
  array(3) {
    ["global_value"]=>
    string(7) "1000000"
    ["local_value"]=>
    string(7) "1000000"
    ["access"]=>
    int(7)
  }
  ["pcre.jit"]=>
  array(3) {
    ["global_value"]=>
    string(1) "1"
    ["local_value"]=>
    string(1) "1"
    ["access"]=>
    int(7)
  }
  ["pcre.recursion_limit"]=>
  array(3) {
    ["global_value"]=>
    string(6) "100000"
    ["local_value"]=>
    string(6) "100000"
    ["access"]=>
    int(7)
  }
}
array(3) {
  ["pcre.backtrack_limit"]=>
  string(7) "1000000"
  ["pcre.jit"]=>
  string(1) "1"
  ["pcre.recursion_limit"]=>
  string(6) "100000"
}
array(0) {
}

Warning: ini_get_all(): Unable to find extension '' in %sini_get_all.php on line %d
bool(false)
Done