*** Testing php_uname() - error test

-- Testing php_uname() function with more than expected no. of arguments --

Warning: php_uname() expects at most 1 parameter, 2 given in %s on line %d
NULL

-- Testing php_uname() function with invalid mode --
bool(true)

-- Testing php_uname() function with invalid argument types --

Warning: php_uname() expects parameter 1 to be string, array given in %s on line %d
NULL

Warning: php_uname() expects parameter 1 to be string, array given in %s on line %d
NULL

Warning: php_uname() expects parameter 1 to be string, object given in %s on line %d
NULL

Warning: php_uname() expects parameter 1 to be string, resource given in %s on line %d
NULL
===DONE===