*** Test substituting argument 1 with string values ***

Warning: proc_nice() expects parameter 1 to be integer, string given in %s on line %d
bool(false)

Warning: proc_nice() expects parameter 1 to be integer, string given in %s on line %d
bool(false)

Warning: proc_nice() expects parameter 1 to be integer, string given in %s on line %d
bool(false)

Warning: proc_nice() expects parameter 1 to be integer, string given in %s on line %d
bool(false)