*** Test substituting argument 1 with array values ***

Warning: proc_nice() expects parameter 1 to be integer, array given in %s on line %d
bool(false)

Warning: proc_nice() expects parameter 1 to be integer, array given in %s on line %d
bool(false)

Warning: proc_nice() expects parameter 1 to be integer, array given in %s on line %d
bool(false)

Warning: proc_nice() expects parameter 1 to be integer, array given in %s on line %d
bool(false)