*** Testing sleep() : error conditions ***

-- Testing sleep() function with zero arguments --

Warning: sleep() expects exactly 1 parameter, 0 given in %s on line %d
bool(false)

-- Testing sleep() function with more than expected no. of arguments --

Warning: sleep() expects exactly 1 parameter, 2 given in %s on line %d
bool(false)

-- Testing sleep() function with negative interval --

Warning: sleep(): Number of seconds must be greater than or equal to 0 in %s on line %d
bool(false)
===DONE===