*** Testing uniqid() : error conditions ***

-- Testing uniqid() function with more than expected no. of arguments --

Warning: uniqid() expects at most 2 parameters, 3 given in %s on line %d
NULL

-- Testing uniqid() function with invalid values for $prefix --

Warning: uniqid() expects parameter 1 to be string, array given in %s on line %d

Warning: uniqid() expects parameter 1 to be string, resource given in %s on line %d

Warning: uniqid() expects parameter 1 to be string, object given in %s on line %d
===DONE===