*** Testing usleep() : error conditions ***

-- Testing usleep() function with zero arguments --

Warning: usleep() expects exactly 1 parameter, 0 given in %s on line %d
NULL

-- Testing usleep() function with more than expected no. of arguments --

Warning: usleep() expects exactly 1 parameter, 2 given in %s on line %d
NULL

-- Testing usleep() function with negative interval --

Warning: usleep(): Number of microseconds must be greater than or equal to 0 in %s on line %d
bool(false)
===DONE===