*** Testing array_fill() : usage variations ***
--- Testing array_fill() with different values for 'start_key' arg ---
-- Iteration 1 --
array(2) {
  [10]=>
  int(100)
  [11]=>
  int(100)
}
-- Iteration 2 --
array(2) {
  [-10]=>
  int(100)
  [0]=>
  int(100)
}
-- Iteration 3 --
array(2) {
  [123456789000]=>
  int(100)
  [123456789001]=>
  int(100)
}
-- Iteration 4 --
array(2) {
  [0]=>
  int(100)
  [1]=>
  int(100)
}
-- Iteration 5 --
array(2) {
  [0]=>
  int(100)
  [1]=>
  int(100)
}
-- Iteration 6 --

Warning: array_fill() expects parameter 1 to be integer, array given in %s on line %d
NULL
-- Iteration 7 --

Warning: array_fill() expects parameter 1 to be integer, array given in %s on line %d
NULL
-- Iteration 8 --

Warning: array_fill() expects parameter 1 to be integer, array given in %s on line %d
NULL
-- Iteration 9 --

Warning: array_fill() expects parameter 1 to be integer, array given in %s on line %d
NULL
-- Iteration 10 --

Warning: array_fill() expects parameter 1 to be integer, array given in %s on line %d
NULL
-- Iteration 11 --
array(2) {
  [0]=>
  int(100)
  [1]=>
  int(100)
}
-- Iteration 12 --
array(2) {
  [0]=>
  int(100)
  [1]=>
  int(100)
}
-- Iteration 13 --
array(2) {
  [1]=>
  int(100)
  [2]=>
  int(100)
}
-- Iteration 14 --
array(2) {
  [0]=>
  int(100)
  [1]=>
  int(100)
}
-- Iteration 15 --
array(2) {
  [1]=>
  int(100)
  [2]=>
  int(100)
}
-- Iteration 16 --
array(2) {
  [0]=>
  int(100)
  [1]=>
  int(100)
}
-- Iteration 17 --

Warning: array_fill() expects parameter 1 to be integer, string given in %s on line %d
NULL
-- Iteration 18 --

Warning: array_fill() expects parameter 1 to be integer, string given in %s on line %d
NULL
-- Iteration 19 --

Warning: array_fill() expects parameter 1 to be integer, string given in %s on line %d
NULL
-- Iteration 20 --

Warning: array_fill() expects parameter 1 to be integer, string given in %s on line %d
NULL
-- Iteration 21 --

Warning: array_fill() expects parameter 1 to be integer, object given in %s on line %d
NULL
-- Iteration 22 --
array(2) {
  [0]=>
  int(100)
  [1]=>
  int(100)
}
-- Iteration 23 --
array(2) {
  [0]=>
  int(100)
  [1]=>
  int(100)
}
-- Iteration 24 --

Warning: array_fill() expects parameter 1 to be integer, resource given in %s on line %d
NULL
Done