*** Testing array_pad() : passing non integer values to $pad_size argument ***
-- Iteration 1 --
array(10) {
  [0]=>
  int(1)
  [1]=>
  int(2)
  [2]=>
  int(1)
  [3]=>
  int(1)
  [4]=>
  int(1)
  [5]=>
  int(1)
  [6]=>
  int(1)
  [7]=>
  int(1)
  [8]=>
  int(1)
  [9]=>
  int(1)
}
-- Iteration 2 --
array(10) {
  [0]=>
  int(1)
  [1]=>
  int(1)
  [2]=>
  int(1)
  [3]=>
  int(1)
  [4]=>
  int(1)
  [5]=>
  int(1)
  [6]=>
  int(1)
  [7]=>
  int(1)
  [8]=>
  int(1)
  [9]=>
  int(2)
}
-- Iteration 3 --

Warning: array_pad(): You may only pad up to 1048576 elements at a time in %s on line %d
bool(false)
-- Iteration 4 --

Warning: array_pad(): You may only pad up to 1048576 elements at a time in %s on line %d
bool(false)
-- Iteration 5 --
array(2) {
  [0]=>
  int(1)
  [1]=>
  int(2)
}
-- Iteration 6 --
array(2) {
  [0]=>
  int(1)
  [1]=>
  int(2)
}
-- Iteration 7 --

Warning: array_pad() expects parameter 2 to be integer, array given in %s on line %d
NULL
-- Iteration 8 --

Warning: array_pad() expects parameter 2 to be integer, array given in %s on line %d
NULL
-- Iteration 9 --

Warning: array_pad() expects parameter 2 to be integer, array given in %s on line %d
NULL
-- Iteration 10 --

Warning: array_pad() expects parameter 2 to be integer, array given in %s on line %d
NULL
-- Iteration 11 --

Warning: array_pad() expects parameter 2 to be integer, array given in %s on line %d
NULL
-- Iteration 12 --
array(2) {
  [0]=>
  int(1)
  [1]=>
  int(2)
}
-- Iteration 13 --
array(2) {
  [0]=>
  int(1)
  [1]=>
  int(2)
}
-- Iteration 14 --
array(2) {
  [0]=>
  int(1)
  [1]=>
  int(2)
}
-- Iteration 15 --
array(2) {
  [0]=>
  int(1)
  [1]=>
  int(2)
}
-- Iteration 16 --
array(2) {
  [0]=>
  int(1)
  [1]=>
  int(2)
}
-- Iteration 17 --
array(2) {
  [0]=>
  int(1)
  [1]=>
  int(2)
}
-- Iteration 18 --

Warning: array_pad() expects parameter 2 to be integer, string given in %s on line %d
NULL
-- Iteration 19 --

Warning: array_pad() expects parameter 2 to be integer, string given in %s on line %d
NULL
-- Iteration 20 --

Warning: array_pad() expects parameter 2 to be integer, string given in %s on line %d
NULL
-- Iteration 21 --

Warning: array_pad() expects parameter 2 to be integer, string given in %s on line %d
NULL
-- Iteration 22 --

Warning: array_pad() expects parameter 2 to be integer, object given in %s on line %d
NULL
-- Iteration 23 --
array(2) {
  [0]=>
  int(1)
  [1]=>
  int(2)
}
-- Iteration 24 --
array(2) {
  [0]=>
  int(1)
  [1]=>
  int(2)
}
Done