*** Testing array_column() : error conditions ***

-- Testing array_column() function with Zero arguments --

Warning: array_column() expects at least 2 parameters, 0 given in %s on line %d
NULL

-- Testing array_column() function with One argument --

Warning: array_column() expects at least 2 parameters, 1 given in %s on line %d
NULL

-- Testing array_column() function with string as first parameter --

Warning: array_column() expects parameter 1 to be array, string given in %s on line %d
NULL

-- Testing array_column() function with int as first parameter --

Warning: array_column() expects parameter 1 to be array, integer given in %s on line %d
NULL

-- Testing array_column() column key parameter should be a string or an integer (testing bool) --

Warning: array_column(): The column key should be either a string or an integer in %s on line %d
bool(false)

-- Testing array_column() column key parameter should be a string or integer (testing array) --

Warning: array_column(): The column key should be either a string or an integer in %s on line %d
bool(false)

-- Testing array_column() index key parameter should be a string or an integer (testing bool) --

Warning: array_column(): The index key should be either a string or an integer in %s on line %d
bool(false)

-- Testing array_column() index key parameter should be a string or integer (testing array) --

Warning: array_column(): The index key should be either a string or an integer in %s on line %d
bool(false)
Done