*** Testing array_rand() : unexpected values for 'num_req' parameter ***

-- Iteration 1 --

Warning: array_rand(): Second argument has to be between 1 and the number of elements in the array in %s on line %d
NULL

-- Iteration 2 --
int(%d)

-- Iteration 3 --

Warning: array_rand(): Second argument has to be between 1 and the number of elements in the array in %s on line %d
NULL

-- Iteration 4 --

Warning: array_rand(): Second argument has to be between 1 and the number of elements in the array in %s on line %d
NULL

-- Iteration 5 --
array(10) {
  [0]=>
  int(%d)
  [1]=>
  int(%d)
  [2]=>
  int(%d)
  [3]=>
  int(%d)
  [4]=>
  int(%d)
  [5]=>
  int(%d)
  [6]=>
  int(%d)
  [7]=>
  int(%d)
  [8]=>
  int(%d)
  [9]=>
  int(%d)
}

-- Iteration 6 --

Warning: array_rand(): Second argument has to be between 1 and the number of elements in the array in %s on line %d
NULL

-- Iteration 7 --

Warning: array_rand(): Second argument has to be between 1 and the number of elements in the array in %s on line %d
NULL

-- Iteration 8 --

Warning: array_rand(): Second argument has to be between 1 and the number of elements in the array in %s on line %d
NULL

-- Iteration 9 --

Warning: array_rand(): Second argument has to be between 1 and the number of elements in the array in %s on line %d
NULL

-- Iteration 10 --

Warning: array_rand(): Second argument has to be between 1 and the number of elements in the array in %s on line %d
NULL

-- Iteration 11 --

Warning: array_rand(): Second argument has to be between 1 and the number of elements in the array in %s on line %d
NULL

-- Iteration 12 --
int(%d)

-- Iteration 13 --

Warning: array_rand(): Second argument has to be between 1 and the number of elements in the array in %s on line %d
NULL

-- Iteration 14 --
int(%d)

-- Iteration 15 --

Warning: array_rand(): Second argument has to be between 1 and the number of elements in the array in %s on line %d
NULL

-- Iteration 16 --

Warning: array_rand() expects parameter 2 to be integer, string given in %s on line %d
NULL

-- Iteration 17 --

Warning: array_rand() expects parameter 2 to be integer, string given in %s on line %d
NULL

-- Iteration 18 --

Warning: array_rand() expects parameter 2 to be integer, string given in %s on line %d
NULL

-- Iteration 19 --

Warning: array_rand() expects parameter 2 to be integer, string given in %s on line %d
NULL

-- Iteration 20 --

Warning: array_rand() expects parameter 2 to be integer, object given in %s on line %d
NULL

-- Iteration 21 --

Warning: array_rand(): Second argument has to be between 1 and the number of elements in the array in %s on line %d
NULL

-- Iteration 22 --

Warning: array_rand(): Second argument has to be between 1 and the number of elements in the array in %s on line %d
NULL
Done