*** Testing basic functionalities ***
-- Iteration 1 --
bool(true)
-- Iteration 2 --
bool(false)
-- Iteration 3 --
bool(true)
-- Iteration 4 --
bool(false)
-- Iteration 5 --
bool(true)
-- Iteration 6 --
bool(true)
-- Iteration 7 --
bool(true)
-- Iteration 8 --
bool(true)

*** Testing possible variations ***

** Variation loop 1 **
-- Iteration 1 --
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(true)
-- Iteration 2 --
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(true)
-- Iteration 3 --
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(true)
-- Iteration 4 --
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(true)
-- Iteration 5 --
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
-- Iteration 6 --
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
-- Iteration 7 --
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(true)
-- Iteration 8 --
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(true)

** Variation loop 2 **
-- Iteration 1 --
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
-- Iteration 2 --
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
-- Iteration 3 --
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(true)
-- Iteration 4 --
bool(true)
bool(true)
bool(true)
bool(false)
bool(true)
bool(false)
bool(true)
-- Iteration 5 --
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(true)

*** Testing error conditions ***

Warning: array_key_exists() expects exactly 2 parameters, 0 given in %s on line %d
NULL

Warning: array_key_exists(): The first argument should be either a string or an integer in %s on line %d
bool(false)

Warning: array_key_exists() expects parameter 2 to be array, string given in %s on line %d
NULL

Warning: array_key_exists() expects parameter 2 to be array, integer given in %s on line %d
NULL

Warning: array_key_exists() expects parameter 2 to be array, null given in %s on line %d
NULL

Warning: array_key_exists() expects parameter 2 to be array, boolean given in %s on line %d
NULL

Warning: array_key_exists() expects parameter 2 to be array, boolean given in %s on line %d
NULL

Warning: array_key_exists() expects parameter 2 to be array, float given in %s on line %d
NULL

Warning: array_key_exists() expects exactly 2 parameters, 3 given in %s on line %d
NULL

Warning: array_key_exists(): The first argument should be either a string or an integer in %s on line %d
bool(false)

*** Testing operation on objects ***
bool(false)
bool(false)
bool(true)
bool(false)
bool(true)
bool(true)

Warning: array_key_exists(): The first argument should be either a string or an integer in %s on line %d
bool(false)
Done