*** Testing array_multisort() : error conditions ***

-- Testing array_multisort() function with Zero arguments --

Warning: array_multisort() expects at least 1 parameter, 0 given in %sarray_multisort_error.php on line %d
NULL

-- Testing array_multisort() function with repeated flags --

Warning: array_multisort(): Argument #3 is expected to be an array or sorting flag that has not already been specified in %sarray_multisort_error.php on line %d
bool(false)

-- Testing array_multisort() function with repeated flags --

Warning: array_multisort(): Argument #3 is expected to be an array or sorting flag that has not already been specified in %sarray_multisort_error.php on line %d
bool(false)
===DONE===