Warning: array_count_values(): Can only count STRING and INTEGER values! in %s on line %s

Warning: array_count_values(): Can only count STRING and INTEGER values! in %s on line %s

Warning: array_count_values(): Can only count STRING and INTEGER values! in %s on line %s
array(8) {
  [1]=>
  int(2)
  ["hello"]=>
  int(2)
  ["world"]=>
  int(1)
  [""]=>
  int(1)
  ["rabbit"]=>
  int(1)
  ["foo"]=>
  int(1)
  ["Foo"]=>
  int(1)
  [0]=>
  int(1)
}