*** Testing error conditions ***

Warning: array_values() expects exactly 1 parameter, 0 given in %s on line %d
NULL

Warning: array_values() expects exactly 1 parameter, 2 given in %s on line %d
NULL

Warning: array_values() expects parameter 1 to be array, string given in %s on line %d
NULL

Warning: array_values() expects parameter 1 to be array, integer given in %s on line %d
NULL

Warning: array_values() expects parameter 1 to be array, object given in %s on line %d
NULL
Done