*** Testing array_key_exists() : usage variations ***

-- Iteration 1 --
bool(true)

-- Iteration 2 --
bool(true)

-- Iteration 3 --
bool(false)

-- Iteration 4 --
bool(false)

-- Iteration 5 --

Warning: array_key_exists(): The first argument should be either a string or an integer in %s on line %d
bool(false)

-- Iteration 6 --

Warning: array_key_exists(): The first argument should be either a string or an integer in %s on line %d
bool(false)

-- Iteration 7 --

Warning: array_key_exists(): The first argument should be either a string or an integer in %s on line %d
bool(false)

-- Iteration 8 --

Warning: array_key_exists(): The first argument should be either a string or an integer in %s on line %d
bool(false)

-- Iteration 9 --

Warning: array_key_exists(): The first argument should be either a string or an integer in %s on line %d
bool(false)

-- Iteration 10 --
bool(false)

-- Iteration 11 --
bool(false)

-- Iteration 12 --

Warning: array_key_exists(): The first argument should be either a string or an integer in %s on line %d
bool(false)

-- Iteration 13 --

Warning: array_key_exists(): The first argument should be either a string or an integer in %s on line %d
bool(false)

-- Iteration 14 --

Warning: array_key_exists(): The first argument should be either a string or an integer in %s on line %d
bool(false)

-- Iteration 15 --

Warning: array_key_exists(): The first argument should be either a string or an integer in %s on line %d
bool(false)

-- Iteration 16 --
bool(false)

-- Iteration 17 --
bool(false)

-- Iteration 18 --

Warning: array_key_exists(): The first argument should be either a string or an integer in %s on line %d
bool(false)

-- Iteration 19 --
bool(true)

-- Iteration 20 --
bool(true)

-- Iteration 21 --
bool(true)

-- Iteration 22 --

Warning: array_key_exists(): The first argument should be either a string or an integer in %s on line %d
bool(false)

-- Iteration 23 --
bool(false)

-- Iteration 24 --
bool(false)

-- Iteration 25 --

Warning: array_key_exists(): The first argument should be either a string or an integer in %s on line %d
bool(false)
Done