Warning: array_walk() expects at least 2 parameters, 0 given in %s on line %d
NULL

Warning: array_walk() expects parameter 1 to be array, integer given in %s on line %d
NULL

Warning: array_walk() expects parameter 2 to be a valid callback, function '' not found or invalid function name in %s on line %d
NULL
int(1)
int(0)
string(4) "data"
int(2)
int(1)
string(4) "data"
bool(true)
string(4) "data"
Done