*** Testing array_uintersect_assoc() : error conditions ***

-- Testing array_uintersect_assoc() function with more than expected no. of arguments --

Warning: array_uintersect_assoc() expects parameter 4 to be a valid callback, no array or string given in %sarray_uintersect_assoc_error.php on line %d
NULL

-- Testing array_uintersect_assoc() function with less than expected no. of arguments --

Warning: array_uintersect_assoc(): at least 3 parameters are required, 2 given in %sarray_uintersect_assoc_error.php on line %d
NULL
===DONE===