*** Testing array_intersect_uassoc() : usage variation ***

--int 0--

Warning: array_intersect_uassoc() expects parameter 3 to be a valid callback, no array or string given in %s on line %d
NULL

Warning: array_intersect_uassoc() expects parameter 4 to be a valid callback, no array or string given in %s on line %d
NULL

--int 1--

Warning: array_intersect_uassoc() expects parameter 3 to be a valid callback, no array or string given in %s on line %d
NULL

Warning: array_intersect_uassoc() expects parameter 4 to be a valid callback, no array or string given in %s on line %d
NULL

--int 12345--

Warning: array_intersect_uassoc() expects parameter 3 to be a valid callback, no array or string given in %s on line %d
NULL

Warning: array_intersect_uassoc() expects parameter 4 to be a valid callback, no array or string given in %s on line %d
NULL

--int -12345--

Warning: array_intersect_uassoc() expects parameter 3 to be a valid callback, no array or string given in %s on line %d
NULL

Warning: array_intersect_uassoc() expects parameter 4 to be a valid callback, no array or string given in %s on line %d
NULL

--float 10.5--

Warning: array_intersect_uassoc() expects parameter 3 to be a valid callback, no array or string given in %s on line %d
NULL

Warning: array_intersect_uassoc() expects parameter 4 to be a valid callback, no array or string given in %s on line %d
NULL

--float -10.5--

Warning: array_intersect_uassoc() expects parameter 3 to be a valid callback, no array or string given in %s on line %d
NULL

Warning: array_intersect_uassoc() expects parameter 4 to be a valid callback, no array or string given in %s on line %d
NULL

--float 12.3456789000e10--

Warning: array_intersect_uassoc() expects parameter 3 to be a valid callback, no array or string given in %s on line %d
NULL

Warning: array_intersect_uassoc() expects parameter 4 to be a valid callback, no array or string given in %s on line %d
NULL

--float -12.3456789000e10--

Warning: array_intersect_uassoc() expects parameter 3 to be a valid callback, no array or string given in %s on line %d
NULL

Warning: array_intersect_uassoc() expects parameter 4 to be a valid callback, no array or string given in %s on line %d
NULL

--float .5--

Warning: array_intersect_uassoc() expects parameter 3 to be a valid callback, no array or string given in %s on line %d
NULL

Warning: array_intersect_uassoc() expects parameter 4 to be a valid callback, no array or string given in %s on line %d
NULL

--uppercase NULL--

Warning: array_intersect_uassoc() expects parameter 3 to be a valid callback, no array or string given in %s on line %d
NULL

Warning: array_intersect_uassoc() expects parameter 4 to be a valid callback, no array or string given in %s on line %d
NULL

--lowercase null--

Warning: array_intersect_uassoc() expects parameter 3 to be a valid callback, no array or string given in %s on line %d
NULL

Warning: array_intersect_uassoc() expects parameter 4 to be a valid callback, no array or string given in %s on line %d
NULL

--lowercase true--

Warning: array_intersect_uassoc() expects parameter 3 to be a valid callback, no array or string given in %s on line %d
NULL

Warning: array_intersect_uassoc() expects parameter 4 to be a valid callback, no array or string given in %s on line %d
NULL

--lowercase false--

Warning: array_intersect_uassoc() expects parameter 3 to be a valid callback, no array or string given in %s on line %d
NULL

Warning: array_intersect_uassoc() expects parameter 4 to be a valid callback, no array or string given in %s on line %d
NULL

--uppercase TRUE--

Warning: array_intersect_uassoc() expects parameter 3 to be a valid callback, no array or string given in %s on line %d
NULL

Warning: array_intersect_uassoc() expects parameter 4 to be a valid callback, no array or string given in %s on line %d
NULL

--uppercase FALSE--

Warning: array_intersect_uassoc() expects parameter 3 to be a valid callback, no array or string given in %s on line %d
NULL

Warning: array_intersect_uassoc() expects parameter 4 to be a valid callback, no array or string given in %s on line %d
NULL

--instance of classWithToString--

Warning: array_intersect_uassoc() expects parameter 3 to be a valid callback, no array or string given in %s on line %d
NULL

Warning: array_intersect_uassoc() expects parameter 4 to be a valid callback, no array or string given in %s on line %d
NULL

--instance of classWithoutToString--

Warning: array_intersect_uassoc() expects parameter 3 to be a valid callback, no array or string given in %s on line %d
NULL

Warning: array_intersect_uassoc() expects parameter 4 to be a valid callback, no array or string given in %s on line %d
NULL

--undefined var--

Warning: array_intersect_uassoc() expects parameter 3 to be a valid callback, no array or string given in %s on line %d
NULL

Warning: array_intersect_uassoc() expects parameter 4 to be a valid callback, no array or string given in %s on line %d
NULL

--unset var--

Warning: array_intersect_uassoc() expects parameter 3 to be a valid callback, no array or string given in %s on line %d
NULL

Warning: array_intersect_uassoc() expects parameter 4 to be a valid callback, no array or string given in %s on line %d
NULL

--resource--

Warning: array_intersect_uassoc() expects parameter 3 to be a valid callback, no array or string given in %s on line %d
NULL

Warning: array_intersect_uassoc() expects parameter 4 to be a valid callback, no array or string given in %s on line %d
NULL
===DONE===