*** Testing array_reverse() : error conditions ***

-- Testing array_reverse() function with Zero arguments --

Warning: array_reverse() expects at least 1 parameter, 0 given in %s on line %d
NULL

-- Testing array_diff() function with more than expected no. of arguments --

Warning: array_reverse() expects at most 2 parameters, 3 given in %s on line %d
NULL

Warning: array_reverse() expects at most 2 parameters, 3 given in %s on line %d
NULL
Done