*** Testing array_fill_keys() : parameter variations ***

-- Testing array_fill_keys() function with both wrong arguments --

Warning: array_fill_keys() expects parameter 1 to be array, boolean given in %sarray_fill_keys_variation3.php on line %d
NULL

-- Testing array_fill_keys() function with unusual second arguments --
array(2) {
  ["one"]=>
  resource(%d) of type (stream)
  ["two"]=>
  resource(%d) of type (stream)
}

-- Testing array_fill_keys() function with mixed array --

Warning: array_fill_keys() expects parameter 1 to be array, null given in %sarray_fill_keys_variation3.php on line %d
NULL
Done