*** Testing array_multisort() : usage variation  - test sort order of all types***

Notice: Object of class classWithToString could not be converted to float in %sarray_multisort_variation9.php on line %d

Notice: Object of class classWithToString could not be converted to float in %sarray_multisort_variation9.php on line %d

Notice: Object of class classWithoutToString could not be converted to float in %sarray_multisort_variation9.php on line %d

Notice: Object of class classWithoutToString could not be converted to float in %sarray_multisort_variation9.php on line %d
bool(true)
array(10) {
  ["float -10.5"]=>
  float(-10.5)
  ["int 0"]=>
  int(0)
  [0]=>
  array(0) {
  }
  ["uppercase NULL"]=>
  NULL
  ["empty string DQ"]=>
  string(0) ""
  ["string DQ"]=>
  string(6) "string"
  ["undefined var"]=>
  NULL
  ["lowercase true"]=>
  bool(true)
  ["instance of classWithToString"]=>
  object(classWithToString)#1 (0) {
  }
  ["instance of classWithoutToString"]=>
  object(classWithoutToString)#2 (0) {
  }
}
===DONE===