*** Testing array_merge_recursive() : Passing non array values to $arr1 argument ***

-- Iteration 1 --
-- With default argument --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
-- With more arguments --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL

-- Iteration 2 --
-- With default argument --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
-- With more arguments --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL

-- Iteration 3 --
-- With default argument --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
-- With more arguments --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL

-- Iteration 4 --
-- With default argument --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
-- With more arguments --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL

-- Iteration 5 --
-- With default argument --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
-- With more arguments --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL

-- Iteration 6 --
-- With default argument --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
-- With more arguments --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL

-- Iteration 7 --
-- With default argument --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
-- With more arguments --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL

-- Iteration 8 --
-- With default argument --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
-- With more arguments --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL

-- Iteration 9 --
-- With default argument --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
-- With more arguments --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL

-- Iteration 10 --
-- With default argument --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
-- With more arguments --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL

-- Iteration 11 --
-- With default argument --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
-- With more arguments --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL

-- Iteration 12 --
-- With default argument --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
-- With more arguments --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL

-- Iteration 13 --
-- With default argument --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
-- With more arguments --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL

-- Iteration 14 --
-- With default argument --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
-- With more arguments --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL

-- Iteration 15 --
-- With default argument --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
-- With more arguments --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL

-- Iteration 16 --
-- With default argument --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
-- With more arguments --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL

-- Iteration 17 --
-- With default argument --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
-- With more arguments --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL

-- Iteration 18 --
-- With default argument --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
-- With more arguments --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL

-- Iteration 19 --
-- With default argument --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
-- With more arguments --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL

-- Iteration 20 --
-- With default argument --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
-- With more arguments --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL

-- Iteration 21 --
-- With default argument --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
-- With more arguments --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL

-- Iteration 22 --
-- With default argument --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
-- With more arguments --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL

-- Iteration 23 --
-- With default argument --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
-- With more arguments --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL

-- Iteration 24 --
-- With default argument --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
-- With more arguments --
Warning: array_merge_recursive(): Argument #1 is not an array in %s on line %d
NULL
Done