*** Testing arsort() : error conditions ***

-- Testing arsort() function with Zero arguments --

Warning: arsort() expects at least 1 parameter, 0 given in %sarsort_error.php on line %d
bool(false)

-- Testing arsort() function with more than expected no. of arguments --

Sort flag = SORT_REGULAR

Warning: arsort() expects at most 2 parameters, 3 given in %sarsort_error.php on line %d
bool(false)
array(2) {
  [0]=>
  int(1)
  [1]=>
  int(2)
}

Sort flag = SORT_STRING

Warning: arsort() expects at most 2 parameters, 3 given in %sarsort_error.php on line %d
bool(false)
array(2) {
  [0]=>
  int(1)
  [1]=>
  int(2)
}

Sort flag = SORT_NUMERIC

Warning: arsort() expects at most 2 parameters, 3 given in %sarsort_error.php on line %d
bool(false)
array(2) {
  [0]=>
  int(1)
  [1]=>
  int(2)
}
Done