*** Testing arsort() : usage variations ***

-- Testing arsort() by supplying different unexpected values for 'sort_flags' argument --
-- Iteration 1 --
bool(true)
array(3) {
  [3]=>
  int(45)
  [1]=>
  int(10)
  [2]=>
  int(2)
}
-- Iteration 2 --
bool(true)
array(3) {
  [3]=>
  int(45)
  [2]=>
  int(2)
  [1]=>
  int(10)
}
-- Iteration 3 --
bool(true)
array(3) {
  [3]=>
  int(45)
  [1]=>
  int(10)
  [2]=>
  int(2)
}
-- Iteration 4 --
bool(true)
array(3) {
  [3]=>
  int(45)
  [1]=>
  int(10)
  [2]=>
  int(2)
}
-- Iteration 5 --
bool(true)
array(3) {
  [3]=>
  int(45)
  [1]=>
  int(10)
  [2]=>
  int(2)
}
-- Iteration 6 --
bool(true)
array(3) {
  [3]=>
  int(45)
  [1]=>
  int(10)
  [2]=>
  int(2)
}
-- Iteration 7 --
bool(true)
array(3) {
  [3]=>
  int(45)
  [1]=>
  int(10)
  [2]=>
  int(2)
}
-- Iteration 8 --
bool(true)
array(3) {
  [3]=>
  int(45)
  [1]=>
  int(10)
  [2]=>
  int(2)
}
-- Iteration 9 --
bool(true)
array(3) {
  [3]=>
  int(45)
  [1]=>
  int(10)
  [2]=>
  int(2)
}
-- Iteration 10 --
bool(true)
array(3) {
  [3]=>
  int(45)
  [1]=>
  int(10)
  [2]=>
  int(2)
}
-- Iteration 11 --
bool(true)
array(3) {
  [3]=>
  int(45)
  [1]=>
  int(10)
  [2]=>
  int(2)
}
-- Iteration 12 --
bool(true)
array(3) {
  [3]=>
  int(45)
  [1]=>
  int(10)
  [2]=>
  int(2)
}
-- Iteration 13 --

Warning: arsort() expects parameter 2 to be integer, string given in %sarsort_variation2.php on line %d
bool(false)
array(3) {
  [1]=>
  int(10)
  [2]=>
  int(2)
  [3]=>
  int(45)
}
-- Iteration 14 --

Warning: arsort() expects parameter 2 to be integer, string given in %sarsort_variation2.php on line %d
bool(false)
array(3) {
  [1]=>
  int(10)
  [2]=>
  int(2)
  [3]=>
  int(45)
}
-- Iteration 15 --

Warning: arsort() expects parameter 2 to be integer, string given in %sarsort_variation2.php on line %d
bool(false)
array(3) {
  [1]=>
  int(10)
  [2]=>
  int(2)
  [3]=>
  int(45)
}
-- Iteration 16 --

Warning: arsort() expects parameter 2 to be integer, string given in %sarsort_variation2.php on line %d
bool(false)
array(3) {
  [1]=>
  int(10)
  [2]=>
  int(2)
  [3]=>
  int(45)
}
-- Iteration 17 --

Warning: arsort() expects parameter 2 to be integer, object given in %sarsort_variation2.php on line %d
bool(false)
array(3) {
  [1]=>
  int(10)
  [2]=>
  int(2)
  [3]=>
  int(45)
}
-- Iteration 18 --

Warning: arsort() expects parameter 2 to be integer, string given in %sarsort_variation2.php on line %d
bool(false)
array(3) {
  [1]=>
  int(10)
  [2]=>
  int(2)
  [3]=>
  int(45)
}
-- Iteration 19 --

Warning: arsort() expects parameter 2 to be integer, string given in %sarsort_variation2.php on line %d
bool(false)
array(3) {
  [1]=>
  int(10)
  [2]=>
  int(2)
  [3]=>
  int(45)
}
-- Iteration 20 --

Warning: arsort() expects parameter 2 to be integer, resource given in %sarsort_variation2.php on line %d
bool(false)
array(3) {
  [1]=>
  int(10)
  [2]=>
  int(2)
  [3]=>
  int(45)
}
Done