*** Testing count() : usage variations ***

-- Iteration 1 --
int(3)

-- Iteration 2 --
int(5)

-- Iteration 3 --
int(3)

-- Iteration 4 --
int(3)

-- Iteration 5 --
int(3)

-- Iteration 6 --
int(3)

-- Iteration 7 --
int(3)

-- Iteration 8 --
int(3)

-- Iteration 9 --
int(3)

-- Iteration 10 --
int(3)

-- Iteration 11 --
int(3)

-- Iteration 12 --
int(5)

-- Iteration 13 --
int(3)

-- Iteration 14 --
int(5)

-- Iteration 15 --
int(3)

-- Iteration 16 --

Warning: count() expects parameter 2 to be integer, string given in %s on line %d
NULL

-- Iteration 17 --

Warning: count() expects parameter 2 to be integer, string given in %s on line %d
NULL

-- Iteration 18 --

Warning: count() expects parameter 2 to be integer, string given in %s on line %d
NULL

-- Iteration 19 --

Warning: count() expects parameter 2 to be integer, string given in %s on line %d
NULL

-- Iteration 20 --

Warning: count() expects parameter 2 to be integer, string given in %s on line %d
NULL

-- Iteration 21 --

Warning: count() expects parameter 2 to be integer, object given in %s on line %d
NULL

-- Iteration 22 --
int(3)

-- Iteration 23 --
int(3)

-- Iteration 24 --

Warning: count() expects parameter 2 to be integer, resource given in %s on line %d
NULL
Done