*** Testing each() : usage variations ***

-- Iteration 1 --

Warning: Variable passed to each() is not an array or object in %s on line %d
NULL

-- Iteration 2 --

Warning: Variable passed to each() is not an array or object in %s on line %d
NULL

-- Iteration 3 --

Warning: Variable passed to each() is not an array or object in %s on line %d
NULL

-- Iteration 4 --

Warning: Variable passed to each() is not an array or object in %s on line %d
NULL

-- Iteration 5 --

Warning: Variable passed to each() is not an array or object in %s on line %d
NULL

-- Iteration 6 --

Warning: Variable passed to each() is not an array or object in %s on line %d
NULL

-- Iteration 7 --

Warning: Variable passed to each() is not an array or object in %s on line %d
NULL

-- Iteration 8 --

Warning: Variable passed to each() is not an array or object in %s on line %d
NULL

-- Iteration 9 --

Warning: Variable passed to each() is not an array or object in %s on line %d
NULL

-- Iteration 10 --

Warning: Variable passed to each() is not an array or object in %s on line %d
NULL

-- Iteration 11 --

Warning: Variable passed to each() is not an array or object in %s on line %d
NULL

-- Iteration 12 --

Warning: Variable passed to each() is not an array or object in %s on line %d
NULL

-- Iteration 13 --

Warning: Variable passed to each() is not an array or object in %s on line %d
NULL

-- Iteration 14 --

Warning: Variable passed to each() is not an array or object in %s on line %d
NULL

-- Iteration 15 --

Warning: Variable passed to each() is not an array or object in %s on line %d
NULL

-- Iteration 16 --

Warning: Variable passed to each() is not an array or object in %s on line %d
NULL

-- Iteration 17 --

Warning: Variable passed to each() is not an array or object in %s on line %d
NULL

-- Iteration 18 --
bool(false)

-- Iteration 19 --

Warning: Variable passed to each() is not an array or object in %s on line %d
NULL

-- Iteration 20 --

Warning: Variable passed to each() is not an array or object in %s on line %d
NULL

-- Iteration 21 --

Warning: Variable passed to each() is not an array or object in %s on line %d
NULL

-- Iteration 22 --
bool(false)

-- Iteration 23 --

Warning: Variable passed to each() is not an array or object in %s on line %d
NULL

-- Iteration 24 --

Warning: Variable passed to each() is not an array or object in %s on line %d
NULL

-- Iteration 25 --

Warning: Variable passed to each() is not an array or object in %s on line %d
NULL
Done