*** Testing error conditions of in_array() ***

Warning: in_array() expects at least 2 parameters, 0 given in %s on line %d
NULL

Warning: in_array() expects at most 3 parameters, 4 given in %s on line %d
NULL

Warning: in_array() expects at least 2 parameters, 1 given in %s on line %d
NULL

Warning: in_array() expects parameter 2 to be array, string given in %s on line %d
NULL

Warning: in_array() expects parameter 2 to be array, integer given in %s on line %d
NULL
Done