*** Testing krsort() : error conditions ***

-- Testing krsort() function with zero arguments --

Warning: krsort() expects at least 1 parameter, 0 given in %s on line %d
bool(false)

-- Testing krsort() function with more than expected no. of arguments --

- Sort flag = SORT_REGULAR -

Warning: krsort() expects at most 2 parameters, 3 given in %s on line %d
bool(false)
array(2) {
  [1]=>
  int(1)
  [2]=>
  int(2)
}

- Sort flag = SORT_STRING -

Warning: krsort() expects at most 2 parameters, 3 given in %s on line %d
bool(false)
array(2) {
  [1]=>
  int(1)
  [2]=>
  int(2)
}

- Sort flag = SORT_NUMERIC -

Warning: krsort() expects at most 2 parameters, 3 given in %s on line %d
bool(false)
array(2) {
  [1]=>
  int(1)
  [2]=>
  int(2)
}
Done