*** Testing ksort() : usage variations ***

-- Testing ksort() by supplying different unexpected values for 'sort_flags' argument --
-- Iteration 1 --
bool(true)
array(3) {
  [2]=>
  int(2)
  [10]=>
  int(10)
  [45]=>
  int(45)
}
-- Iteration 2 --
bool(true)
array(3) {
  [10]=>
  int(10)
  [2]=>
  int(2)
  [45]=>
  int(45)
}
-- Iteration 3 --
bool(true)
array(3) {
  [2]=>
  int(2)
  [10]=>
  int(10)
  [45]=>
  int(45)
}
-- Iteration 4 --
bool(true)
array(3) {
  [2]=>
  int(2)
  [10]=>
  int(10)
  [45]=>
  int(45)
}
-- Iteration 5 --
bool(true)
array(3) {
  [2]=>
  int(2)
  [10]=>
  int(10)
  [45]=>
  int(45)
}
-- Iteration 6 --
bool(true)
array(3) {
  [2]=>
  int(2)
  [10]=>
  int(10)
  [45]=>
  int(45)
}
-- Iteration 7 --
bool(true)
array(3) {
  [2]=>
  int(2)
  [10]=>
  int(10)
  [45]=>
  int(45)
}
-- Iteration 8 --
bool(true)
array(3) {
  [2]=>
  int(2)
  [10]=>
  int(10)
  [45]=>
  int(45)
}
-- Iteration 9 --
bool(true)
array(3) {
  [2]=>
  int(2)
  [10]=>
  int(10)
  [45]=>
  int(45)
}
-- Iteration 10 --
bool(true)
array(3) {
  [2]=>
  int(2)
  [10]=>
  int(10)
  [45]=>
  int(45)
}
-- Iteration 11 --
bool(true)
array(3) {
  [2]=>
  int(2)
  [10]=>
  int(10)
  [45]=>
  int(45)
}
-- Iteration 12 --
bool(true)
array(3) {
  [2]=>
  int(2)
  [10]=>
  int(10)
  [45]=>
  int(45)
}
-- Iteration 13 --

Warning: ksort() expects parameter 2 to be integer, string given in %s on line %d
bool(false)
array(3) {
  [10]=>
  int(10)
  [2]=>
  int(2)
  [45]=>
  int(45)
}
-- Iteration 14 --

Warning: ksort() expects parameter 2 to be integer, string given in %s on line %d
bool(false)
array(3) {
  [10]=>
  int(10)
  [2]=>
  int(2)
  [45]=>
  int(45)
}
-- Iteration 15 --

Warning: ksort() expects parameter 2 to be integer, string given in %s on line %d
bool(false)
array(3) {
  [10]=>
  int(10)
  [2]=>
  int(2)
  [45]=>
  int(45)
}
-- Iteration 16 --

Warning: ksort() expects parameter 2 to be integer, string given in %s on line %d
bool(false)
array(3) {
  [10]=>
  int(10)
  [2]=>
  int(2)
  [45]=>
  int(45)
}
-- Iteration 17 --

Warning: ksort() expects parameter 2 to be integer, object given in %s on line %d
bool(false)
array(3) {
  [10]=>
  int(10)
  [2]=>
  int(2)
  [45]=>
  int(45)
}
-- Iteration 18 --

Warning: ksort() expects parameter 2 to be integer, string given in %s on line %d
bool(false)
array(3) {
  [10]=>
  int(10)
  [2]=>
  int(2)
  [45]=>
  int(45)
}
-- Iteration 19 --

Warning: ksort() expects parameter 2 to be integer, string given in %s on line %d
bool(false)
array(3) {
  [10]=>
  int(10)
  [2]=>
  int(2)
  [45]=>
  int(45)
}
-- Iteration 20 --

Warning: ksort() expects parameter 2 to be integer, resource given in %s on line %d
bool(false)
array(3) {
  [10]=>
  int(10)
  [2]=>
  int(2)
  [45]=>
  int(45)
}
Done