*** Testing rsort() : variation ***
-- Iteration 1 --
Flag = default:

Warning: rsort() expects parameter 1 to be array, integer given in %s on line %d
bool(false)
Flag = SORT_REGULAR:

Warning: rsort() expects parameter 1 to be array, integer given in %s on line %d
bool(false)
Flag = SORT_NUMERIC:

Warning: rsort() expects parameter 1 to be array, integer given in %s on line %d
bool(false)
Flag = SORT_STRING:

Warning: rsort() expects parameter 1 to be array, integer given in %s on line %d
bool(false)
-- Iteration 2 --
Flag = default:

Warning: rsort() expects parameter 1 to be array, integer given in %s on line %d
bool(false)
Flag = SORT_REGULAR:

Warning: rsort() expects parameter 1 to be array, integer given in %s on line %d
bool(false)
Flag = SORT_NUMERIC:

Warning: rsort() expects parameter 1 to be array, integer given in %s on line %d
bool(false)
Flag = SORT_STRING:

Warning: rsort() expects parameter 1 to be array, integer given in %s on line %d
bool(false)
-- Iteration 3 --
Flag = default:

Warning: rsort() expects parameter 1 to be array, integer given in %s on line %d
bool(false)
Flag = SORT_REGULAR:

Warning: rsort() expects parameter 1 to be array, integer given in %s on line %d
bool(false)
Flag = SORT_NUMERIC:

Warning: rsort() expects parameter 1 to be array, integer given in %s on line %d
bool(false)
Flag = SORT_STRING:

Warning: rsort() expects parameter 1 to be array, integer given in %s on line %d
bool(false)
-- Iteration 4 --
Flag = default:

Warning: rsort() expects parameter 1 to be array, integer given in %s on line %d
bool(false)
Flag = SORT_REGULAR:

Warning: rsort() expects parameter 1 to be array, integer given in %s on line %d
bool(false)
Flag = SORT_NUMERIC:

Warning: rsort() expects parameter 1 to be array, integer given in %s on line %d
bool(false)
Flag = SORT_STRING:

Warning: rsort() expects parameter 1 to be array, integer given in %s on line %d
bool(false)
-- Iteration 5 --
Flag = default:

Warning: rsort() expects parameter 1 to be array, float given in %s on line %d
bool(false)
Flag = SORT_REGULAR:

Warning: rsort() expects parameter 1 to be array, float given in %s on line %d
bool(false)
Flag = SORT_NUMERIC:

Warning: rsort() expects parameter 1 to be array, float given in %s on line %d
bool(false)
Flag = SORT_STRING:

Warning: rsort() expects parameter 1 to be array, float given in %s on line %d
bool(false)
-- Iteration 6 --
Flag = default:

Warning: rsort() expects parameter 1 to be array, float given in %s on line %d
bool(false)
Flag = SORT_REGULAR:

Warning: rsort() expects parameter 1 to be array, float given in %s on line %d
bool(false)
Flag = SORT_NUMERIC:

Warning: rsort() expects parameter 1 to be array, float given in %s on line %d
bool(false)
Flag = SORT_STRING:

Warning: rsort() expects parameter 1 to be array, float given in %s on line %d
bool(false)
-- Iteration 7 --
Flag = default:

Warning: rsort() expects parameter 1 to be array, float given in %s on line %d
bool(false)
Flag = SORT_REGULAR:

Warning: rsort() expects parameter 1 to be array, float given in %s on line %d
bool(false)
Flag = SORT_NUMERIC:

Warning: rsort() expects parameter 1 to be array, float given in %s on line %d
bool(false)
Flag = SORT_STRING:

Warning: rsort() expects parameter 1 to be array, float given in %s on line %d
bool(false)
-- Iteration 8 --
Flag = default:

Warning: rsort() expects parameter 1 to be array, float given in %s on line %d
bool(false)
Flag = SORT_REGULAR:

Warning: rsort() expects parameter 1 to be array, float given in %s on line %d
bool(false)
Flag = SORT_NUMERIC:

Warning: rsort() expects parameter 1 to be array, float given in %s on line %d
bool(false)
Flag = SORT_STRING:

Warning: rsort() expects parameter 1 to be array, float given in %s on line %d
bool(false)
-- Iteration 9 --
Flag = default:

Warning: rsort() expects parameter 1 to be array, float given in %s on line %d
bool(false)
Flag = SORT_REGULAR:

Warning: rsort() expects parameter 1 to be array, float given in %s on line %d
bool(false)
Flag = SORT_NUMERIC:

Warning: rsort() expects parameter 1 to be array, float given in %s on line %d
bool(false)
Flag = SORT_STRING:

Warning: rsort() expects parameter 1 to be array, float given in %s on line %d
bool(false)
-- Iteration 10 --
Flag = default:

Warning: rsort() expects parameter 1 to be array, null given in %s on line %d
bool(false)
Flag = SORT_REGULAR:

Warning: rsort() expects parameter 1 to be array, null given in %s on line %d
bool(false)
Flag = SORT_NUMERIC:

Warning: rsort() expects parameter 1 to be array, null given in %s on line %d
bool(false)
Flag = SORT_STRING:

Warning: rsort() expects parameter 1 to be array, null given in %s on line %d
bool(false)
-- Iteration 11 --
Flag = default:

Warning: rsort() expects parameter 1 to be array, null given in %s on line %d
bool(false)
Flag = SORT_REGULAR:

Warning: rsort() expects parameter 1 to be array, null given in %s on line %d
bool(false)
Flag = SORT_NUMERIC:

Warning: rsort() expects parameter 1 to be array, null given in %s on line %d
bool(false)
Flag = SORT_STRING:

Warning: rsort() expects parameter 1 to be array, null given in %s on line %d
bool(false)
-- Iteration 12 --
Flag = default:

Warning: rsort() expects parameter 1 to be array, boolean given in %s on line %d
bool(false)
Flag = SORT_REGULAR:

Warning: rsort() expects parameter 1 to be array, boolean given in %s on line %d
bool(false)
Flag = SORT_NUMERIC:

Warning: rsort() expects parameter 1 to be array, boolean given in %s on line %d
bool(false)
Flag = SORT_STRING:

Warning: rsort() expects parameter 1 to be array, boolean given in %s on line %d
bool(false)
-- Iteration 13 --
Flag = default:

Warning: rsort() expects parameter 1 to be array, boolean given in %s on line %d
bool(false)
Flag = SORT_REGULAR:

Warning: rsort() expects parameter 1 to be array, boolean given in %s on line %d
bool(false)
Flag = SORT_NUMERIC:

Warning: rsort() expects parameter 1 to be array, boolean given in %s on line %d
bool(false)
Flag = SORT_STRING:

Warning: rsort() expects parameter 1 to be array, boolean given in %s on line %d
bool(false)
-- Iteration 14 --
Flag = default:

Warning: rsort() expects parameter 1 to be array, boolean given in %s on line %d
bool(false)
Flag = SORT_REGULAR:

Warning: rsort() expects parameter 1 to be array, boolean given in %s on line %d
bool(false)
Flag = SORT_NUMERIC:

Warning: rsort() expects parameter 1 to be array, boolean given in %s on line %d
bool(false)
Flag = SORT_STRING:

Warning: rsort() expects parameter 1 to be array, boolean given in %s on line %d
bool(false)
-- Iteration 15 --
Flag = default:

Warning: rsort() expects parameter 1 to be array, boolean given in %s on line %d
bool(false)
Flag = SORT_REGULAR:

Warning: rsort() expects parameter 1 to be array, boolean given in %s on line %d
bool(false)
Flag = SORT_NUMERIC:

Warning: rsort() expects parameter 1 to be array, boolean given in %s on line %d
bool(false)
Flag = SORT_STRING:

Warning: rsort() expects parameter 1 to be array, boolean given in %s on line %d
bool(false)
-- Iteration 16 --
Flag = default:

Warning: rsort() expects parameter 1 to be array, string given in %s on line %d
bool(false)
Flag = SORT_REGULAR:

Warning: rsort() expects parameter 1 to be array, string given in %s on line %d
bool(false)
Flag = SORT_NUMERIC:

Warning: rsort() expects parameter 1 to be array, string given in %s on line %d
bool(false)
Flag = SORT_STRING:

Warning: rsort() expects parameter 1 to be array, string given in %s on line %d
bool(false)
-- Iteration 17 --
Flag = default:

Warning: rsort() expects parameter 1 to be array, string given in %s on line %d
bool(false)
Flag = SORT_REGULAR:

Warning: rsort() expects parameter 1 to be array, string given in %s on line %d
bool(false)
Flag = SORT_NUMERIC:

Warning: rsort() expects parameter 1 to be array, string given in %s on line %d
bool(false)
Flag = SORT_STRING:

Warning: rsort() expects parameter 1 to be array, string given in %s on line %d
bool(false)
-- Iteration 18 --
Flag = default:

Warning: rsort() expects parameter 1 to be array, string given in %s on line %d
bool(false)
Flag = SORT_REGULAR:

Warning: rsort() expects parameter 1 to be array, string given in %s on line %d
bool(false)
Flag = SORT_NUMERIC:

Warning: rsort() expects parameter 1 to be array, string given in %s on line %d
bool(false)
Flag = SORT_STRING:

Warning: rsort() expects parameter 1 to be array, string given in %s on line %d
bool(false)
-- Iteration 19 --
Flag = default:

Warning: rsort() expects parameter 1 to be array, string given in %s on line %d
bool(false)
Flag = SORT_REGULAR:

Warning: rsort() expects parameter 1 to be array, string given in %s on line %d
bool(false)
Flag = SORT_NUMERIC:

Warning: rsort() expects parameter 1 to be array, string given in %s on line %d
bool(false)
Flag = SORT_STRING:

Warning: rsort() expects parameter 1 to be array, string given in %s on line %d
bool(false)
-- Iteration 20 --
Flag = default:

Warning: rsort() expects parameter 1 to be array, string given in %s on line %d
bool(false)
Flag = SORT_REGULAR:

Warning: rsort() expects parameter 1 to be array, string given in %s on line %d
bool(false)
Flag = SORT_NUMERIC:

Warning: rsort() expects parameter 1 to be array, string given in %s on line %d
bool(false)
Flag = SORT_STRING:

Warning: rsort() expects parameter 1 to be array, string given in %s on line %d
bool(false)
-- Iteration 21 --
Flag = default:

Warning: rsort() expects parameter 1 to be array, object given in %s on line %d
bool(false)
Flag = SORT_REGULAR:

Warning: rsort() expects parameter 1 to be array, object given in %s on line %d
bool(false)
Flag = SORT_NUMERIC:

Warning: rsort() expects parameter 1 to be array, object given in %s on line %d
bool(false)
Flag = SORT_STRING:

Warning: rsort() expects parameter 1 to be array, object given in %s on line %d
bool(false)
-- Iteration 22 --
Flag = default:

Warning: rsort() expects parameter 1 to be array, null given in %s on line %d
bool(false)
Flag = SORT_REGULAR:

Warning: rsort() expects parameter 1 to be array, null given in %s on line %d
bool(false)
Flag = SORT_NUMERIC:

Warning: rsort() expects parameter 1 to be array, null given in %s on line %d
bool(false)
Flag = SORT_STRING:

Warning: rsort() expects parameter 1 to be array, null given in %s on line %d
bool(false)
-- Iteration 23 --
Flag = default:

Warning: rsort() expects parameter 1 to be array, null given in %s on line %d
bool(false)
Flag = SORT_REGULAR:

Warning: rsort() expects parameter 1 to be array, null given in %s on line %d
bool(false)
Flag = SORT_NUMERIC:

Warning: rsort() expects parameter 1 to be array, null given in %s on line %d
bool(false)
Flag = SORT_STRING:

Warning: rsort() expects parameter 1 to be array, null given in %s on line %d
bool(false)
-- Iteration 24 --
Flag = default:

Warning: rsort() expects parameter 1 to be array, resource given in %s on line %d
bool(false)
Flag = SORT_REGULAR:

Warning: rsort() expects parameter 1 to be array, resource given in %s on line %d
bool(false)
Flag = SORT_NUMERIC:

Warning: rsort() expects parameter 1 to be array, resource given in %s on line %d
bool(false)
Flag = SORT_STRING:

Warning: rsort() expects parameter 1 to be array, resource given in %s on line %d
bool(false)
Done