*** Testing shuffle() : with unexpected values for 'array_arg' argument ***

-- Iteration 1 --

Warning: shuffle() expects parameter 1 to be array, integer given in %s on line %d
bool(false)

-- Iteration 2 --

Warning: shuffle() expects parameter 1 to be array, integer given in %s on line %d
bool(false)

-- Iteration 3 --

Warning: shuffle() expects parameter 1 to be array, integer given in %s on line %d
bool(false)

-- Iteration 4 --

Warning: shuffle() expects parameter 1 to be array, integer given in %s on line %d
bool(false)

-- Iteration 5 --

Warning: shuffle() expects parameter 1 to be array, float given in %s on line %d
bool(false)

-- Iteration 6 --

Warning: shuffle() expects parameter 1 to be array, float given in %s on line %d
bool(false)

-- Iteration 7 --

Warning: shuffle() expects parameter 1 to be array, float given in %s on line %d
bool(false)

-- Iteration 8 --

Warning: shuffle() expects parameter 1 to be array, float given in %s on line %d
bool(false)

-- Iteration 9 --

Warning: shuffle() expects parameter 1 to be array, float given in %s on line %d
bool(false)

-- Iteration 10 --

Warning: shuffle() expects parameter 1 to be array, null given in %s on line %d
bool(false)

-- Iteration 11 --

Warning: shuffle() expects parameter 1 to be array, null given in %s on line %d
bool(false)

-- Iteration 12 --

Warning: shuffle() expects parameter 1 to be array, boolean given in %s on line %d
bool(false)

-- Iteration 13 --

Warning: shuffle() expects parameter 1 to be array, boolean given in %s on line %d
bool(false)

-- Iteration 14 --

Warning: shuffle() expects parameter 1 to be array, boolean given in %s on line %d
bool(false)

-- Iteration 15 --

Warning: shuffle() expects parameter 1 to be array, boolean given in %s on line %d
bool(false)

-- Iteration 16 --

Warning: shuffle() expects parameter 1 to be array, string given in %s on line %d
bool(false)

-- Iteration 17 --

Warning: shuffle() expects parameter 1 to be array, string given in %s on line %d
bool(false)

-- Iteration 18 --

Warning: shuffle() expects parameter 1 to be array, string given in %s on line %d
bool(false)

-- Iteration 19 --

Warning: shuffle() expects parameter 1 to be array, string given in %s on line %d
bool(false)

-- Iteration 20 --

Warning: shuffle() expects parameter 1 to be array, object given in %s on line %d
bool(false)

-- Iteration 21 --

Warning: shuffle() expects parameter 1 to be array, null given in %s on line %d
bool(false)

-- Iteration 22 --

Warning: shuffle() expects parameter 1 to be array, null given in %s on line %d
bool(false)

-- Iteration 23 --

Warning: shuffle() expects parameter 1 to be array, resource given in %s on line %d
bool(false)
Done