*** Testing sort() : error conditions ***

-- Testing sort() function with Zero arguments --

Warning: sort() expects at least 1 parameter, 0 given in %s on line %d
bool(false)

-- Testing sort() function with more than expected no. of arguments --

Sort flag = SORT_REGULAR

Warning: sort() expects at most 2 parameters, 3 given in %s on line %d
bool(false)
array(2) {
  [0]=>
  int(1)
  [1]=>
  int(2)
}

Sort flag = SORT_STRING

Warning: sort() expects at most 2 parameters, 3 given in %s on line %d
bool(false)
array(2) {
  [0]=>
  int(1)
  [1]=>
  int(2)
}

Sort flag = SORT_NUMERIC

Warning: sort() expects at most 2 parameters, 3 given in %s on line %d
bool(false)
array(2) {
  [0]=>
  int(1)
  [1]=>
  int(2)
}
Done