*** Testing uasort() : unexpected values for 'array_arg' ***
-- Iteration 1 --

Warning: uasort() expects parameter 1 to be array, integer given in %s on line %d
NULL
-- Iteration 2 --

Warning: uasort() expects parameter 1 to be array, integer given in %s on line %d
NULL
-- Iteration 3 --

Warning: uasort() expects parameter 1 to be array, integer given in %s on line %d
NULL
-- Iteration 4 --

Warning: uasort() expects parameter 1 to be array, integer given in %s on line %d
NULL
-- Iteration 5 --

Warning: uasort() expects parameter 1 to be array, float given in %s on line %d
NULL
-- Iteration 6 --

Warning: uasort() expects parameter 1 to be array, float given in %s on line %d
NULL
-- Iteration 7 --

Warning: uasort() expects parameter 1 to be array, float given in %s on line %d
NULL
-- Iteration 8 --

Warning: uasort() expects parameter 1 to be array, float given in %s on line %d
NULL
-- Iteration 9 --

Warning: uasort() expects parameter 1 to be array, float given in %s on line %d
NULL
-- Iteration 10 --

Warning: uasort() expects parameter 1 to be array, null given in %s on line %d
NULL
-- Iteration 11 --

Warning: uasort() expects parameter 1 to be array, null given in %s on line %d
NULL
-- Iteration 12 --

Warning: uasort() expects parameter 1 to be array, boolean given in %s on line %d
NULL
-- Iteration 13 --

Warning: uasort() expects parameter 1 to be array, boolean given in %s on line %d
NULL
-- Iteration 14 --

Warning: uasort() expects parameter 1 to be array, boolean given in %s on line %d
NULL
-- Iteration 15 --

Warning: uasort() expects parameter 1 to be array, boolean given in %s on line %d
NULL
-- Iteration 16 --

Warning: uasort() expects parameter 1 to be array, string given in %s on line %d
NULL
-- Iteration 17 --

Warning: uasort() expects parameter 1 to be array, string given in %s on line %d
NULL
-- Iteration 18 --

Warning: uasort() expects parameter 1 to be array, string given in %s on line %d
NULL
-- Iteration 19 --

Warning: uasort() expects parameter 1 to be array, string given in %s on line %d
NULL
-- Iteration 20 --

Warning: uasort() expects parameter 1 to be array, resource given in %s on line %d
NULL
-- Iteration 21 --

Warning: uasort() expects parameter 1 to be array, null given in %s on line %d
NULL
-- Iteration 22 --

Warning: uasort() expects parameter 1 to be array, null given in %s on line %d
NULL
Done