*** Test substituting argument 1 with string values ***

Warning: posix_setgid() expects parameter 1 to be integer, string given in %s on line %d
bool(false)

Warning: posix_setgid() expects parameter 1 to be integer, string given in %s on line %d
bool(false)

Warning: posix_setgid() expects parameter 1 to be integer, string given in %s on line %d
bool(false)

Warning: posix_setgid() expects parameter 1 to be integer, string given in %s on line %d
bool(false)