*** Testing posix_getpgid() : error conditions ***

-- Testing posix_getpgid() function no arguments --

Warning: posix_getpgid() expects exactly 1 parameter, 0 given in %s on line %d
bool(false)

-- Testing posix_getpgid() with one extra argument --

Warning: posix_getpgid() expects exactly 1 parameter, 2 given in %s on line %d
bool(false)

-- Testing posix_getpgid() with negative pid  --
bool(false)
Done