*** Testing posix_strerror() : error conditions ***

-- Testing posix_strerror() function with Zero arguments --

Warning: posix_strerror() expects exactly 1 parameter, 0 given in %s on line %d
bool(false)

-- Testing posix_strerror() function with more than expected no. of arguments --

Warning: posix_strerror() expects exactly 1 parameter, 2 given in %s on line %d
bool(false)

-- Testing posix_strerror() function with invalid error number --
string
Done