*** Testing posix_getgrgid() : error conditions ***

-- Testing posix_getgrgid() function with Zero arguments --

Warning: posix_getgrgid() expects exactly 1 parameter, 0 given in %s on line %d
bool(false)

-- Testing posix_getgrgid() function with more than expected no. of arguments --

Warning: posix_getgrgid() expects exactly 1 parameter, 2 given in %s on line %d
bool(false)

-- Testing posix_getgrgid() function with a negative group id --
bool(false)
Done