Warning: posix_seteuid() expects parameter 1 to be integer, array given in %s on line 15
bool(false)

Warning: posix_seteuid() expects parameter 1 to be integer, array given in %s on line 15
bool(false)

Warning: posix_seteuid() expects parameter 1 to be integer, array given in %s on line 15
bool(false)

Warning: posix_seteuid() expects parameter 1 to be integer, array given in %s on line 15
bool(false)