*** Test substituting argument 1 with string values ***

Warning: posix_setuid() expects parameter 1 to be integer, string given in %s on line 21
bool(false)

Warning: posix_setuid() expects parameter 1 to be integer, string given in %s on line 21
bool(false)

Warning: posix_setuid() expects parameter 1 to be integer, string given in %s on line 21
bool(false)

Warning: posix_setuid() expects parameter 1 to be integer, string given in %s on line 21
bool(false)