*** Testing posix_getpwuid() : error conditions ***

-- Testing posix_getpwuid() function with Zero arguments --

Warning: posix_getpwuid() expects exactly 1 parameter, 0 given in %s on line %d
bool(false)

-- Testing posix_getpwuid() function with more than expected no. of arguments --

Warning: posix_getpwuid() expects exactly 1 parameter, 2 given in %s on line %d
bool(false)

-- Testing posix_getpwuid() function negative uid --
bool(false)
Done