*** Test substituting argument 1 with array values ***

Warning: posix_setgid() expects parameter 1 to be integer, array given in %s on line %d
bool(false)

Warning: posix_setgid() expects parameter 1 to be integer, array given in %s on line %d
bool(false)

Warning: posix_setgid() expects parameter 1 to be integer, array given in %s on line %d
bool(false)

Warning: posix_setgid() expects parameter 1 to be integer, array given in %s on line %d
bool(false)
===DONE===