*** Testing get_class_vars() : error conditions ***

-- Testing get_class_vars() function with more than expected no. of arguments --

Warning: get_class_vars() expects exactly 1 parameter, 2 given in %sget_class_vars_error.php on line %d
NULL

-- Testing get_class_vars() function with less than expected no. of arguments --

Warning: get_class_vars() expects exactly 1 parameter, 0 given in %sget_class_vars_error.php on line %d
NULL
===DONE===