*** Testing is_a() : error conditions ***

-- Testing is_a() function with more than expected no. of arguments --

Warning: is_a() expects at most 3 parameters, 4 given in %s on line 17
NULL

-- Testing is_a() function with non-boolean in last position --

Warning: is_a() expects parameter 3 to be boolean, object given in %s on line 21
NULL

-- Testing is_a() function with less than expected no. of arguments --

Warning: is_a() expects at least 2 parameters, 1 given in %s on line 27
NULL
Done