*** Testing property_exists() : error conditions ***

-- Testing property_exists() function with more than expected no. of arguments --

Warning: property_exists() expects exactly 2 parameters, 3 given in %sproperty_exists_error.php on line %d
NULL

-- Testing property_exists() function with less than expected no. of arguments --

Warning: property_exists() expects exactly 2 parameters, 1 given in %sproperty_exists_error.php on line %d
NULL

-- Testing property_exists() function with incorrect arguments --

Warning: First parameter must either be an object or the name of an existing class in %sproperty_exists_error.php on line %d
NULL
===DONE===