array(1) {
  [0]=>
  string(%d) "%s"
}
array(2) {
  [0]=>
  string(%d) "%s"
  [1]=>
  string(%d) "%s"
}

Warning: get_included_files() expects exactly 0 parameters, 2 given in %s on line %d
NULL
array(2) {
  [0]=>
  string(%d) "%s"
  [1]=>
  string(%d) "%s"
}

Warning: get_included_files() expects exactly 0 parameters, 1 given in %s on line %d
NULL
array(2) {
  [0]=>
  string(%d) "%s"
  [1]=>
  string(%d) "%s"
}
Done