Notice: Undefined variable: a in %s on line %d
NULL

Notice: Undefined variable: %s in %s on line %d

Notice: Undefined variable: %s in %s on line %d
NULL

Notice: Undefined variable: a in %s on line %d
int(1)

Notice: Undefined variable: %s in %s on line %d

Notice: Undefined variable: %s in %s on line %d
int(0)

Notice: Undefined variable: a in %s on line %d
NULL

Notice: Undefined variable: b in %s on line %d
int(1)

Notice: Trying to get property of non-object in %s on line %d
NULL

Notice: Trying to get property of non-object in %s on line %d
NULL

Notice: Undefined variable: c in %s on line %d

Notice: Trying to get property of non-object in %s on line %d

Notice: Trying to get property of non-object in %s on line %d
NULL