Notice: String offset cast occurred in %s on line %d

Notice: Uninitialized string offset: %s in %s on line 6

Notice: Uninitialized string offset: 0 in %s on line %d

Notice: Uninitialized string offset: 0 in %s on line %d

Notice: String offset cast occurred in %s on line %d

Notice: Uninitialized string offset: %i in %s on line %d

Notice: String offset cast occurred in %s on line %d

Notice: Uninitialized string offset: %i in %s on line %d

Notice: Uninitialized string offset: 0 in %s on line %d

Notice: Uninitialized string offset: 4 in %s on line %d

Notice: Uninitialized string offset: 4 in %s on line %d

Notice: Uninitialized string offset: 4 in %s on line %d

Notice: Uninitialized string offset: 4 in %s on line %d

Notice: Uninitialized string offset: 4 in %s on line %d

Notice: String offset cast occurred in %s on line %d

Notice: Uninitialized string offset: 12 in %s on line %d

Notice: String offset cast occurred in %s on line %d

Notice: Uninitialized string offset: 12 in %s on line %d

Notice: String offset cast occurred in %s on line %d

Notice: String offset cast occurred in %s on line %d
b
Done