string(1) "a"
string(1) "a"
string(1) "a"
string(6) "     a"

Warning: Illegal string offset:  -1 in %s on line %d
NULL
string(0) ""

Warning: Illegal string offset 'foo' in %s on line %d
string(1) "a"
string(1) "a"
Error: [] operator not supported for strings
string(0) ""
Error: Cannot use assign-op operators with string offsets
string(0) ""
Error: Cannot use string offset as an array
string(0) ""