Array of NULL:

Warning: Expected array for frame 0 in %s on line %d
string(9) "#0 {main}"

Array of empty array:
string(36) "#0 [internal function]: ()
#1 {main}"

Array of array of NULL values:

Warning: Function name is no string in %s on line %d

Warning: Value for class is no string in %s on line %d

Warning: Value for type is no string in %s on line %d

Warning: Value for function is no string in %s on line %d

Warning: args element is no array in %s on line %d
string(60) "#0 [unknown function][unknown][unknown][unknown]()
#1 {main}"