bool(false)
bool(true)

Warning: strlen() has been disabled for security reasons in %sbug69315.php on line %d
NULL

Warning: defined() has been disabled for security reasons in %sbug69315.php on line %d
NULL

Warning: constant() has been disabled for security reasons in %sbug69315.php on line %d
NULL

Warning: call_user_func() has been disabled for security reasons in %sbug69315.php on line %d
NULL

Warning: is_string() has been disabled for security reasons in %sbug69315.php on line %d
NULL