Warning: Parameter 1 to test() expected to be a reference, value given in %s on line %d

Warning: Parameter 2 to test() expected to be a reference, value given in %s on line %d
bool(true)
int(0)
int(0)

Warning: Parameter 1 to test() expected to be a reference, value given in %s on line %d

Warning: Parameter 2 to test() expected to be a reference, value given in %s on line %d
bool(true)
int(0)
int(0)

Warning: Parameter 1 to test() expected to be a reference, value given in %s on line %d

Warning: Parameter 2 to test() expected to be a reference, value given in %s on line %d
bool(true)
int(0)
int(0)

Warning: Parameter 1 to test() expected to be a reference, value given in %s on line %d

Warning: Parameter 2 to test() expected to be a reference, value given in %s on line %d
bool(true)
int(0)
int(0)