Before binding
bool(false)
bool(false)

bool(true)
bool(false)

After binding, null scope, no instance
bool(false)
bool(false)

bool(false)
bool(false)

After binding, null scope, with instance

Warning: Cannot bind an instance to a static closure in %s on line %d

Warning: Cannot bind an instance to a static closure in %s on line %d
After binding, with scope, no instance
bool(true)
bool(false)

bool(true)
bool(false)

After binding, with scope, with instance

Warning: Cannot bind an instance to a static closure in %s on line %d

Warning: Cannot bind an instance to a static closure in %s on line %d
Done.