Notice: Array to string conversion in %s on line %d

Warning: Class 'Array' not found in %s on line %d

Warning: Closure::bindTo() expects parameter 1 to be object, array given in %s on line 25

Warning: Closure::bindTo() expects at most 2 parameters, 3 given in %s on line %d

Warning: Closure::bindTo() expects at least 1 parameter, 0 given in %s on line %d

Warning: Cannot bind an instance to a static closure in %s on line %d