array(2) {
  [0]=>
  int(1)
  [1]=>
  int(5)
}
int(5)
int(1)
object(foo)#2 (0) {
}
array(3) {
  [0]=>
  int(3)
  [1]=>
  array(2) {
    [0]=>
    int(1)
    [1]=>
    int(5)
  }
  [2]=>
  object(foo)#3 (0) {
  }
}
int(3)
object(foo)#3 (0) {
}
array(2) {
  [0]=>
  int(1)
  [1]=>
  int(5)
}
int(1)
NULL

Notice: Undefined offset: 4 in %s on line %d
NULL

Notice: Undefined offset: 3 in %s on line %d

Fatal error: Uncaught Error: Call to a member function bar() on null in %s:%d
Stack trace:
#0 {main}
  thrown in %s on line %d