Warning: Cannot call extract() dynamically in %s on line %d

Warning: Cannot call compact() dynamically in %s on line %d

Warning: Cannot call parse_str() with a single argument dynamically in %s on line %d

Warning: Cannot call get_defined_vars() dynamically in %s on line %d

Warning: Cannot call assert() with string argument dynamically in %s on line %d

Warning: Cannot call func_get_args() dynamically in %s on line %d

Warning: Cannot call func_get_arg() dynamically in %s on line %d

Warning: Cannot call func_num_args() dynamically in %s on line %d