Exception: Cannot call abstract method C::foo() in %sexception_017.php on line %d

Exception: Argument 1 passed to foo() must be callable, string given, called in %sexception_017.php on line %d
Exception: Cannot call abstract method C::foo()

Fatal error: Uncaught Error: Cannot call abstract method C::foo() in %sexception_017.php:%d
Stack trace:
#0 {main}
  thrown in %sexception_017.php on line %d