*** Indexing - Testing value assignment with key ***
array(1) {
  ["foo"]=>
  array(1) {
    [0]=>
    int(1)
  }
}

Warning: Cannot use a scalar value as an array in %s on line %d
int(0)

Warning: Cannot use a scalar value as an array in %s on line %d
int(1)

Warning: Cannot use a scalar value as an array in %s on line %d
bool(true)
array(1) {
  ["foo"]=>
  array(1) {
    [0]=>
    int(1)
  }
}

Warning: Illegal string offset 'foo' in %s on line %d

Notice: Array to string conversion in %s on line %d
string(1) "A"

Warning: Illegal string offset 'foo' in %s on line %d

Notice: Array to string conversion in %s on line %d
string(1) "A"

Warning: Cannot use a scalar value as an array in %s on line %d
float(0.1)
array(1) {
  ["foo"]=>
  array(1) {
    [0]=>
    int(1)
  }
}

*** Indexing - Testing reference assignment with key ***
array(1) {
  ["foo"]=>
  &array(1) {
    [0]=>
    int(1)
  }
}

Warning: Cannot use a scalar value as an array in %s on line %d
int(0)

Warning: Cannot use a scalar value as an array in %s on line %d
int(1)

Warning: Cannot use a scalar value as an array in %s on line %d
bool(true)
array(1) {
  ["foo"]=>
  &array(1) {
    [0]=>
    int(1)
  }
}

Warning: Cannot use a scalar value as an array in %s on line %d
float(0.1)
array(1) {
  ["foo"]=>
  &array(1) {
    [0]=>
    int(1)
  }
}
*** Indexing - Testing value assignment no key ***
array(1) {
  [0]=>
  array(1) {
    [0]=>
    int(1)
  }
}

Warning: Cannot use a scalar value as an array in %s on line %d
int(0)

Warning: Cannot use a scalar value as an array in %s on line %d
int(1)

Warning: Cannot use a scalar value as an array in %s on line %d
bool(true)
array(1) {
  [0]=>
  array(1) {
    [0]=>
    int(1)
  }
}

Warning: Cannot use a scalar value as an array in %s on line %d
float(0.1)
array(1) {
  [0]=>
  array(1) {
    [0]=>
    int(1)
  }
}

*** Indexing - Testing reference assignment no key ***
array(1) {
  [0]=>
  &array(1) {
    [0]=>
    int(1)
  }
}

Warning: Cannot use a scalar value as an array in %s on line %d
int(0)

Warning: Cannot use a scalar value as an array in %s on line %d
int(1)

Warning: Cannot use a scalar value as an array in %s on line %d
bool(true)
array(1) {
  [0]=>
  &array(1) {
    [0]=>
    int(1)
  }
}

Warning: Cannot use a scalar value as an array in %s on line %d
float(0.1)
array(1) {
  [0]=>
  &array(1) {
    [0]=>
    int(1)
  }
}

Done