bool(false)
bool(true)
bool(true)
bool(false)
bool(false)
bool(true)
bool(false)
bool(true)

Notice: Object of class Bar could not be converted to int in %s on line %d
bool(false)

Notice: Object of class Bar could not be converted to int in %s on line %d
bool(true)

Notice: Object of class Bar could not be converted to int in %s on line %d
bool(true)

Notice: Object of class Bar could not be converted to int in %s on line %d
bool(false)

Notice: Object of class Bar could not be converted to float in %s on line %d
bool(true)

Notice: Object of class Bar could not be converted to float in %s on line %d
bool(false)

Notice: Object of class Bar could not be converted to int in %s on line %d
bool(true)
Done