string(1) "i"

Notice: String offset cast occurred in %s on line %d
string(1) "S"

Notice: String offset cast occurred in %s on line %d
string(1) "S"

Warning: Illegal string offset 'run away' in %s on line %d
string(1) "S"
string(1) "c"

Warning: Illegal string offset '14.5' in %s on line %d
string(1) "o"

Notice: A non well formed numeric value encountered in %s on line %d
string(1) "r"

Notice: String offset cast occurred in %s on line %d
string(1) "i"

Notice: String offset cast occurred in %s on line %d
string(1) "S"

Warning: Illegal offset type in %s on line %d
string(1) "%s"

Warning: Illegal offset type in %s on line %d

Notice: Object of class stdClass could not be converted to int in %s on line %d
string(1) "%s"

Warning: Illegal offset type in %s on line %d
string(1) "i"
Done