Notice: Uninitialized string offset: -10 in %sstr_offset_003.php on line %d
string(0) ""
string(1) "d"

Notice: Uninitialized string offset: -2 in %sstr_offset_003.php on line %d
string(0) ""
string(1) "c"

Notice: Uninitialized string offset: -10 in %sstr_offset_003.php on line %d
string(0) ""
string(1) "d"

Notice: Uninitialized string offset: -2 in %sstr_offset_003.php on line %d
string(0) ""
string(1) "c"