*** Testing error conditions ***

-- Testing with  Non-existing files --
Warning: fileatime(): stat failed for /no/such/file/or/dir in %s on line %d
bool(false)

Warning: filemtime(): stat failed for /no/such/file/or/dir in %s on line %d
bool(false)

Warning: filectime(): stat failed for /no/such/file/or/dir in %s on line %d
bool(false)

Warning: touch(): Unable to create file /no/such/file/or/dir because No such file or directory in %s on line %d
bool(false)

Warning: fileatime() expects exactly 1 parameter, 2 given in %s on line %d
NULL

Warning: filemtime() expects exactly 1 parameter, 2 given in %s on line %d
NULL

Warning: filectime() expects exactly 1 parameter, 2 given in %s on line %d
NULL

Warning: touch() expects at most 3 parameters, 4 given in %s on line %d
NULL

-- Testing No.of arguments less than expected --
Warning: fileatime() expects exactly 1 parameter, 0 given in %s on line %d
NULL

Warning: filemtime() expects exactly 1 parameter, 0 given in %s on line %d
NULL

Warning: filectime() expects exactly 1 parameter, 0 given in %s on line %d
NULL

Warning: touch() expects at least 1 parameter, 0 given in %s on line %d
NULL

-- Testing No.of arguments greater than expected --
Warning: fileatime() expects exactly 1 parameter, 2 given in %s on line %d
NULL

Warning: filemtime() expects exactly 1 parameter, 2 given in %s on line %d
NULL

Warning: filectime() expects exactly 1 parameter, 2 given in %s on line %d
NULL

Warning: touch() expects at most 3 parameters, 4 given in %s on line %d
NULL

Warning: fileatime() expects exactly 1 parameter, 2 given in %s on line %d
NULL

Warning: filemtime() expects exactly 1 parameter, 2 given in %s on line %d
NULL

Warning: filectime() expects exactly 1 parameter, 2 given in %s on line %d
NULL

Warning: touch() expects at most 3 parameters, 4 given in %s on line %d
NULL

Done