*** Testing chmod() : error conditions ***

-- Testing chmod() function with more than expected no. of arguments --

Warning: chmod() expects exactly 2 parameters, 3 given in %s on line %d
NULL

-- Testing chmod() function with less than expected no. of arguments --

Warning: chmod() expects exactly 2 parameters, 1 given in %s on line %d
NULL

Warning: chmod(): No such file or directory in %s on line %d
bool(false)
===DONE===