*** Testing fgets() : usage variations ***
-- Testing fgets() with closed handle --

Warning: fgets(): supplied resource is not a valid stream resource in %s on line %d
bool(false)

Warning: fgets(): supplied resource is not a valid stream resource in %s on line %d
bool(false)
-- Testing fgets() with unset handle --

Notice: Undefined variable: file_handle in %s on line %d

Warning: fgets() expects parameter 1 to be resource, null given in %s on line %d
bool(false)

Notice: Undefined variable: file_handle in %s on line %d

Warning: fgets() expects parameter 1 to be resource, null given in %s on line %d
bool(false)
Done