*** Testing fgetcsv() : with default enclosure & delimiter of two chars ***

-- Testing fgetcsv() with file opened using r mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water,fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using rb mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water,fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using rt mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water,fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using r+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water,fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using r+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water,fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using r+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water,fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using a+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water,fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using a+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water,fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using a+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water,fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using w+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water,fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using w+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water,fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using w+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water,fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using x+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water,fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using x+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water,fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using x+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water,fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using r mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using rb mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using rt mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using r+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using r+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using r+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using a+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using a+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using a+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using w+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using w+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using w+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using x+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using x+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using x+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(11) "water fruit"
}
int(12)
bool(false)

-- Testing fgetcsv() with file opened using r mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(13) "water "fruit""
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using rb mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(13) "water "fruit""
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using rt mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(13) "water "fruit""
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using r+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(13) "water "fruit""
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using r+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(13) "water "fruit""
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using r+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(13) "water "fruit""
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using a+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(13) "water "fruit""
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using a+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(13) "water "fruit""
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using a+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(13) "water "fruit""
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using w+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(13) "water "fruit""
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using w+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(13) "water "fruit""
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using w+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(13) "water "fruit""
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using x+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(13) "water "fruit""
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using x+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(13) "water "fruit""
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using x+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(13) "water "fruit""
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using r mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(19) "water\"fruit"\"air""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using rb mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(19) "water\"fruit"\"air""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using rt mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(19) "water\"fruit"\"air""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using r+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(19) "water\"fruit"\"air""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using r+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(19) "water\"fruit"\"air""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using r+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(19) "water\"fruit"\"air""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using a+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(19) "water\"fruit"\"air""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using a+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(19) "water\"fruit"\"air""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using a+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(19) "water\"fruit"\"air""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using w+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(19) "water\"fruit"\"air""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using w+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(19) "water\"fruit"\"air""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using w+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(19) "water\"fruit"\"air""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using x+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(19) "water\"fruit"\"air""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using x+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(19) "water\"fruit"\"air""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using x+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(19) "water\"fruit"\"air""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using r mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(17) "water\"fruit"\""""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using rb mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(17) "water\"fruit"\""""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using rt mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(17) "water\"fruit"\""""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using r+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(17) "water\"fruit"\""""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using r+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(17) "water\"fruit"\""""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using r+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(17) "water\"fruit"\""""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using a+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(17) "water\"fruit"\""""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using a+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(17) "water\"fruit"\""""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using a+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(17) "water\"fruit"\""""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using w+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(17) "water\"fruit"\""""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using w+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(17) "water\"fruit"\""""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using w+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(17) "water\"fruit"\""""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using x+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(17) "water\"fruit"\""""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using x+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(17) "water\"fruit"\""""
}
int(20)
bool(false)

-- Testing fgetcsv() with file opened using x+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d
array(1) {
  [0]=>
  string(17) "water\"fruit"\""""
}
int(20)
bool(false)
Done