*** Testing fgetcsv() : with two chars as enclosure & delimiter ***

-- Testing fgetcsv() with file opened using r mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(13) ""water",fruit"
}
int(14)
bool(false)

-- Testing fgetcsv() with file opened using rb mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(13) ""water",fruit"
}
int(14)
bool(false)

-- Testing fgetcsv() with file opened using rt mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(13) ""water",fruit"
}
int(14)
bool(false)

-- Testing fgetcsv() with file opened using r+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(13) ""water",fruit"
}
int(14)
bool(false)

-- Testing fgetcsv() with file opened using r+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(13) ""water",fruit"
}
int(14)
bool(false)

-- Testing fgetcsv() with file opened using r+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(13) ""water",fruit"
}
int(14)
bool(false)

-- Testing fgetcsv() with file opened using a+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(13) ""water",fruit"
}
int(14)
bool(false)

-- Testing fgetcsv() with file opened using a+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(13) ""water",fruit"
}
int(14)
bool(false)

-- Testing fgetcsv() with file opened using a+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(13) ""water",fruit"
}
int(14)
bool(false)

-- Testing fgetcsv() with file opened using r mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) ""water","fruit""
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using rb mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) ""water","fruit""
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using rt mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) ""water","fruit""
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using r+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) ""water","fruit""
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using r+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) ""water","fruit""
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using r+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) ""water","fruit""
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using a+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) ""water","fruit""
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using a+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) ""water","fruit""
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using a+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) ""water","fruit""
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using r mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "^water^ ^fruit^"
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using rb mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "^water^ ^fruit^"
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using rt mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "^water^ ^fruit^"
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using r+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "^water^ ^fruit^"
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using r+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "^water^ ^fruit^"
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using r+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "^water^ ^fruit^"
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using a+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "^water^ ^fruit^"
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using a+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "^water^ ^fruit^"
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using a+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "^water^ ^fruit^"
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using r mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "&water&:&fruit&"
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using rb mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "&water&:&fruit&"
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using rt mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "&water&:&fruit&"
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using r+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "&water&:&fruit&"
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using r+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "&water&:&fruit&"
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using r+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "&water&:&fruit&"
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using a+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "&water&:&fruit&"
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using a+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "&water&:&fruit&"
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using a+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "&water&:&fruit&"
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using r mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "=water===fruit="
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using rb mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "=water===fruit="
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using rt mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "=water===fruit="
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using r+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "=water===fruit="
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using r+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "=water===fruit="
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using r+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "=water===fruit="
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using a+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "=water===fruit="
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using a+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "=water===fruit="
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using a+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(15) "=water===fruit="
}
int(16)
bool(false)

-- Testing fgetcsv() with file opened using r mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(17) "-water--fruit-air"
}
int(18)
bool(false)

-- Testing fgetcsv() with file opened using rb mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(17) "-water--fruit-air"
}
int(18)
bool(false)

-- Testing fgetcsv() with file opened using rt mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(17) "-water--fruit-air"
}
int(18)
bool(false)

-- Testing fgetcsv() with file opened using r+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(17) "-water--fruit-air"
}
int(18)
bool(false)

-- Testing fgetcsv() with file opened using r+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(17) "-water--fruit-air"
}
int(18)
bool(false)

-- Testing fgetcsv() with file opened using r+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(17) "-water--fruit-air"
}
int(18)
bool(false)

-- Testing fgetcsv() with file opened using a+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(17) "-water--fruit-air"
}
int(18)
bool(false)

-- Testing fgetcsv() with file opened using a+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(17) "-water--fruit-air"
}
int(18)
bool(false)

-- Testing fgetcsv() with file opened using a+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(17) "-water--fruit-air"
}
int(18)
bool(false)

-- Testing fgetcsv() with file opened using r mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(21) "-water---fruit---air-"
}
int(22)
bool(false)

-- Testing fgetcsv() with file opened using rb mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(21) "-water---fruit---air-"
}
int(22)
bool(false)

-- Testing fgetcsv() with file opened using rt mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(21) "-water---fruit---air-"
}
int(22)
bool(false)

-- Testing fgetcsv() with file opened using r+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(21) "-water---fruit---air-"
}
int(22)
bool(false)

-- Testing fgetcsv() with file opened using r+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(21) "-water---fruit---air-"
}
int(22)
bool(false)

-- Testing fgetcsv() with file opened using r+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(21) "-water---fruit---air-"
}
int(22)
bool(false)

-- Testing fgetcsv() with file opened using a+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(21) "-water---fruit---air-"
}
int(22)
bool(false)

-- Testing fgetcsv() with file opened using a+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(21) "-water---fruit---air-"
}
int(22)
bool(false)

-- Testing fgetcsv() with file opened using a+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(21) "-water---fruit---air-"
}
int(22)
bool(false)

-- Testing fgetcsv() with file opened using r mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(23) "&""""&:&"&:,:":&,&:,,,,"
}
int(24)
bool(false)

-- Testing fgetcsv() with file opened using rb mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(23) "&""""&:&"&:,:":&,&:,,,,"
}
int(24)
bool(false)

-- Testing fgetcsv() with file opened using rt mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(23) "&""""&:&"&:,:":&,&:,,,,"
}
int(24)
bool(false)

-- Testing fgetcsv() with file opened using r+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(23) "&""""&:&"&:,:":&,&:,,,,"
}
int(24)
bool(false)

-- Testing fgetcsv() with file opened using r+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(23) "&""""&:&"&:,:":&,&:,,,,"
}
int(24)
bool(false)

-- Testing fgetcsv() with file opened using r+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(23) "&""""&:&"&:,:":&,&:,,,,"
}
int(24)
bool(false)

-- Testing fgetcsv() with file opened using a+ mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(23) "&""""&:&"&:,:":&,&:,,,,"
}
int(24)
bool(false)

-- Testing fgetcsv() with file opened using a+b mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(23) "&""""&:&"&:,:":&,&:,,,,"
}
int(24)
bool(false)

-- Testing fgetcsv() with file opened using a+t mode --

Notice: fgetcsv(): delimiter must be a single character in %s on line %d

Notice: fgetcsv(): enclosure must be a single character in %s on line %d
array(1) {
  [0]=>
  string(23) "&""""&:&"&:,:":&,&:,,,,"
}
int(24)
bool(false)
Done