*** Testing fgetcsv() : with delimiter as NULL ***

-- Testing fgetcsv() with file opened using r mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using rb mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using rt mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using a+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using a+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using a+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using w+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using w+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using w+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using x+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using x+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using x+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using rb mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using rt mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using a+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using a+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using a+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using w+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using w+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using w+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using x+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using x+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using x+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using rb mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using rt mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using a+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using a+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using a+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using w+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using w+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using w+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using x+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using x+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using x+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using rb mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using rt mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using a+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using a+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using a+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using w+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using w+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using w+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using x+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using x+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using x+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using rb mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using rt mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using a+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using a+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using a+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using w+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using w+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using w+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using x+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using x+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using x+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using rb mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using rt mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using a+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using a+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using a+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using w+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using w+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using w+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using x+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using x+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using x+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using rb mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using rt mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using a+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using a+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using a+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using w+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using w+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using w+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using x+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using x+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using x+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using rb mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using rt mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using r+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using a+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using a+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using a+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using w+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using w+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using w+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using x+ mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using x+b mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)

-- Testing fgetcsv() with file opened using x+t mode --

Warning: fgetcsv(): delimiter must be a character in %s on line %d
bool(false)
int(0)
bool(false)
Done