*** Testing error conditions ***
-- Testing fgetcsv() with zero argument --

Warning: fgetcsv() expects at least 1 parameter, 0 given in %s on line %d
NULL
-- Testing fgetcsv() with more than expected number of arguments --

Warning: fgetcsv() expects at most 5 parameters, 6 given in %s on line %d
NULL
-- Testing fgetcsv() with invalid arguments --
-- Iteration 1 --

Warning: fgetcsv() expects parameter 1 to be resource, string given in %s on line %d
NULL

Warning: fgetcsv() expects parameter 1 to be resource, string given in %s on line %d
NULL
-- Iteration 2 --

Warning: fgetcsv() expects parameter 1 to be resource, integer given in %s on line %d
NULL

Warning: fgetcsv() expects parameter 1 to be resource, integer given in %s on line %d
NULL
-- Iteration 3 --

Warning: fgetcsv() expects parameter 1 to be resource, float given in %s on line %d
NULL

Warning: fgetcsv() expects parameter 1 to be resource, float given in %s on line %d
NULL
-- Iteration 4 --

Warning: fgetcsv() expects parameter 1 to be resource, boolean given in %s on line %d
NULL

Warning: fgetcsv() expects parameter 1 to be resource, boolean given in %s on line %d
NULL
-- Iteration 5 --

Warning: fgetcsv() expects parameter 1 to be resource, array given in %s on line %d
NULL

Warning: fgetcsv() expects parameter 1 to be resource, array given in %s on line %d
NULL
-- Iteration 6 --

Warning: fgetcsv() expects parameter 1 to be resource, object given in %s on line %d
NULL

Warning: fgetcsv() expects parameter 1 to be resource, object given in %s on line %d
NULL
Done