*** Testing error conditions ***
-- Testing fgetc() with zero argument --

Warning: fgetc() expects exactly 1 parameter, 0 given in %s on line %d
bool(false)
-- Testing fgetc() with more than expected number of arguments --

Warning: fgetc() expects exactly 1 parameter, 2 given in %s on line %d
bool(false)
-- Testing fgetc() with invalid arguments --
-- Iteration 1 --

Warning: fgetc() expects parameter 1 to be resource, string given in %s on line %d
bool(false)
-- Iteration 2 --

Warning: fgetc() expects parameter 1 to be resource, integer given in %s on line %d
bool(false)
-- Iteration 3 --

Warning: fgetc() expects parameter 1 to be resource, float given in %s on line %d
bool(false)
-- Iteration 4 --

Warning: fgetc() expects parameter 1 to be resource, boolean given in %s on line %d
bool(false)
-- Iteration 5 --

Warning: fgetc() expects parameter 1 to be resource, array given in %s on line %d
bool(false)
-- Iteration 6 --

Warning: fgetc() expects parameter 1 to be resource, object given in %s on line %d
bool(false)
Done