*** Testing filegroup() with different notations of file names ***
- Iteration 1 -
int(%d)
- Iteration 2 -

Warning: filegroup(): stat failed for %s//filegroup_variation3/filegroup_variation3.tmp/ in %s on line %d
bool(false)
- Iteration 3 -
int(%d)
- Iteration 4 -
int(%d)
- Iteration 5 -

Warning: filegroup(): stat failed for %s//filegroup_variation3/*.tmp in %s on line %d
bool(false)
- Iteration 6 -

Warning: filegroup(): stat failed for %s/filegroup_variation3/filegroup*.tmp in %s on line %d
bool(false)
- Iteration 7 -

Warning: filegroup() expects parameter 1 to be a valid path, string given in %s on line %d
NULL
- Iteration 8 -

Warning: filegroup() expects parameter 1 to be a valid path, string given in %s on line %d
NULL

*** Done ***