*** Testing fileinode() with different notations of file names ***
- Iteration 1 -
int(%i)
- Iteration 2 -

Warning: fileinode(): stat failed for %s//fileinode_variation3/fileinode_variation3.tmp/ in %s on line %d
bool(false)
- Iteration 3 -
int(%i)
- Iteration 4 -
int(%i)
- Iteration 5 -

Warning: fileinode(): stat failed for %s//fileinode_variation3/*.tmp in %s on line %d
bool(false)
- Iteration 6 -

Warning: fileinode(): stat failed for %s/fileinode_variation3/fileinode*.tmp in %s on line %d
bool(false)
- Iteration 7 -

Warning: fileinode() expects parameter 1 to be a valid path, string given in %s on line %d
NULL
- Iteration 8 -

Warning: fileinode() expects parameter 1 to be a valid path, string given in %s on line %d
NULL

*** Done ***