*** Testing file_get_contents() : variation ***
-- Iteration 0 --

Warning: file_get_contents(-1): failed to open stream: No such file or directory in %s on line %d
bool(false)
-- Iteration 1 --

Warning: file_get_contents(1): failed to open stream: No such file or directory in %s on line %d
bool(false)
-- Iteration 2 --

Warning: file_get_contents(): Filename cannot be empty in %s on line %d
bool(false)
-- Iteration 3 --

Warning: file_get_contents(): Filename cannot be empty in %s on line %d
bool(false)
-- Iteration 4 --

Warning: file_get_contents(): Filename cannot be empty in %s on line %d
bool(false)
-- Iteration 5 --

Warning: file_get_contents( ): failed to open stream: No such file or directory in %s on line %d
bool(false)
-- Iteration 6 --

Warning: file_get_contents() expects parameter 1 to be a valid path, string given in %s on line %d
NULL
-- Iteration 7 --

Warning: file_get_contents() expects parameter 1 to be a valid path, array given in %s on line %d
NULL
-- Iteration 8 --

Warning: file_get_contents(/no/such/file/dir): failed to open stream: No such file or directory in %s on line %d
bool(false)
-- Iteration 9 --

Warning: file_get_contents(php/php): failed to open stream: No such file or directory in %s on line %d
bool(false)

*** Done ***