int(%d)
int(%d)
int(%d)
int(%d)
int(%d)
int(%d)
int(%d)
int(%d)
int(%d)
int(%d)
int(%d)
int(%d)
int(%d)
int(%d)
int(%d)

Warning: fileinode(): stat failed for /no/such/file/or/dir in %s on line %d
bool(false)

Warning: fileowner(): stat failed for /no/such/file/or/dir in %s on line %d
bool(false)

Warning: filegroup(): stat failed for /no/such/file/or/dir in %s on line %d
bool(false)

Warning: fileatime(): stat failed for /no/such/file/or/dir in %s on line %d
bool(false)

Warning: filectime(): stat failed for /no/such/file/or/dir in %s on line %d
bool(false)
Done