*** Testing fileperms() with different notations of file names ***
- Iteration 1 -
int(%d)
- Iteration 2 -

Warning: fileperms(): stat failed for %s//fileperms_variation3/fileperms_variation3.tmp/ in %s on line %d
bool(false)
- Iteration 3 -
int(%d)
- Iteration 4 -
int(%d)
- Iteration 5 -

Warning: fileperms(): stat failed for %s//fileperms_variation3/*.tmp in %s on line %d
bool(false)
- Iteration 6 -

Warning: fileperms(): stat failed for %s/fileperms_variation3/fileperms*.tmp in %s on line %d
bool(false)
- Iteration 7 -

Warning: fileperms() expects parameter 1 to be a valid path, string given in %s on line %d
NULL
- Iteration 8 -

Warning: fileperms() expects parameter 1 to be a valid path, string given in %s on line %d
NULL

*** Done ***