*** Testing error conditions ***

--- Iteration 0 ---
Warning: flock(): Illegal operation argument in %s on line %d
bool(false)

--- Iteration 1 ---
Warning: flock(): Illegal operation argument in %s on line %d
bool(false)

--- Iteration 2 ---
Warning: flock(): Illegal operation argument in %s on line %d
bool(false)

--- Iteration 3 ---
Warning: flock(): Illegal operation argument in %s on line %d
bool(false)

--- Iteration 4 ---
Warning: flock() expects parameter 2 to be integer, array given in %s on line %d
NULL

--- Iteration 5 ---
Warning: flock() expects parameter 2 to be integer, array given in %s on line %d
NULL

--- Iteration 6 ---
Warning: flock() expects parameter 2 to be integer, string given in %s on line %d
NULL

--- Iteration 7 ---
Warning: flock() expects parameter 2 to be integer, string given in %s on line %d
NULL

--- Iteration 8 ---
Warning: flock() expects parameter 2 to be integer, string given in %s on line %d
NULL

Warning: flock(): supplied resource is not a valid stream resource in %s on line %d
bool(false)

Warning: flock() expects parameter 1 to be resource, string given in %s on line %d
NULL

Warning: flock() expects at least 2 parameters, 0 given in %s on line %d
NULL

Warning: flock() expects at least 2 parameters, 1 given in %s on line %d
NULL

Warning: flock() expects at most 3 parameters, 4 given in %s on line %d
NULL

*** Done ***