*** Testing fnmatch() with file and various patterns ***
-- Iteration 0 --
bool(true)
-- Iteration 1 --
bool(false)
-- Iteration 2 --
bool(false)
-- Iteration 3 --
bool(false)
-- Iteration 4 --
bool(false)
-- Iteration 5 --
bool(false)
-- Iteration 6 --
bool(true)
-- Iteration 7 --
bool(true)
-- Iteration 8 --
bool(false)
-- Iteration 9 --
bool(true)
-- Iteration 10 --
bool(false)
-- Iteration 11 --
bool(false)
-- Iteration 12 --
bool(false)
-- Iteration 13 --
bool(false)
-- Iteration 14 --
bool(false)
-- Iteration 15 --
bool(false)
-- Iteration 16 --
bool(false)
-- Iteration 17 --
bool(false)
-- Iteration 18 --
bool(false)
-- Iteration 19 --
bool(false)
-- Iteration 20 --
bool(false)
-- Iteration 21 --
bool(false)
-- Iteration 22 --
bool(false)
-- Iteration 23 --

Warning: fnmatch() expects parameter 1 to be a valid path, string given in %s on line %d
NULL
-- Iteration 24 --

Warning: fnmatch() expects parameter 1 to be a valid path, string given in %s on line %d
NULL
-- Iteration 25 --
bool(false)
-- Iteration 26 --
bool(false)
-- Iteration 27 --
bool(false)
-- Iteration 28 --
bool(false)
-- Iteration 29 --
bool(false)
-- Iteration 30 --
bool(false)
-- Iteration 31 --
bool(true)
-- Iteration 32 --
bool(false)
-- Iteration 33 --
bool(true)
-- Iteration 34 --
bool(false)
-- Iteration 35 --
bool(false)
-- Iteration 36 --
bool(false)

*** Testing fnmatch() with other types other than files ***
--- With Integers ---
-- Iteration 0 --
bool(true)
bool(true)
bool(true)
bool(false)
bool(false)
bool(false)
-- Iteration 1 --
bool(true)
bool(true)
bool(true)
bool(false)
bool(false)
bool(false)
-- Iteration 2 --
bool(true)
bool(true)
bool(true)
bool(false)
bool(false)
bool(false)
-- Iteration 3 --
bool(false)
bool(false)
bool(false)
bool(true)
bool(false)
bool(false)
-- Iteration 4 --
bool(false)
bool(false)
bool(false)
bool(false)
bool(true)
bool(false)
-- Iteration 5 --
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(true)

--- With Strings ---
-- Iteration 0 --
bool(true)

Warning: fnmatch() expects parameter 2 to be a valid path, string given in %s on line %d
NULL
bool(true)

Warning: fnmatch() expects parameter 2 to be a valid path, string given in %s on line %d
NULL
bool(false)
bool(true)
-- Iteration 1 --

Warning: fnmatch() expects parameter 1 to be a valid path, string given in %s on line %d
NULL

Warning: fnmatch() expects parameter 1 to be a valid path, string given in %s on line %d
NULL

Warning: fnmatch() expects parameter 1 to be a valid path, string given in %s on line %d
NULL

Warning: fnmatch() expects parameter 1 to be a valid path, string given in %s on line %d
NULL

Warning: fnmatch() expects parameter 1 to be a valid path, string given in %s on line %d
NULL

Warning: fnmatch() expects parameter 1 to be a valid path, string given in %s on line %d
NULL
-- Iteration 2 --
bool(true)

Warning: fnmatch() expects parameter 2 to be a valid path, string given in %s on line %d
NULL
bool(true)

Warning: fnmatch() expects parameter 2 to be a valid path, string given in %s on line %d
NULL
bool(false)
bool(true)
-- Iteration 3 --

Warning: fnmatch() expects parameter 1 to be a valid path, string given in %s on line %d
NULL

Warning: fnmatch() expects parameter 1 to be a valid path, string given in %s on line %d
NULL

Warning: fnmatch() expects parameter 1 to be a valid path, string given in %s on line %d
NULL

Warning: fnmatch() expects parameter 1 to be a valid path, string given in %s on line %d
NULL

Warning: fnmatch() expects parameter 1 to be a valid path, string given in %s on line %d
NULL

Warning: fnmatch() expects parameter 1 to be a valid path, string given in %s on line %d
NULL
-- Iteration 4 --
bool(false)

Warning: fnmatch() expects parameter 2 to be a valid path, string given in %s on line %d
NULL
bool(false)

Warning: fnmatch() expects parameter 2 to be a valid path, string given in %s on line %d
NULL
bool(true)
bool(false)
-- Iteration 5 --
bool(true)

Warning: fnmatch() expects parameter 2 to be a valid path, string given in %s on line %d
NULL
bool(true)

Warning: fnmatch() expects parameter 2 to be a valid path, string given in %s on line %d
NULL
bool(false)
bool(true)

--- With booleans ---
-- Iteration 0 --
bool(true)
bool(true)
bool(true)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
-- Iteration 1 --
bool(true)
bool(true)
bool(true)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
-- Iteration 2 --
bool(true)
bool(true)
bool(true)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
-- Iteration 3 --
bool(false)
bool(false)
bool(false)
bool(true)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
-- Iteration 4 --
bool(false)
bool(false)
bool(false)
bool(false)
bool(true)
bool(true)
bool(false)
bool(true)
bool(false)
-- Iteration 5 --
bool(false)
bool(false)
bool(false)
bool(false)
bool(true)
bool(true)
bool(false)
bool(true)
bool(false)
-- Iteration 6 --
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(true)
bool(false)
bool(false)
-- Iteration 7 --
bool(false)
bool(false)
bool(false)
bool(false)
bool(true)
bool(true)
bool(false)
bool(true)
bool(false)
-- Iteration 8 --
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
bool(true)

--- With NULL ---
-- Iteration 0 --
bool(true)
bool(true)
bool(true)

Warning: fnmatch() expects parameter 2 to be a valid path, string given in %s on line %d
NULL
bool(false)
bool(false)
-- Iteration 1 --
bool(true)
bool(true)
bool(true)

Warning: fnmatch() expects parameter 2 to be a valid path, string given in %s on line %d
NULL
bool(false)
bool(false)
-- Iteration 2 --
bool(true)
bool(true)
bool(true)

Warning: fnmatch() expects parameter 2 to be a valid path, string given in %s on line %d
NULL
bool(false)
bool(false)
-- Iteration 3 --

Warning: fnmatch() expects parameter 1 to be a valid path, string given in %s on line %d
NULL

Warning: fnmatch() expects parameter 1 to be a valid path, string given in %s on line %d
NULL

Warning: fnmatch() expects parameter 1 to be a valid path, string given in %s on line %d
NULL

Warning: fnmatch() expects parameter 1 to be a valid path, string given in %s on line %d
NULL

Warning: fnmatch() expects parameter 1 to be a valid path, string given in %s on line %d
NULL

Warning: fnmatch() expects parameter 1 to be a valid path, string given in %s on line %d
NULL
-- Iteration 4 --
bool(false)
bool(false)
bool(false)

Warning: fnmatch() expects parameter 2 to be a valid path, string given in %s on line %d
NULL
bool(true)
bool(false)
-- Iteration 5 --
bool(false)
bool(false)
bool(false)

Warning: fnmatch() expects parameter 2 to be a valid path, string given in %s on line %d
NULL
bool(false)
bool(true)

*** Done ***