*** Testing error conditions for fnmatch() ***
Warning: fnmatch() expects parameter 1 to be a valid path, array given in %s on line %d
NULL

Warning: fnmatch() expects parameter 1 to be a valid path, resource given in %s on line %d
NULL

Warning: fnmatch() expects parameter 1 to be a valid path, object given in %s on line %d
NULL

Warning: fnmatch() expects at least 2 parameters, 1 given in %s on line %d%d
NULL

Warning: fnmatch() expects at least 2 parameters, 1 given in %s on line %d%d
NULL

Warning: fnmatch() expects at most 3 parameters, 4 given in %s on line %d%d
NULL

*** Done ***