*** Testing fputcsv() : with default enclosure & delimiter of two chars ***

-- file opened in r+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(12)
int(12)
bool(false)
string(12) "water,fruit
"

-- file opened in r+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(12)
int(12)
bool(false)
string(12) "water,fruit
"

-- file opened in r+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(12)
int(12)
bool(false)
string(%d) "water,fruit
"

-- file opened in a+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(12)
int(12)
bool(false)
string(12) "water,fruit
"

-- file opened in a+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(12)
int(12)
bool(false)
string(12) "water,fruit
"

-- file opened in a+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(12)
int(12)
bool(false)
string(%d) "water,fruit
"

-- file opened in w+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(12)
int(12)
bool(false)
string(12) "water,fruit
"

-- file opened in w+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(12)
int(12)
bool(false)
string(12) "water,fruit
"

-- file opened in w+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(12)
int(12)
bool(false)
string(%d) "water,fruit
"

-- file opened in x+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(12)
int(12)
bool(false)
string(12) "water,fruit
"

-- file opened in x+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(12)
int(12)
bool(false)
string(12) "water,fruit
"

-- file opened in x+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(12)
int(12)
bool(false)
string(%d) "water,fruit
"

-- file opened in r+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(20)
int(20)
bool(false)
string(20) """"water"",""fruit"
"

-- file opened in r+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(20)
int(20)
bool(false)
string(20) """"water"",""fruit"
"

-- file opened in r+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(20)
int(20)
bool(false)
string(%d) """"water"",""fruit"
"

-- file opened in a+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(20)
int(20)
bool(false)
string(20) """"water"",""fruit"
"

-- file opened in a+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(20)
int(20)
bool(false)
string(20) """"water"",""fruit"
"

-- file opened in a+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(20)
int(20)
bool(false)
string(%d) """"water"",""fruit"
"

-- file opened in w+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(20)
int(20)
bool(false)
string(20) """"water"",""fruit"
"

-- file opened in w+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(20)
int(20)
bool(false)
string(20) """"water"",""fruit"
"

-- file opened in w+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(20)
int(20)
bool(false)
string(%d) """"water"",""fruit"
"

-- file opened in x+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(20)
int(20)
bool(false)
string(20) """"water"",""fruit"
"

-- file opened in x+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(20)
int(20)
bool(false)
string(20) """"water"",""fruit"
"

-- file opened in x+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(20)
int(20)
bool(false)
string(%d) """"water"",""fruit"
"

-- file opened in r+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(22)
int(22)
bool(false)
string(22) """"water"",""fruit"""
"

-- file opened in r+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(22)
int(22)
bool(false)
string(22) """"water"",""fruit"""
"

-- file opened in r+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(22)
int(22)
bool(false)
string(%d) """"water"",""fruit"""
"

-- file opened in a+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(22)
int(22)
bool(false)
string(22) """"water"",""fruit"""
"

-- file opened in a+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(22)
int(22)
bool(false)
string(22) """"water"",""fruit"""
"

-- file opened in a+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(22)
int(22)
bool(false)
string(%d) """"water"",""fruit"""
"

-- file opened in w+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(22)
int(22)
bool(false)
string(22) """"water"",""fruit"""
"

-- file opened in w+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(22)
int(22)
bool(false)
string(22) """"water"",""fruit"""
"

-- file opened in w+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(22)
int(22)
bool(false)
string(%d) """"water"",""fruit"""
"

-- file opened in x+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(22)
int(22)
bool(false)
string(22) """"water"",""fruit"""
"

-- file opened in x+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(22)
int(22)
bool(false)
string(22) """"water"",""fruit"""
"

-- file opened in x+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(22)
int(22)
bool(false)
string(%d) """"water"",""fruit"""
"

-- file opened in r+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(18)
int(18)
bool(false)
string(18) ""^water^ ^fruit^"
"

-- file opened in r+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(18)
int(18)
bool(false)
string(18) ""^water^ ^fruit^"
"

-- file opened in r+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(18)
int(18)
bool(false)
string(%d) ""^water^ ^fruit^"
"

-- file opened in a+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(18)
int(18)
bool(false)
string(18) ""^water^ ^fruit^"
"

-- file opened in a+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(18)
int(18)
bool(false)
string(18) ""^water^ ^fruit^"
"

-- file opened in a+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(18)
int(18)
bool(false)
string(%d) ""^water^ ^fruit^"
"

-- file opened in w+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(18)
int(18)
bool(false)
string(18) ""^water^ ^fruit^"
"

-- file opened in w+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(18)
int(18)
bool(false)
string(18) ""^water^ ^fruit^"
"

-- file opened in w+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(18)
int(18)
bool(false)
string(%d) ""^water^ ^fruit^"
"

-- file opened in x+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(18)
int(18)
bool(false)
string(18) ""^water^ ^fruit^"
"

-- file opened in x+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(18)
int(18)
bool(false)
string(18) ""^water^ ^fruit^"
"

-- file opened in x+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(18)
int(18)
bool(false)
string(%d) ""^water^ ^fruit^"
"

-- file opened in r+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(16)
int(16)
bool(false)
string(16) "&water&:&fruit&
"

-- file opened in r+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(16)
int(16)
bool(false)
string(16) "&water&:&fruit&
"

-- file opened in r+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(16)
int(16)
bool(false)
string(%d) "&water&:&fruit&
"

-- file opened in a+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(16)
int(16)
bool(false)
string(16) "&water&:&fruit&
"

-- file opened in a+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(16)
int(16)
bool(false)
string(16) "&water&:&fruit&
"

-- file opened in a+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(16)
int(16)
bool(false)
string(%d) "&water&:&fruit&
"

-- file opened in w+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(16)
int(16)
bool(false)
string(16) "&water&:&fruit&
"

-- file opened in w+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(16)
int(16)
bool(false)
string(16) "&water&:&fruit&
"

-- file opened in w+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(16)
int(16)
bool(false)
string(%d) "&water&:&fruit&
"

-- file opened in x+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(16)
int(16)
bool(false)
string(16) "&water&:&fruit&
"

-- file opened in x+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(16)
int(16)
bool(false)
string(16) "&water&:&fruit&
"

-- file opened in x+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(16)
int(16)
bool(false)
string(%d) "&water&:&fruit&
"

-- file opened in r+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(16)
int(16)
bool(false)
string(16) "=water===fruit=
"

-- file opened in r+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(16)
int(16)
bool(false)
string(16) "=water===fruit=
"

-- file opened in r+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(16)
int(16)
bool(false)
string(%d) "=water===fruit=
"

-- file opened in a+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(16)
int(16)
bool(false)
string(16) "=water===fruit=
"

-- file opened in a+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(16)
int(16)
bool(false)
string(16) "=water===fruit=
"

-- file opened in a+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(16)
int(16)
bool(false)
string(%d) "=water===fruit=
"

-- file opened in w+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(16)
int(16)
bool(false)
string(16) "=water===fruit=
"

-- file opened in w+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(16)
int(16)
bool(false)
string(16) "=water===fruit=
"

-- file opened in w+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(16)
int(16)
bool(false)
string(%d) "=water===fruit=
"

-- file opened in x+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(16)
int(16)
bool(false)
string(16) "=water===fruit=
"

-- file opened in x+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(16)
int(16)
bool(false)
string(16) "=water===fruit=
"

-- file opened in x+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(16)
int(16)
bool(false)
string(%d) "=water===fruit=
"

-- file opened in r+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(18)
int(18)
bool(false)
string(18) "-water--fruit-air
"

-- file opened in r+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(18)
int(18)
bool(false)
string(18) "-water--fruit-air
"

-- file opened in r+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(18)
int(18)
bool(false)
string(%d) "-water--fruit-air
"

-- file opened in a+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(18)
int(18)
bool(false)
string(18) "-water--fruit-air
"

-- file opened in a+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(18)
int(18)
bool(false)
string(18) "-water--fruit-air
"

-- file opened in a+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(18)
int(18)
bool(false)
string(%d) "-water--fruit-air
"

-- file opened in w+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(18)
int(18)
bool(false)
string(18) "-water--fruit-air
"

-- file opened in w+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(18)
int(18)
bool(false)
string(18) "-water--fruit-air
"

-- file opened in w+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(18)
int(18)
bool(false)
string(%d) "-water--fruit-air
"

-- file opened in x+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(18)
int(18)
bool(false)
string(18) "-water--fruit-air
"

-- file opened in x+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(18)
int(18)
bool(false)
string(18) "-water--fruit-air
"

-- file opened in x+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(18)
int(18)
bool(false)
string(%d) "-water--fruit-air
"

-- file opened in r+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(22)
int(22)
bool(false)
string(22) "-water---fruit---air-
"

-- file opened in r+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(22)
int(22)
bool(false)
string(22) "-water---fruit---air-
"

-- file opened in r+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(22)
int(22)
bool(false)
string(%d) "-water---fruit---air-
"

-- file opened in a+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(22)
int(22)
bool(false)
string(22) "-water---fruit---air-
"

-- file opened in a+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(22)
int(22)
bool(false)
string(22) "-water---fruit---air-
"

-- file opened in a+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(22)
int(22)
bool(false)
string(%d) "-water---fruit---air-
"

-- file opened in w+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(22)
int(22)
bool(false)
string(22) "-water---fruit---air-
"

-- file opened in w+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(22)
int(22)
bool(false)
string(22) "-water---fruit---air-
"

-- file opened in w+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(22)
int(22)
bool(false)
string(%d) "-water---fruit---air-
"

-- file opened in x+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(22)
int(22)
bool(false)
string(22) "-water---fruit---air-
"

-- file opened in x+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(22)
int(22)
bool(false)
string(22) "-water---fruit---air-
"

-- file opened in x+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(22)
int(22)
bool(false)
string(%d) "-water---fruit---air-
"

-- file opened in r+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(32)
int(32)
bool(false)
string(32) ""&""""""""&:&""&:,:"":&,&:,,,,"
"

-- file opened in r+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(32)
int(32)
bool(false)
string(32) ""&""""""""&:&""&:,:"":&,&:,,,,"
"

-- file opened in r+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(32)
int(32)
bool(false)
string(%d) ""&""""""""&:&""&:,:"":&,&:,,,,"
"

-- file opened in a+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(32)
int(32)
bool(false)
string(32) ""&""""""""&:&""&:,:"":&,&:,,,,"
"

-- file opened in a+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(32)
int(32)
bool(false)
string(32) ""&""""""""&:&""&:,:"":&,&:,,,,"
"

-- file opened in a+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(32)
int(32)
bool(false)
string(%d) ""&""""""""&:&""&:,:"":&,&:,,,,"
"

-- file opened in w+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(32)
int(32)
bool(false)
string(32) ""&""""""""&:&""&:,:"":&,&:,,,,"
"

-- file opened in w+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(32)
int(32)
bool(false)
string(32) ""&""""""""&:&""&:,:"":&,&:,,,,"
"

-- file opened in w+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(32)
int(32)
bool(false)
string(%d) ""&""""""""&:&""&:,:"":&,&:,,,,"
"

-- file opened in x+ --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(32)
int(32)
bool(false)
string(32) ""&""""""""&:&""&:,:"":&,&:,,,,"
"

-- file opened in x+b --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(32)
int(32)
bool(false)
string(32) ""&""""""""&:&""&:,:"":&,&:,,,,"
"

-- file opened in x+t --

Notice: fputcsv(): delimiter must be a single character in %s on line %d
int(32)
int(32)
bool(false)
string(%d) ""&""""""""&:&""&:,:"":&,&:,,,,"
"
Done