*** Testing fputcsv() : with enclosure as NULL ***

-- file opened in r+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in r+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in a+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in w+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+ --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+b --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""

-- file opened in x+t --

Warning: fputcsv(): enclosure must be a character in %s on line %d
bool(false)
int(0)
bool(false)
string(0) ""
Done