*** Testing fputcsv() : with enclosure & delimiter of two chars and file opened in read mode ***

-- file opened in r --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in rb --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in rt --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in r --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in rb --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in rt --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in r --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in rb --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in rt --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in r --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in rb --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in rt --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in r --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in rb --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in rt --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in r --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in rb --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in rt --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in r --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in rb --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in rt --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in r --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in rb --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in rt --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in r --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in rb --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""

-- file opened in rt --

Notice: fputcsv(): delimiter must be a single character in %s on line %d

Notice: fputcsv(): enclosure must be a single character in %s on line %d
int(0)
int(0)
bool(false)
string(0) ""
Done