*** Testing fscanf() for error conditions ***

Warning: fscanf() expects at least 2 parameters, 0 given in %s on line %d
NULL

Warning: fscanf() expects at least 2 parameters, 1 given in %s on line %d
NULL

Warning: fscanf(): supplied resource is not a valid File-Handle resource in %s on line %d
bool(false)

Warning: fscanf(): Different numbers of variable names and field specifiers in %s on line %d
int(-1)

Notice: Undefined variable: undefined_var in %s on line %d

Notice: Use of undefined constant undefined_constant - assumed 'undefined_constant' in %s on line %d
array(0) {
}
array(0) {
}

Warning: fscanf(): Bad scan conversion character " in %s on line %d
NULL

Warning: fscanf(): Bad scan conversion character " in %s on line %d
NULL

Warning: fscanf(): Bad scan conversion character "." in %s on line %d
NULL

Warning: fscanf(): Bad scan conversion character "m" in %s on line %d
NULL

*** Done ***