*** Testing fseek() : usage variations ***

Arg value 10.5 
int(0)
int(10)

Arg value -10.5 
int(-1)
int(10)

Arg value 1.07654321E-9 
int(0)
int(0)

Arg value 0.5 
int(0)
int(0)

Arg value Array 

Warning: fseek() expects parameter 2 to be integer, array given in %s on line %d
bool(false)
int(0)

Arg value Array 

Warning: fseek() expects parameter 2 to be integer, array given in %s on line %d
bool(false)
int(0)

Arg value Array 

Warning: fseek() expects parameter 2 to be integer, array given in %s on line %d
bool(false)
int(0)

Arg value Array 

Warning: fseek() expects parameter 2 to be integer, array given in %s on line %d
bool(false)
int(0)

Arg value Array 

Warning: fseek() expects parameter 2 to be integer, array given in %s on line %d
bool(false)
int(0)

Arg value  
int(0)
int(0)

Arg value  
int(0)
int(0)

Arg value 1 
int(0)
int(1)

Arg value  
int(0)
int(0)

Arg value 1 
int(0)
int(1)

Arg value  
int(0)
int(0)

Arg value  

Warning: fseek() expects parameter 2 to be integer, string given in %s on line %d
bool(false)
int(0)

Arg value  

Warning: fseek() expects parameter 2 to be integer, string given in %s on line %d
bool(false)
int(0)

Arg value string 

Warning: fseek() expects parameter 2 to be integer, string given in %s on line %d
bool(false)
int(0)

Arg value string 

Warning: fseek() expects parameter 2 to be integer, string given in %s on line %d
bool(false)
int(0)

Arg value testClass 

Warning: fseek() expects parameter 2 to be integer, object given in %s on line %d
bool(false)
int(0)

Arg value  
int(0)
int(0)

Arg value  
int(0)
int(0)
Done