*** Testing fseek() : error conditions ***
-- Testing fseek() with zero argument --

Warning: fseek() expects at least 2 parameters, 0 given in %s on line %d
bool(false)
-- Testing fseek() with unexpected number of arguments --

Warning: fseek() expects at least 2 parameters, 1 given in %s on line %d
bool(false)

Warning: fseek() expects at most 3 parameters, 4 given in %s on line %d
bool(false)
-- Testing fseek() with invalid arguments --
-- Iteration 1 --

Warning: fseek() expects parameter 1 to be resource, string given in %s on line %d
bool(false)
-- Iteration 2 --

Warning: fseek() expects parameter 1 to be resource, integer given in %s on line %d
bool(false)
-- Iteration 3 --

Warning: fseek() expects parameter 1 to be resource, float given in %s on line %d
bool(false)
-- Iteration 4 --

Warning: fseek() expects parameter 1 to be resource, boolean given in %s on line %d
bool(false)
-- Iteration 5 --

Warning: fseek() expects parameter 1 to be resource, array given in %s on line %d
bool(false)
-- Iteration 6 --

Warning: fseek() expects parameter 1 to be resource, object given in %s on line %d
bool(false)
-- Testing fseek() with closed/unset file handle --
Warning: fseek(): supplied resource is not a valid stream resource in %s on line %d
bool(false)

Warning: fseek() expects parameter 1 to be resource, null given in %s on line %d
bool(false)
Done