*** Testing fseek() : usage variations ***

Arg value -100 
int(-1)
int(0)

Arg value 100 
int(-1)
int(0)

Arg value 10.5 
int(-1)
int(0)

Arg value -10.5 
int(-1)
int(0)

Arg value 101234567000 
int(-1)
int(0)

Arg value 1.07654321E-9 
int(0)
int(3)

Arg value 0.5 
int(0)
int(3)

Arg value  
int(0)
int(3)

Arg value  
int(0)
int(3)

Arg value 1 
int(0)
int(6)

Arg value  
int(0)
int(3)

Arg value 1 
int(0)
int(6)

Arg value  
int(0)
int(3)

Arg value  

Warning: fseek() expects parameter 3 to be integer, string given in %s on line %d
bool(false)
int(3)

Arg value  

Warning: fseek() expects parameter 3 to be integer, string given in %s on line %d
bool(false)
int(3)

Arg value string 

Warning: fseek() expects parameter 3 to be integer, string given in %s on line %d
bool(false)
int(3)

Arg value string 

Warning: fseek() expects parameter 3 to be integer, string given in %s on line %d
bool(false)
int(3)

Arg value  
int(0)
int(3)

Arg value  
int(0)
int(3)
Done