Warning: fstat() expects parameter 1 to be resource, null given in %s on line %d
bool(false)

Warning: fstat() expects parameter 1 to be resource, null given in %s on line %d
bool(false)

Warning: fstat() expects parameter 1 to be resource, string given in %s on line %d
bool(false)

Warning: fstat() expects parameter 1 to be resource, string given in %s on line %d
bool(false)

Warning: fstat() expects parameter 1 to be resource, null given in %s on line %d
bool(false)

Warning: fstat() expects parameter 1 to be resource, null given in %s on line %d
bool(false)
===DONE===