Warning: fwrite() expects at least 2 parameters, 1 given in %s on line %d
bool(false)

Warning: fwrite() expects parameter 2 to be string, array given in %s on line %d
bool(false)
int(0)
int(0)
int(4)
int(0)

Warning: fwrite() expects parameter 1 to be resource, array given in %s on line %d
bool(false)

Warning: fwrite() expects parameter 1 to be resource, array given in %s on line %d
bool(false)

Warning: fwrite() expects at least 2 parameters, 1 given in %s on line %d
bool(false)
string(4) "data"
Done