*** Testing is_executable(): usage variations ***
-- Iteration 1 --
bool(false)
-- Iteration 2 --
bool(false)
-- Iteration 3 --
bool(false)
-- Iteration 4 --
bool(false)
-- Iteration 5 --
bool(false)
-- Iteration 6 --

Warning: is_executable() expects parameter 1 to be a valid path, string given in %s on line %d
NULL
-- Iteration 7 --

Warning: is_executable() expects parameter 1 to be a valid path, string given in %s on line %d
NULL
-- Iteration 8 --
bool(false)
-- Iteration 9 --
bool(true)
-- Iteration 10 --
bool(true)
Done