*** Testing is_file() with different notations of file names ***
- Iteration 1 -
bool(true)
- Iteration 2 -
bool(false)
- Iteration 3 -
bool(true)
- Iteration 4 -
bool(true)
- Iteration 5 -
bool(false)
- Iteration 6 -
bool(false)
- Iteration 7 -

Warning: is_file() expects parameter 1 to be a valid path, string given in %s on line %d
NULL
- Iteration 8 -

Warning: is_file() expects parameter 1 to be a valid path, string given in %s on line %d
NULL

*** Done ***