*** Testing mkdir() : variation ***
-- creating mkdirVar5.tmp/aSubDir --
Directory created
-- creating ./mkdirVar5.tmp/aSubDir --
Directory created
-- creating mkdirVar5.tmp/../mkdirVar5.tmp/aSubDir --
Directory created
-- creating mkdirVar5.tmp/../BADDIR/aSubDir --

Warning: mkdir(): No such file or directory in %s on line %d
-- creating BADDIR/aSubDir --

Warning: mkdir(): No such file or directory in %s on line %d
-- creating %s/mkdirVar5.tmp/aSubDir --
Directory created
-- creating %s/./mkdirVar5.tmp/aSubDir --
Directory created
-- creating %s/mkdirVar5.tmp/../mkdirVar5.tmp/aSubDir --
Directory created
-- creating %s/BADDIR/aSubDir --

Warning: mkdir(): No such file or directory in %s on line %d
-- creating mkdirVar5.tmp/aSubDir/ --
Directory created
-- creating %s/mkdirVar5.tmp/aSubDir/ --
Directory created
-- creating mkdirVar5.tmp//aSubDir --
Directory created
-- creating %s//mkdirVar5.tmp//aSubDir --
Directory created
===DONE===