*** Testing parse_ini_file() : error conditions ***

-- Testing parse_ini_file() function with Zero arguments --

Warning: parse_ini_file() expects at least 1 parameter, 0 given in %s on line %d
bool(false)

-- Testing parse_ini_file() function with more than expected no. of arguments --

Warning: parse_ini_file(%s): failed to open stream: No such file or directory in %s on line %d
bool(false)

-- Testing parse_ini_file() function with a non-existent file --

Warning: parse_ini_file(%s): failed to open stream: No such file or directory in %s on line %d
bool(false)
Done