*** Testing readlink() and realpath() : usage variations ***

*** Testing readlink() and realpath() with linkname as empty string, NULL and single space ***
-- Iteration1 --

Warning: readlink(): %s in %s on line %d
bool(false)
%s
-- Iteration2 --

Warning: readlink(): %s in %s on line %d
bool(false)
%s
-- Iteration3 --

Warning: readlink(): %s in %s on line %d
bool(false)
string(%d) "%s"
-- Iteration4 --

Warning: readlink(): %s in %s on line %d
bool(false)
string(%d) "%s"
-- Iteration5 --

Warning: readlink(): %s in %s on line %d
bool(false)
string(%d) "%s"
-- Iteration6 --

Warning: readlink(): %s in %s on line %d
bool(false)
string(%d) "%s"
Done