Warning: stream_socket_client(): unable to connect to  (Failed to parse address "") in %s on line %d
bool(false)
int(0)
string(26) "Failed to parse address """

Warning: stream_socket_client(): unable to connect to [ (Failed to parse address "[") in %s on line %d
bool(false)
int(0)
string(27) "Failed to parse address "[""

Warning: stream_socket_client(): unable to connect to [  (Failed to parse%saddress "[ ") in %s on line %d
bool(false)
int(0)
string(%d) "Failed to parse%saddress "[ ""

Warning: stream_socket_client(): unable to connect to . (Failed to parse address ".") in %s on line %d
bool(false)
int(0)
string(27) "Failed to parse address ".""

Warning: stream_socket_client(): unable to connect to 1 (Failed to parse address "1") in %s on line %d
bool(false)
int(0)
string(27) "Failed to parse address "1""

Warning: stream_socket_client() expects parameter 1 to be string, array given in %s on line %d
bool(false)
int(0)
string(27) "Failed to parse address "1""
Done