*** Testing tempnam() with obscure prefixes ***
-- Iteration 0 --
File name is => %s/%s
File permissions are => 100600
File created in => directory specified
-- Iteration 1 --
File name is => %s/%s
File permissions are => 100600
File created in => directory specified
-- Iteration 2 --
File name is => %s/%s
File permissions are => 100600
File created in => directory specified
-- Iteration 3 --
File name is => %s/%s
File permissions are => 100600
File created in => directory specified
-- Iteration 4 --
File name is => %s/%s
File permissions are => 100600
File created in => directory specified
-- Iteration 5 --
File name is => %s/%s
File permissions are => 100600
File created in => directory specified
-- Iteration 6 --

Warning: tempnam() expects parameter 2 to be a valid path, string given in %s on line %d
-- File is not created --

Warning: unlink(): %s in %s on line %d
-- Iteration 7 --

Warning: tempnam() expects parameter 2 to be a valid path, array given in %s on line %d
-- File is not created --

Warning: unlink(): %s in %s on line %d
-- Iteration 8 --
File name is => %s/dir%s
File permissions are => 100600
File created in => directory specified
-- Iteration 9 --
File name is => %s/php%s
File permissions are => 100600
File created in => directory specified

*** Done ***