*** Testing unlink() : variation ***
-- removing unlinkVar8.tmp/file.tmp --
file removed
-- unlinking soft link unlinkVar8.tmp/file.tmp --
file unlinked
-- unlinking hard link unlinkVar8.tmp/file.tmp --
file unlinked
-- removing ./unlinkVar8.tmp/file.tmp --
file removed
-- unlinking soft link ./unlinkVar8.tmp/file.tmp --
file unlinked
-- unlinking hard link ./unlinkVar8.tmp/file.tmp --
file unlinked
-- removing unlinkVar8.tmp/../unlinkVar8.tmp/file.tmp --
file removed
-- unlinking soft link unlinkVar8.tmp/../unlinkVar8.tmp/file.tmp --
file unlinked
-- unlinking hard link unlinkVar8.tmp/../unlinkVar8.tmp/file.tmp --
file unlinked
-- removing unlinkVar8.tmp/../BADDIR/file.tmp --

Warning: unlink(unlinkVar8.tmp/../BADDIR/file.tmp): No such file or directory in %s on line %d
-- unlinking soft link unlinkVar8.tmp/../BADDIR/file.tmp --

Warning: unlink(unlinkVar8.tmp/../BADDIR/file.tmp): No such file or directory in %s on line %d
-- unlinking hard link unlinkVar8.tmp/../BADDIR/file.tmp --

Warning: unlink(unlinkVar8.tmp/../BADDIR/file.tmp): No such file or directory in %s on line %d
-- removing BADDIR/file.tmp --

Warning: unlink(BADDIR/file.tmp): No such file or directory in %s on line %d
-- unlinking soft link BADDIR/file.tmp --

Warning: unlink(BADDIR/file.tmp): No such file or directory in %s on line %d
-- unlinking hard link BADDIR/file.tmp --

Warning: unlink(BADDIR/file.tmp): No such file or directory in %s on line %d
-- removing /%s/unlinkVar8.tmp/file.tmp --
file removed
-- unlinking soft link /%s/unlinkVar8.tmp/file.tmp --
file unlinked
-- unlinking hard link /%s/unlinkVar8.tmp/file.tmp --
file unlinked
-- removing /%s/./unlinkVar8.tmp/file.tmp --
file removed
-- unlinking soft link /%s/./unlinkVar8.tmp/file.tmp --
file unlinked
-- unlinking hard link /%s/./unlinkVar8.tmp/file.tmp --
file unlinked
-- removing /%s/unlinkVar8.tmp/../unlinkVar8.tmp/file.tmp --
file removed
-- unlinking soft link /%s/unlinkVar8.tmp/../unlinkVar8.tmp/file.tmp --
file unlinked
-- unlinking hard link /%s/unlinkVar8.tmp/../unlinkVar8.tmp/file.tmp --
file unlinked
-- removing /%s/BADDIR/file.tmp --

Warning: unlink(/%s/BADDIR/file.tmp): No such file or directory in %s on line %d
-- unlinking soft link /%s/BADDIR/file.tmp --

Warning: unlink(/%s/BADDIR/file.tmp): No such file or directory in %s on line %d
-- unlinking hard link /%s/BADDIR/file.tmp --

Warning: unlink(/%s/BADDIR/file.tmp): No such file or directory in %s on line %d
-- removing unlinkVar8.tmp/file.tmp/ --

Warning: unlink(unlinkVar8.tmp/file.tmp/): Not a directory in %s on line %d
-- unlinking soft link unlinkVar8.tmp/file.tmp/ --

Warning: unlink(unlinkVar8.tmp/file.tmp/): %s directory in %s on line %d
-- unlinking hard link unlinkVar8.tmp/file.tmp/ --

Warning: unlink(unlinkVar8.tmp/file.tmp/): Not a directory in %s on line %d
-- removing /%s/unlinkVar8.tmp/file.tmp/ --

Warning: unlink(/%s/unlinkVar8.tmp/file.tmp/): Not a directory in %s on line %d
-- unlinking soft link /%s/unlinkVar8.tmp/file.tmp/ --

Warning: unlink(/%s/unlinkVar8.tmp/file.tmp/): %s directory in %s on line %d
-- unlinking hard link /%s/unlinkVar8.tmp/file.tmp/ --

Warning: unlink(/%s/unlinkVar8.tmp/file.tmp/): Not a directory in %s on line %d
-- removing unlinkVar8.tmp//file.tmp --
file removed
-- unlinking soft link unlinkVar8.tmp//file.tmp --
file unlinked
-- unlinking hard link unlinkVar8.tmp//file.tmp --
file unlinked
-- removing /%s//unlinkVar8.tmp//file.tmp --
file removed
-- unlinking soft link /%s//unlinkVar8.tmp//file.tmp --
file unlinked
-- unlinking hard link /%s//unlinkVar8.tmp//file.tmp --
file unlinked
===DONE===