*** Testing unlink() : variation ***
-- unlinking soft link unlinkVar8.tmp/subDir.tmp --
directory unlinked
-- unlinking soft link ./unlinkVar8.tmp/subDir.tmp --
directory unlinked
-- unlinking soft link unlinkVar8.tmp/../unlinkVar8.tmp/subDir.tmp --
directory unlinked
-- unlinking soft link /%s/unlinkVar8.tmp/subDir.tmp --
directory unlinked
-- unlinking soft link /%s/./unlinkVar8.tmp/subDir.tmp --
directory unlinked
-- unlinking soft link /%s/unlinkVar8.tmp/../unlinkVar8.tmp/subDir.tmp --
directory unlinked
-- unlinking soft link unlinkVar8.tmp//subDir.tmp --
directory unlinked
-- unlinking soft link /%s//unlinkVar8.tmp//subDir.tmp --
directory unlinked

--- try to unlink a directory ---

Warning: unlink(unlinkVar8.tmp/linkme.tmp): %s in %s on line %d
===DONE===