bool(true)
bool(true)
------ stream_lock not implemented: -------

Warning: flock(): test_wrapper_base::stream_lock is not implemented! in %s
bool(false)
------ fclock(LOCK_SH): -------
bool(true)
------ fclock(LOCK_SH|LOCK_NB): -------
bool(true)
------ fclock(LOCK_EX): -------
bool(true)
------ fclock(LOCK_EX|LOCK_NB): -------
bool(true)
------ fclock(LOCK_UN): -------
bool(true)
------ fclock(LOCK_UN|LOCK_NB): -------
bool(true)