bool(true)
bool(true)

------ valid stream: -------
bool(true)

------ stream_cast not implemented: -------

Warning: stream_select(): test_wrapper_base::stream_cast is not implemented! in %s

Warning: stream_select(): cannot represent a stream of type user-space as a select()able descriptor in %s

Warning: stream_select(): No stream arrays were passed in %s
bool(false)

------ return value is false: -------

Warning: stream_select(): cannot represent a stream of type user-space as a select()able descriptor in %s

Warning: stream_select(): No stream arrays were passed in %s
bool(false)

------ return value not a stream resource: -------

Warning: stream_select(): supplied argument is not a valid stream resource in %s

Warning: stream_select(): test_wrapper::stream_cast must return a stream resource in %s

Warning: stream_select(): cannot represent a stream of type user-space as a select()able descriptor in %s

Warning: stream_select(): No stream arrays were passed in %s
bool(false)

------ return value is stream itself: -------

Warning: stream_select(): test_wrapper::stream_cast must not return itself in %s

Warning: stream_select(): cannot represent a stream of type user-space as a select()able descriptor in %s

Warning: stream_select(): No stream arrays were passed in %s
bool(false)

------ return value cannot be casted: -------

Warning: stream_select(): test_wrapper_base::stream_cast is not implemented! in %s

Warning: stream_select(): cannot represent a stream of type user-space as a select()able descriptor in %s

Warning: stream_select(): cannot represent a stream of type user-space as a select()able descriptor in %s

Warning: stream_select(): No stream arrays were passed in %s
bool(false)