Warning: ob_start(): class 'nonExistent' not found in %s on line 13

Notice: ob_start(): failed to create buffer in %s on line 13
bool(false)

Warning: ob_start(): class 'C' does not have a method 'nonExistent' in %s on line 14

Notice: ob_start(): failed to create buffer in %s on line 14
bool(false)

Warning: ob_start(): class 'C' does not have a method 'no' in %s on line 15

Notice: ob_start(): failed to create buffer in %s on line 15
bool(false)

Warning: ob_start(): function 'no' not found or invalid function name in %s on line 16

Notice: ob_start(): failed to create buffer in %s on line 16
bool(false)
done