- Too many arguments

Warning: ob_start() expects at most 3 parameters, 4 given in %s on line 17
NULL

- Arg 1 wrong type

Warning: ob_start(): no array or string given in %s on line 20

Notice: ob_start(): failed to create buffer in %s on line 20
bool(false)

- Arg 2 wrong type

Warning: ob_start() expects parameter 2 to be integer, string given in %s on line 23
NULL

- Arg 3 wrong type

Warning: ob_start() expects parameter 3 to be integer, string given in %s on line 26
NULL