[callback:1]All of the following calls will fail to clean/remove the topmost buffer:

Notice: ob_clean(): failed to delete buffer of callback (0) in %s on line 11
bool(false)

Notice: ob_end_clean(): failed to discard buffer of callback (0) in %s on line 12
bool(false)

Notice: ob_end_flush(): failed to send buffer of callback (0) in %s on line 13
bool(false)
The OB nesting will still be 1 level deep:
int(1)