---> Test arrays: 

Warning: ob_start(): array must have exactly two members in %s on line 44

Notice: ob_start(): failed to create buffer in %s on line 44
bool(false)
Array
(
)

Warning: ob_start(): class 'f' not found in %s on line 47

Notice: ob_start(): failed to create buffer in %s on line 47
bool(false)
Array
(
)

Warning: ob_start(): array must have exactly two members in %s on line 50

Notice: ob_start(): failed to create buffer in %s on line 50
bool(false)
Array
(
)

Warning: ob_start(): array must have exactly two members in %s on line 53

Notice: ob_start(): failed to create buffer in %s on line 53
bool(false)
Array
(
)

Warning: ob_start(): array must have exactly two members in %s on line 56

Notice: ob_start(): failed to create buffer in %s on line 56
bool(false)
Array
(
)
C::h[call:1; len:37; id:originalID] - bool(true)
Array
(
    [0] => C::h
)

C::h[call:2; len:37; id:changedID] - bool(true)
Array
(
    [0] => C::h
)


Warning: ob_start(): array must have exactly two members in %s on line 68

Notice: ob_start(): failed to create buffer in %s on line 68
bool(false)
Array
(
)