Warning: Phar::mungServer() expects parameter 1 to be array, %string given in %sbadparameters.php on line %d

Warning: Phar::createDefaultStub() expects parameter 1 to be a valid path, array given in %sbadparameters.php on line %d

Warning: Phar::loadPhar() expects parameter 1 to be a valid path, array given in %sbadparameters.php on line %d

Warning: Phar::canCompress() expects parameter 1 to be integer, %string given in %sbadparameters.php on line %d

Exception: Phar::__construct() expects parameter 1 to be a valid path, array given in %sbadparameters.php on line %d

Warning: Phar::convertToExecutable() expects parameter 1 to be integer, array given in %sbadparameters.php on line %d

Warning: Phar::convertToData() expects parameter 1 to be integer, array given in %sbadparameters.php on line %d

Warning: PharData::delete() expects parameter 1 to be a valid path, array given in %sbadparameters.php on line %d
Cannot write out phar archive, phar is read-only
Entry oops does not exist and cannot be deleted
%sfiles/frontcontroller10.phar
Cannot write out phar archive, phar is read-only
A Phar alias cannot be set in a plain tar archive

Warning: Phar::setAlias() expects parameter 1 to be %string, array given in %sbadparameters.php on line %d
Cannot change stub, phar is read-only
A Phar stub cannot be set in a plain tar archive

Warning: Phar::setStub() expects parameter 1 to be %string, array given in %sbadparameters.php on line %d
A Phar stub cannot be set in a plain tar archive

Warning: Phar::setDefaultStub() expects parameter 1 to be %string, array given in %sbadparameters.php on line %d
Cannot change stub: phar.readonly=1
Cannot set signature algorithm, phar is read-only

Warning: Phar::compress() expects parameter 1 to be integer, array given in %sbadparameters.php on line %d
Cannot compress phar archive, phar is read-only

Warning: Phar::compressFiles() expects parameter 1 to be integer, array given in %sbadparameters.php on line %d
Phar is readonly, cannot change compression

Warning: Phar::copy() expects exactly 2 parameters, 1 given in %sbadparameters.php on line %d
Cannot copy "a" to "b", phar is read-only

Warning: Phar::offsetExists() expects parameter 1 to be a valid path, array given in %sbadparameters.php on line %d

Warning: Phar::offsetGet() expects parameter 1 to be a valid path, array given in %sbadparameters.php on line %d

Warning: Phar::offsetSet() expects exactly 2 parameters, 1 given in %sbadparameters.php on line %d

Warning: PharData::offsetUnset() expects parameter 1 to be a valid path, array given in %sbadparameters.php on line %d
Write operations disabled by the php.ini setting phar.readonly

Warning: Phar::addEmptyDir() expects parameter 1 to be a valid path, array given in %sbadparameters.php on line %d

Warning: Phar::addFile() expects parameter 1 to be a valid path, array given in %sbadparameters.php on line %d

Warning: Phar::addFromString() expects exactly 2 parameters, 1 given in %sbadparameters.php on line %d
Write operations disabled by the php.ini setting phar.readonly

Warning: Phar::setMetadata() expects exactly 1 parameter, 2 given in %sbadparameters.php on line %d
Write operations disabled by the php.ini setting phar.readonly
===DONE===