testing has_dimension
bool(true)
bool(false)
bool(false)
testing property access
string(4) "data"

Notice: Trying to get property of non-object in %s on line %d
NULL
testing offset not a long
array(1) {
  [0]=>
  string(4) "test"
}

Notice: Trying to get property of non-object in %s on line %d
bool(false)
NULL
array(1) {
  [0]=>
  string(4) "test"
}
string(4) "test"
bool(true)
string(4) "data"
string(4) "test"
string(4) "test"
bool(true)
string(4) "data"
string(4) "test"
testing read_dimension with null offset
NULL
testing attribute access
string(4) "href"
==DONE==